cellList
NAME
cellList - cellList class.
SYNOPSIS
#include <cellList.h>
Public Member Functions
cellList (std::vector< double >, double, std::vector< atom * >)
void sortIntoCells (std::vector< atom * >)
void sortIntoCells (std::vector< atom > *)
void insertParticle (atom *)
void swapAndDeleteParticle (atom *, atom *)
void translateParticle (atom *, std::vector< double >)
int calcIndex (int, int, int)
int calcIndexS (int, int, int)
int calcIndex (double, double, double)
int calcIndexS (double, double, double)
Public Attributes
std::vector< double > cellSize
std::vector< double > box
int cellCountX
int cellCountY
int cellCountZ
int cellCountXY
int cellCount
std::vector< std::vector< atom * > > cells
std::vector< std::vector< unsigned int > > neighbours
Detailed Description
cellList class.
Definition at line 15 of file cellList.h.
Constructor & Destructor Documentation
cellList::cellList (std::vector< double > _box, double _cellSize, std::vector< atom * > _atoms)
Definition at line 3 of file cellList.cpp.
References box, cellCount, cellCountX, cellCountXY, cellCountY, cellCountZ, cells, cellSize, neighbours, and sortIntoCells().
                                                                                          {
                box = _box;
                                
                cellCountX = floor(_box[0]/_cellSize);
                cellCountY = floor(_box[1]/_cellSize);
                cellCountZ = floor(_box[2]/_cellSize);
                cellCountXY = cellCountX*cellCountY;
                cellCount = cellCountXY*cellCountZ;
                
                cellSize.resize(3);
                cellSize[0] = _box[0]/cellCountX;
                cellSize[1] = _box[1]/cellCountY;
                cellSize[2] = _box[2]/cellCountZ;
                // init neighbour list
                neighbours.assign(cellCount, std::vector < unsigned int > (26));
                initNeighbours();
                
                // init cell list
                cells.assign(cellCount, std::vector < atom* > (0));
                
                // clear all cells
                const unsigned int reserveCount = ceil(cellSize[0]*cellSize[1]*cellSize[2]);
                for (unsigned int i = 0; i < cells.size(); i++) {
                                cells[i].reserve(reserveCount);
                                cells[i].clear();
                }
                
                if (_atoms.size() > 0) {
                                //std::cout << "Sorting particles into cells." << std::endl;
                                sortIntoCells(_atoms);
                }
}
Member Function Documentation
int cellList::calcIndex (int k, int l, int m) [inline]
Definition at line 41 of file cellList.h.
References cellCountX, and cellCountXY.
Referenced by simSystem::getNeighborPositions(), insertParticle(), sortIntoCells(), swapAndDeleteParticle(), and translateParticle().
                                                   {
                return (k + l*cellCountX + m*cellCountXY);
}
int cellList::calcIndex (double _x, double _y, double _z) [inline]
Definition at line 69 of file cellList.h.
References cellCountX, cellCountXY, and cellSize.
                                                               {
                return (floor(_x/cellSize[0]) + floor(_y/cellSize[1])*cellCountX +floor(_z/cellSize[2])*cellCountXY);
}
int cellList::calcIndexS (int _k, int _l, int _m) [inline]
Definition at line 46 of file cellList.h.
References cellCountX, cellCountXY, cellCountY, and cellCountZ.
                                                       {
                int k = _k;
                int l = _l;
                int m = _m;
                if (k >= cellCountX)
                                k -= cellCountX;
                else if (k < 0)
                                k += cellCountX;
                                
                if (l >= cellCountY)
                                l -= cellCountY;
                else if (l < 0)
                                l += cellCountY;
                if (m >= cellCountZ)
                                m -= cellCountZ;
                else if (m < 0)
                                m += cellCountZ;
                                
                return (k + l*cellCountX + m*cellCountXY);
}
int cellList::calcIndexS (double _x, double _y, double _z) [inline]
Definition at line 74 of file cellList.h.
References box, cellCountX, cellCountXY, and cellSize.
                                                                {
                double x = _x;
                double y = _y;
                double z = _z;
                if (x >= box[0])
                                x -= box[0];
                else if (x < 0.0)
                                x += box[0];
                                
                if (y >= box[1])
                                y -= box[1];
                else if (y < 0.0)
                                y += box[1];
                if (z >= box[2])
                                z -= box[2];
                else if (z < 0.0)
                                z += box[2];
                
                return (floor(x/cellSize[0]) + floor(y/cellSize[1])*cellCountX +floor(z/cellSize[2])*cellCountXY);
}
void cellList::insertParticle (atom * _a)
Definition at line 95 of file cellList.cpp.
References calcIndex(), cells, and atom::pos.
Referenced by simSystem::insertAtom().
                                       {
                const unsigned index = calcIndex(_a->pos[0], _a->pos[1], _a->pos[2]);
                cells[index].push_back(_a);
}
void cellList::sortIntoCells (std::vector< atom * > _atoms)
Definition at line 73 of file cellList.cpp.
References calcIndex(), and cells.
Referenced by cellList().
                                                        {
                // clear all cells
                for (unsigned int i = 0; i < cells.size(); i++)
                                cells[i].clear();
                for (unsigned int i=0; i<_atoms.size(); i++) {
                                const unsigned index = calcIndex(_atoms[i]->pos[0], _atoms[i]->pos[1], _atoms[i]->pos[2]);
                                cells[index].push_back(_atoms[i]);
                }
}
void cellList::sortIntoCells (std::vector< atom > * _atoms)
Definition at line 84 of file cellList.cpp.
References calcIndex(), and cells.
                                                        {
                // clear all cells
                for (unsigned int i = 0; i < cells.size(); i++)
                                cells[i].clear();
                for (unsigned int i = 0; i < _atoms->size(); i++) {
                                const unsigned index = calcIndex(_atoms->at(i).pos[0], _atoms->at(i).pos[1], _atoms->at(i).pos[2]);
                                cells[index].push_back(&_atoms->at(i));
                }
}
void cellList::swapAndDeleteParticle (atom * _a, atom * _b)
Definition at line 102 of file cellList.cpp.
References calcIndex(), cells, and atom::pos.
Referenced by simSystem::deleteAtom().
                                                        {
                const unsigned indexA = calcIndex(_a->pos[0], _a->pos[1], _a->pos[2]);
                const unsigned indexB = calcIndex(_b->pos[0], _b->pos[1], _b->pos[2]);
                
                unsigned int cellIndexA = 0, cellIndexB = 0;
                bool foundCellIndexA = false, foundCellIndexB = false;
                
                // locate position of atom _a in its cell
                for (unsigned int i = 0; i < cells[indexA].size(); i++) { // error?
                                if (cells[indexA][i] == _a) {
                                                cellIndexA = i;
                                                foundCellIndexA = true;
                                                break;
                                }
                }
                
                // locate position of atom _b in its cell
                for (unsigned int i = 0; i < cells[indexB].size(); i++) { // error ?
                                if (cells[indexB][i] == _b) {
                                                cellIndexB = i;
                                                foundCellIndexB = true;
                                                break;
                                }
                }
                
                if (!foundCellIndexA || !foundCellIndexB) {
                                throw customException ("Failed to locate index in cell list properly");
                }
                
                // swap addresses
                cells[indexB][cellIndexB] = cells[indexA][cellIndexA];
                
                // remove _a from its cell
                cells[indexA].erase(cells[indexA].begin()+cellIndexA);
}
void cellList::translateParticle (atom * _a, std::vector< double > _oldPos)
Definition at line 139 of file cellList.cpp.
References calcIndex(), cells, and atom::pos.
Referenced by simSystem::translateAtom().
                                                                        {
                const unsigned indexOld = calcIndex(_oldPos[0], _oldPos[1], _oldPos[2]);
                const unsigned indexNew = calcIndex(_a->pos[0], _a->pos[1], _a->pos[2]);
                
                if (indexOld != indexNew) {
                                unsigned int cellIndexOld = 0;
                                bool foundCellIndexOld = false;
                
                                // locate position of atom _a in its cell
                                for (unsigned int i = 0; i < cells[indexOld].size(); i++) { //error?
                                                if (cells[indexOld][i] == _a) {
                                                                cellIndexOld = i;
                                                                foundCellIndexOld = true;
                                                                break;
                                                }
                                }
                                
                                if (!foundCellIndexOld) {
                                                throw customException ("Failed to locate cell index properly");
                                }
                                
                                // remove _a from its cell
                                cells[indexOld].erase(cells[indexOld].begin()+cellIndexOld);
                                
                                // insert _a into new cell
                                cells[indexNew].push_back(_a);
                }
}
Member Data Documentation
std::vector< double > cellList::box
Definition at line 34 of file cellList.h.
Referenced by calcIndexS(), and cellList().
int cellList::cellCount
Definition at line 36 of file cellList.h.
Referenced by cellList().
int cellList::cellCountX
Definition at line 36 of file cellList.h.
Referenced by calcIndex(), calcIndexS(), and cellList().
int cellList::cellCountXY
Definition at line 36 of file cellList.h.
Referenced by calcIndex(), calcIndexS(), and cellList().
int cellList::cellCountY
Definition at line 36 of file cellList.h.
Referenced by calcIndexS(), and cellList().
int cellList::cellCountZ
Definition at line 36 of file cellList.h.
Referenced by calcIndexS(), and cellList().
std::vector< std::vector < atom* > > cellList::cells
Definition at line 37 of file cellList.h.
Referenced by cellList(), simSystem::getNeighborPositions(), insertParticle(), sortIntoCells(), swapAndDeleteParticle(), and translateParticle().
std::vector< double > cellList::cellSize
Definition at line 33 of file cellList.h.
Referenced by calcIndex(), calcIndexS(), and cellList().
std::vector< std::vector < unsigned int > > cellList::neighbours
Definition at line 38 of file cellList.h.
Referenced by cellList(), and simSystem::getNeighborPositions().
Author
Generated automatically by Doxygen for Multicomponent Monte Carlo Simulation from the source code.