customException
NAME
customException -
Error handling via custom exceptions.
SYNOPSIS
#include <global.h>
Inherits exception.
Public Member Functions
const char * what () const throw ()
Return the user's message.
customException (std::string m='custom exception occurred')
Instantiate an exeption with a user-defined error message.
~customException () throw ()
Throw the message to the user.
Detailed Description
Error handling via custom exceptions.
Definition at line 128 of file global.h.
Constructor & Destructor Documentation
customException::customException (std::stringm = 'custom exception occurred') [inline]
Instantiate an exeption with a user-defined error message.
Definition at line 131 of file global.h.
customException::~customException () [inline]
Throw the message to the user.
Definition at line 132 of file global.h.
Member Function Documentation
const char* customException::what () const [inline]
Return the user's message.
Definition at line 130 of file global.h.
Referenced by compositeBarrier::addCylinderZ(), compositeBarrier::addHardWallZ(), simSystem::addPotential(), compositeBarrier::addRightTriangleXZ(), compositeBarrier::addSquareWellWallZ(), initializeSystemBarriers(), rightTriangleXZ::inside(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), moves::makeMove(), moves::moves(), performCrossover(), performTMMC(), performWALA(), simSystem::readConfig(), dynamic_one_dim_histogram::record(), simSystem::refineEnergyHistogramBounds(), simSystem::restartExtMoments(), simSystem::scratchEnergy(), setup(), simSystem::startTMMC(), simSystem::startWALA(), and tmmc::updateC().
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.