.TH "/home/nam4/Desktop/sandbox/FHMCSimulation/src/moves.h" 3 "Thu Dec 22 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/moves.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'global\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBmcMove\fP"
.br
.RI "\fIVirtual base class for all Monte Carlo moves\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMOVE_SUCCESS\fP   1"
.br
.RI "\fIReturned by \fBmcMove\fP if move was successful\&. \fP"
.ti -1c
.RI "#define \fBMOVE_FAILURE\fP   0"
.br
.RI "\fIReturned by \fBmcMove\fP if move was not successful\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MOVE_FAILURE   0"

.PP
Returned by \fBmcMove\fP if move was not successful\&. 
.PP
Definition at line 5 of file moves\&.h\&.
.PP
Referenced by aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), insertParticle::make(), swapParticles::make(), aggVolBiasInsert::make(), and aggVolBiasDelete::make()\&.
.SS "#define MOVE_SUCCESS   1"

.PP
Returned by \fBmcMove\fP if move was successful\&. 
.PP
Definition at line 4 of file moves\&.h\&.
.PP
Referenced by aggVolBias3::make(), translateParticle::make(), deleteParticle::make(), insertParticle::make(), and swapParticles::make()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
