/home/nam4/Desktop/sandbox/FHMCSimulation/src/system.h
NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/system.h -
SYNOPSIS
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <iostream>
#include <stdlib.h>
#include <exception>
#include <map>
#include <cmath>
#include <iomanip>
#include <memory>
#include 'potentials.h'
#include 'atom.h'
#include 'cellList.h'
#include 'bias.h'
#include 'global.h'
#include 'histogram.h'
#include 'barrier.h'
Data Structures
class simSystem
System information for the simulation.
Functions
const double calculateBias (simSystem &sys, const int nTotFinal, const int mFinal)
Calculate the bias based on a systems current state and the next state being proposed.
Function Documentation
const double calculateBias (simSystem &sys, const intnTotFinal, const intmFinal)
Calculate the bias based on a systems current state and the next state being proposed.
Parameters:
sys System object containing the current state of the system.
nTotFinal Total atoms in the proposed final state.
mFinal Final value of the expanded ensemble state of the system.
p_u Ratio of the system's partition in the final and initial state (e.g. unbiased p_acc = min(1, p_u)).
Returns:
rel_bias The value of the relative bias to apply in the metropolis criteria during sampling
Definition at line 1741 of file system.cpp.
References __BIAS_INT_TYPE__, tmmc::getAddress(), wala::getAddress(), tmmc::getBias(), wala::getBias(), simSystem::getCurrentM(), simSystem::getTotN(), simSystem::tmmcBias, simSystem::useTMMC, simSystem::useWALA, and simSystem::wlBias.
Referenced by aggVolBias3::make(), translateParticle::make(), deleteParticle::make(), insertParticle::make(), and swapParticles::make().
                                                                                   {
    double rel_bias = 1.0;
    if (sys.useTMMC && !sys.useWALA) {
        // TMMC biasing
        const __BIAS_INT_TYPE__ address1 = sys.tmmcBias->getAddress(sys.getTotN(), sys.getCurrentM()), address2 = sys.tmmcBias->getAddress(nTotFinal, mFinal);
        const double b1 = sys.tmmcBias->getBias (address1), b2 = sys.tmmcBias->getBias (address2);
        rel_bias = exp(b2-b1);
    } else if (!sys.useTMMC && sys.useWALA) {
        // Wang-Landau Biasing
        const __BIAS_INT_TYPE__ address1 = sys.wlBias->getAddress(sys.getTotN(), sys.getCurrentM()), address2 = sys.wlBias->getAddress(nTotFinal, mFinal);
        const double b1 = sys.wlBias->getBias (address1), b2 = sys.wlBias->getBias (address2);
        rel_bias = exp(b2-b1);
    } else if (sys.useTMMC && sys.useWALA) {
        // Crossover phase where we use WL but update TMMC collection matrix
        const int address1 = sys.wlBias->getAddress(sys.getTotN(), sys.getCurrentM()), address2 = sys.wlBias->getAddress(nTotFinal, mFinal);
        const double b1 = sys.wlBias->getBias (address1), b2 = sys.wlBias->getBias (address2);
        rel_bias = exp(b2-b1);
    } else {
        // No biasing
        rel_bias = 1.0;
    }
    return rel_bias;
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.