/Users/nam4/Desktop/omcs/src/system.cpp
NAME
/Users/nam4/Desktop/omcs/src/system.cpp -
SYNOPSIS
#include 'system.h'
Functions
const double calculateBias (simSystem &sys, const int nTotFinal, const double p_u)
Calculate the bias based on a systems current state and the next state being proposed.
Function Documentation
const double calculateBias (simSystem & sys, const int nTotFinal, const double p_u)
Calculate the bias based on a systems current state and the next state being proposed.
Parameters:
sys System object containing the current state of the system.
nTotFinal Total atoms in the proposed final state.
p_u Ratio of the system's partition in the final and initial state (e.g. unbiased p_acc = min(1, p_u)).
Returns:
rel_bias The value of the relative bias to apply in the metropolis criteria during sampling
Definition at line 759 of file system.cpp.
References __BIAS_INT_TYPE__, tmmc::getAddress(), wala::getAddress(), tmmc::getBias(), wala::getBias(), simSystem::getTotN(), simSystem::tmmcBias, tmmc::updateC(), simSystem::useTMMC, simSystem::useWALA, and simSystem::wlBias.
Referenced by deleteParticle::make(), translateParticle::make(), swapParticles::make(), and insertParticle::make().
                                                                                   {
                double rel_bias = 1.0;
                
                if (sys.useTMMC && !sys.useWALA) {
                                // TMMC biasing
                                const __BIAS_INT_TYPE__ address1 = sys.tmmcBias->getAddress(sys.getTotN()), address2 = sys.tmmcBias->getAddress(nTotFinal);
                                const double b1 = sys.tmmcBias->getBias (address1), b2 = sys.tmmcBias->getBias (address2);
                                rel_bias = exp(b2-b1);
                                sys.tmmcBias->updateC (sys.getTotN(), nTotFinal, std::min(1.0, p_u));
    } else if (!sys.useTMMC && sys.useWALA) {
                // Wang-Landau Biasing
                const __BIAS_INT_TYPE__ address1 = sys.wlBias->getAddress(sys.getTotN()), address2 = sys.wlBias->getAddress(nTotFinal);
                const double b1 = sys.wlBias->getBias (address1), b2 = sys.wlBias->getBias (address2);
                rel_bias = exp(b2-b1);
    } else if (sys.useTMMC && sys.useWALA) {
                // Crossover phase where we use WL but update TMMC collection matrix
                const int address1 = sys.wlBias->getAddress(sys.getTotN()), address2 = sys.wlBias->getAddress(nTotFinal);
                const double b1 = sys.wlBias->getBias (address1), b2 = sys.wlBias->getBias (address2);
                rel_bias = exp(b2-b1);
                sys.tmmcBias->updateC (sys.getTotN(), nTotFinal, std::min(1.0, p_u));
    } else {
                // No biasing
                rel_bias = 1.0;
    }
                
                return rel_bias;
}
Author
Generated automatically by Doxygen for Multicomponent Monte Carlo Simulation from the source code.