wala
NAME
wala -
Wang-Landau biasing class.
SYNOPSIS
#include <bias.h>
Public Member Functions
wala ()
wala (const double lnF, const double g, const double s, const int Nmax, const int Nmin, const int Mtot, const std::vector< double > box)
Wang-Landau biasing constructor.
void update (const int Nval, const int Mval)
Update the estimate of the macrostate distribution.
void iterateForward ()
This should only be called when the 'flatness' criterion is met.
void print (const std::string fileName, const bool printH=false)
Print the UN-NORMALIZED biasing function (lnPI) and possible the visted states histogram to files.
void readlnPI (const std::string fileName)
Read the macrostate distribution (biasing function) from a file.
void readH (const std::string fileName)
Read the visited states histogram from a file.
void setlnPI (const std::vector< double > &lnPIguess)
Blindly assign a guess of the macrostate distribution.
bool evaluateFlatness ()
Evaluate if the visited states histogram is approxiamtely 'flat'.
const __BIAS_INT_TYPE__ getAddress (const int Nval, const int Mval)
For multidimensional Wang-Landau biasing, get the 1D coordinate of the macrostate distribution estimate (bias) for multidimensional data.
const double lnF ()
const double getBias (const int address)
const std::vector< double > getlnPI ()
Return the current estimate of the macrostate distribution.
const std::vector< double > getH ()
Return the visited-states histogram.
Detailed Description
Wang-Landau biasing class.
Definition at line 66 of file bias.h.
Constructor & Destructor Documentation
wala::wala () [inline]
Definition at line 68 of file bias.h.
{};
wala::wala (const doublelnF, const doubleg, const doubles, const intNmax, const intNmin, const intMtot, const std::vector< double >box)
Wang-Landau biasing constructor.
Parameters:
lnF Factor by which the estimate of the density of states in updated each time it is visited.
g Factor by which lnF is reduced (multiplied) once 'flatness' has been achieved.
s Factor by which the min(H) must be within the mean of H to be considered 'flat', e.g. 0.8 --> min is within 20% error of mean
Nmax Upper bound for total number of particles.
Nmin Lower bound for total number of particles.
Mtot Total number of expanded ensemble states in a system.
box Vector of simulation box size.
Definition at line 497 of file bias.cpp.
References __BIAS_INT_TYPE__, and lnF().
                                                                                                                                          {
    if (lnF < 0) {
        throw customException ("lnF in Wang-Landau cannot be < 0");
    }
    lnF_ = lnF;
    if (g <= 0 || g >= 1) {
        throw customException ("In Wang-Landau 0 < g < 1");
    }
    g_ = g;
    if (s <= 0 || s >= 1) {
        throw customException ("In Wang-Landau 0 < s < 1");
    }
    s_ = s;
    if (Nmin > Nmax) {
        throw customException ("Nmin > Nmax in Wang-Landau object");
    }
    if (Nmin < 0) {
        throw customException ("Nmin < 0 in Wang-Landau object");
    }
    if (Mtot < 1) {
        throw customException ("Mtot < 1 in Wang-Landau object");
    }
    Mtot_ = Mtot;
    if (box.size() != 3) {
        throw customException ("Illegal number of box dimensions in Wang-Landau");
    }
    for (unsigned int i = 0; i < box.size(); ++i) {
        if (box[i] < 0) {
            throw customException ("Illegal box dimensions in Wang-Landau");
        }
    }
    box_.resize(3, 0);
    box_ = box;
    __BIAS_INT_TYPE__ size = (Nmax - Nmin + 1);
    Nmin_ = Nmin;
    Nmax_ = Nmax;
    // attempt to allocate memory for macrostate distribution matrix and initializes it all to 0
    try {
        lnPI_.resize(size*Mtot_, 0.0);
    } catch (const std::bad_alloc &ce) {
        throw customException ("Out of memory, cannot allocate space for macrostate distribution matrix in wala");
    }
    // initialize the visited-states histogram
    try {
        H_.resize(size*Mtot_, 0.0);
    } catch (const std::bad_alloc &ce) {
        throw customException ("Out of memory, cannot allocate space for visited-states histogram in wala");
    }
}
Member Function Documentation
bool wala::evaluateFlatness ()
Evaluate if the visited states histogram is approxiamtely 'flat'.
Returns:
Returns whether the histogram is flat or not.
Definition at line 587 of file bias.cpp.
References specExp.
Referenced by performCrossover(), and performWALA().
                             {
    double min = H_[0], lnMean = -DBL_MAX;
    for (unsigned int i = 0; i < H_.size() - (Mtot_-1); ++i) { // insert routine prevents the sampling past N = Nmax, M = 0, so N = Nmax and M > 0 are validly empty
        if (H_[i] < min) {
            min = H_[i];
        }
        // summing so many doubles may overrun DBL_MAX, so instead track the lnMean
        lnMean = specExp(lnMean, log(H_[i]));
    }
    lnMean -= log(H_.size() - (Mtot_-1));
    if (log(min) - lnMean > log(s_)) {
        return true;
    }
    return false;
}
const __BIAS_INT_TYPE__ wala::getAddress (const intNval, const intMval)
For multidimensional Wang-Landau biasing, get the 1D coordinate of the macrostate distribution estimate (bias) for multidimensional data.
Parameters:
Nval Total number of atoms in the system
Mval Current value of the expanded ensemble state of the system
Definition at line 563 of file bias.cpp.
Referenced by calculateBias(), and update().
                                                                        {
    if (Nval > Nmax_ || Nval < Nmin_ || Mval < 0 || Mval > Mtot_-1) {
        throw customException ("N, M out of bounds in Wang-Landau object, cannot retrieve address");
    }
    return (Nval - Nmin_)*Mtot_ + Mval;
}
const double wala::getBias (const intaddress) [inline]
Definition at line 80 of file bias.h.
Referenced by calculateBias().
{ return -lnPI_[address]; }
const std::vector<double> wala::getH () [inline]
Return the visited-states histogram.
Definition at line 82 of file bias.h.
const std::vector<double> wala::getlnPI () [inline]
Return the current estimate of the macrostate distribution.
Definition at line 81 of file bias.h.
void wala::iterateForward ()
This should only be called when the 'flatness' criterion is met. This then resets the visited-states histogram H, and decrements lnF.
Definition at line 608 of file bias.cpp.
Referenced by performCrossover(), and performWALA().
                           {
    lnF_ = lnF_*g_;
    std::fill(H_.begin(), H_.end(), 0);
}
const double wala::lnF () [inline]
Definition at line 79 of file bias.h.
Referenced by checkpoint::dump(), performCrossover(), performWALA(), and wala().
{ return lnF_; }
void wala::print (const std::stringfileName, const boolprintH = false)
Print the UN-NORMALIZED biasing function (lnPI) and possible the visted states histogram to files. Will overwrite the files if another with that name exists. Prints in netCDF format if enabled.
Parameters:
fileName Name of the file to print to. Will append with '_lnPI' and '_H' for the macrostate distribution and visited-states histogram, respectively.
printH Defaults to false, but if true will also print the visited states histogram.
Definition at line 621 of file bias.cpp.
Referenced by checkpoint::dump().
                                                       {
#ifdef NETCDF_CAPABLE
    // Print visited-states histogram
    if (printH) {
        const std::string name = fileName + "_H.nc";
        try {
            // print complete visited states histogram to restart / visualize progress
            NcFile outFile(name.c_str(), NcFile::replace);
            NcDim probDim = outFile.addDim("vectorized_position", H_.size());
            NcVar probVar = outFile.addVar("H", ncDouble, probDim);
            std::string attName = "species_total_upper_bound";
            probVar.putAtt(attName.c_str(), std::to_string(Nmax_).c_str());
            attName = "species_upper_lower_bound";
            probVar.putAtt(attName.c_str(), std::to_string(Nmin_).c_str());
            attName = "volume";
            double V = box_[0]*box_[1]*box_[2];
            probVar.putAtt(attName.c_str(), std::to_string(V).c_str());
            probVar.putVar(&H_[0]);
        } catch (NcException ioe) {
            throw customException ("Unable to write Wang-Landau visited states histogram to "+name);
        }
    }
    // Print lnPI (bias) matrix
    const std::string name = fileName + "_lnPI.nc";
    try {
        // only ALL states for restarting purposes
        NcFile outFile(name.c_str(), NcFile::replace);
        NcDim probDim = outFile.addDim("vectorized_position", lnPI_.size());
        NcVar probVar = outFile.addVar("lnPI", ncDouble, probDim);
        std::string attName = "species_total_upper_bound";
        probVar.putAtt(attName.c_str(), std::to_string(Nmax_).c_str());
        attName = "species_total_lower_bound";
        probVar.putAtt(attName.c_str(), std::to_string(Nmin_).c_str());
        attName = "volume";
        double V = box_[0]*box_[1]*box_[2];
        probVar.putAtt(attName.c_str(), std::to_string(V).c_str());
        probVar.putVar(&lnPI_[0]);
    } catch (NcException ioe) {
        throw customException ("Unable to write Wang-Landau lnPI histogram to "+name);
    }
#else
    // Print visited-states histogram
    if (printH) {
        // print complete visited states histogram to restart / visualize progress
        std::ofstream of;
        std::string name = fileName+"_H.dat";
        of.open(name.c_str(), std::ofstream::out);
        if (!of.is_open()) {
            throw customException ("Unable to write Wang-Landau visited states histogram to "+name);
        }
        of << "# Visited states histogram in single row (vectorized) notation." << std::endl;
        of << "# species_total_upper_bound: " << Nmax_ << std::endl;
        of << "# species_total_lower_bound: " << Nmin_ << std::endl;
        double V = box_[0]*box_[1]*box_[2];
        of << "# volume: " << std::setprecision(15) << V << std::endl;
        for (long long int i = 0; i < H_.size(); ++i) {
            of << std::setprecision(15) << H_[i] << std::endl;
        }
        of.close();
    }
    // Print lnPI (bias) matrix
    std::ofstream of;
    std::string name = fileName+"_lnPI.dat";
    of.open(name.c_str(), std::ofstream::out);
    if (!of.is_open()) {
        throw customException ("Unable to write Wang-Landau lnPI histogram to "+name);
    }
    of << "# lnPI (bias) matrix in single row (vectorized) notation." << std::endl;
    of << "# species_total_upper_bound: " << Nmax_ << std::endl;
    of << "# species_total_lower_bound: " << Nmin_ << std::endl;
    double V = box_[0]*box_[1]*box_[2];
    of << "# volume: " << std::setprecision(15) << V << std::endl;
    for (long long int i = 0; i < lnPI_.size(); ++i) {
        of << std::setprecision(15) << lnPI_[i] << std::endl; // only ALL states for restarting purposes
    }
    of.close();
#endif
}
void wala::readH (const std::stringfileName)
Read the visited states histogram from a file. This assumes the user has already guaranteed that the bounds are consistent, e.g. Nmin and Nmax, as it will not check this automatically. Also assumes file was generated by this code. 'Hand made' ones might have formatting issues since parsing is done based on tokens.
Parameters:
fileName Name of file containing visited states. Must include file extension.
Definition at line 744 of file bias.cpp.
Referenced by checkpoint::load().
                                          {
#ifdef NETCDF_CAPABLE
    try {
        NcFile dataFile (fileName.c_str(), NcFile::read);
        NcVar H_data = dataFile.getVar("H");
        if (H_data.isNull()) throw customException("Wang-Landau visited states matrix was empty, cannot read from "+fileName);
        H_data.getVar(&H_[0]);
    } catch (NcException ioe) {
        throw customException ("Unable to read Wang-Landau visited states matrix from "+fileName);
    }
#else
    std::ifstream infile (fileName.c_str());
    if (!infile.is_open()) {
        throw customException ("Unable to read Wang-Landau visited states matrix from "+fileName);
    }
    std::string line;
    int lineIndex = 0;
    while(std::getline(infile,line)) {
        std::stringstream lineStream(line);
        // skip any header information
        if (line.compare(0,1,"#",0,1) != 0) {
            H_[lineIndex] = atof(line.c_str());
            lineIndex++;
        }
    }
#endif
}
void wala::readlnPI (const std::stringfileName)
Read the macrostate distribution (biasing function) from a file. This assumes the user has already guaranteed that the bounds are consistent, e.g. Nmin and Nmax, as it will not check this automatically. Also assumes file was generated by this code. 'Hand made' ones might have formatting issues since parsing is done based on tokens.
Parameters:
fileName Name of file containing lnPI. Must include file extension.
Definition at line 709 of file bias.cpp.
Referenced by checkpoint::load(), and performWALA().
                                             {
#ifdef NETCDF_CAPABLE
    try {
        NcFile dataFile (fileName.c_str(), NcFile::read);
        NcVar lnPI_data = dataFile.getVar("lnPI");
        if (lnPI_data.isNull()) throw customException("Wang-Landau macrostate distribution matrix (biasing function) was empty, cannot read from "+fileName);
        lnPI_data.getVar(&lnPI_[0]);
    } catch (NcException ioe) {
        throw customException ("Unable to read Wang-Landau lnPI from "+fileName);
    }
#else
    std::ifstream infile (fileName.c_str());
    if (!infile.is_open()) {
        throw customException ("Unable to read Wang-Landau lnPI from "+fileName);
    }
    std::string line;
    int lineIndex = 0;
    while(std::getline(infile,line)) {
        std::stringstream lineStream(line);
        // skip any header information
        if (line.compare(0,1,"#",0,1) != 0) {
            lnPI_[lineIndex] = atof(line.c_str());
            lineIndex++;
        }
    }
#endif
}
void wala::setlnPI (const std::vector< double > &lnPIguess) [inline]
Blindly assign a guess of the macrostate distribution.
Definition at line 76 of file bias.h.
void wala::update (const intNval, const intMval)
Update the estimate of the macrostate distribution.
Parameters:
Nval Total current number of atoms in the system
Mval Current value of the expanded ensemble state of the system
Definition at line 576 of file bias.cpp.
References __BIAS_INT_TYPE__, and getAddress().
Referenced by aggVolBias3::make(), translateParticle::make(), deleteParticle::make(), insertParticle::make(), and swapParticles::make().
                                                 {
    __BIAS_INT_TYPE__ address = getAddress (Nval, Mval);
    lnPI_[address] += lnF_;
    H_[address] += 1.0;
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.