.TH "aggVolBiasDelete" 3 "Fri Dec 23 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aggVolBiasDelete \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aggvolbias\&.h>\fP
.PP
Inherits \fBmcMove\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaggVolBiasDelete\fP ()"
.br
.ti -1c
.RI "\fBaggVolBiasDelete\fP (const int typeIndex, const double pBias, const std::vector< double > rc, const std::string tag)"
.br
.RI "\fIInstantiate a grand canonical aggregation-volume bias move to delete particles\&. \fP"
.ti -1c
.RI "int \fBmake\fP (\fBsimSystem\fP &sys)"
.br
.RI "\fIUse aggregation-volume bias to delete a particle from the system\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 39 of file aggvolbias\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "aggVolBiasDelete::aggVolBiasDelete ()\fC [inline]\fP"

.PP
Definition at line 41 of file aggvolbias\&.h\&.
.PP
References mcMove::changeN_\&.
.PP
.nf
41 { changeN_ = true; pBias_ = 0; }
.fi
.SS "aggVolBiasDelete::aggVolBiasDelete (const inttypeIndex, const doublepBias, const std::vector< double >rc, const std::stringtag)"

.PP
Instantiate a grand canonical aggregation-volume bias move to delete particles\&. From Chen et al\&., J\&. Chem\&. Phys\&. 115 (2001)\&.
.PP
\fBParameters:\fP
.RS 4
\fItypeIndex\fP Type to consider deleting from the vicinity of 
.br
\fIpBias\fP Biasing probability 
.br
\fIrc\fP Radius (min, max) around particle of typeIndex to consider as being the 'in' region 
.br
\fItag\fP Name modifier to identify move to user 
.RE
.PP

.PP
Definition at line 54 of file aggvolbias\&.cpp\&.
.PP
References mcMove::changeN_, mcMove::name_, and mcMove::typeIndex_\&.
.PP
.nf
54                                                                                                                                {
55     typeIndex_ = typeIndex;
56         if (pBias < 1 && pBias > 0) {
57                 pBias_ = pBias;
58         } else {
59                 throw customException ("Bias probability must be > 0 and < 1 for aggVolBias moves");
60         }
61 
62         if (!(rc[0] > 0\&.0)) {
63                 throw customException ("Min neighborhood radius for aggVolBias must be > 0");
64         } else {
65                 rcmin_ = rc[0];
66         }
67 
68         if (!(rc[1] > rc[0])) {
69                 throw customException ("Max neighborhood radius for aggVolBias must be > min");
70         } else {
71                 rcmax_ = rc[1];
72         }
73 
74         name_ = tag + std::to_string(typeIndex);
75         changeN_ = true;
76 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "int aggVolBiasDelete::make (\fBsimSystem\fP &sys)\fC [virtual]\fP"

.PP
Use aggregation-volume bias to delete a particle from the system\&. All other information is stored in the \fBsimSystem\fP object\&.
.PP
\fBParameters:\fP
.RS 4
\fIsys\fP System object to attempt to delete particles from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
MOVE_SUCCESS if particle is deleted, otherwise MOVE_FAILURE if not\&. Will throw exceptions if there was an error\&. 
.RE
.PP

.PP
Implements \fBmcMove\fP\&.
.PP
Definition at line 85 of file aggvolbias\&.cpp\&.
.PP
References MOVE_FAILURE\&.
.PP
.nf
85                                           {
86         return MOVE_FAILURE;
87 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
