.TH "/home/nam4/Desktop/sandbox/FHMCSimulation/src/bias.cpp" 3 "Fri Dec 30 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/bias.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bias\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
