checkpoint
NAME
checkpoint -
Information to restart/checkpoint the simulation.
SYNOPSIS
#include <checkpoint.h>
Public Member Functions
checkpoint ()
checkpoint (const std::string directory, const long int frequency, simSystem &sys, const bool snaps=false, const bool override=false)
Read system state from a file.
~checkpoint ()
void load (simSystem &sys, const bool override)
Read state of a system from a json file.
void dump (simSystem &sys, const long long int moveCounter=0, const long long int sweepCounter=0, const bool refine=false)
Save the state of a system to a json file.
bool check (simSystem &sys, const long long int moveCounter=0, const long long int sweepCounter=0, const bool refine=false)
Check how long it has been since last checkpoint, and write new one if has exceeded frequency.
Data Fields
bool hasCheckpoint
At least one checkpoint has been made that the system can restart from.
bool takeSnaps
Save snapshot of the system each time a record is made.
bool tmmcDone
bool crossoverDone
bool walaDone
Progress of each stage, regardless of where the checkpoint indicated to start from.
bool resFromWALA
bool resFromCross
bool resFromTMMC
Flags corresponding to which stage the checkpoint indicated to restart from.
long int freq
Frequency (in seconds) that the system should print a new instantaneous snapshot of itself, does not load from checkpoints but is assigned when instantiated (is dumped though)
long long int moveCounter
Tracks the number of moves in a given sweep that have executed.
long long int sweepCounter
Tracks the number of sweeps that have executed.
double wala_lnF
Current value of lnF from WALA.
std::string dir
Name of the checkpoint directory containing the information to reinitialize the system (json)
std::string chkptName
Name of checkpoint file.
std::vector< double > elb
std::vector< double > eub
Upper and lower energy bounds for energy histogram.
Detailed Description
Information to restart/checkpoint the simulation.
Definition at line 22 of file checkpoint.h.
Constructor & Destructor Documentation
checkpoint::checkpoint () [inline]
Definition at line 24 of file checkpoint.h.
References crossoverDone, dir, freq, hasCheckpoint, resFromCross, resFromTMMC, resFromWALA, takeSnaps, tmmcDone, and walaDone.
{ tmmcDone = false; crossoverDone = false; walaDone = false; hasCheckpoint = false; resFromTMMC = false; resFromWALA = false; resFromCross = false; takeSnaps = false; freq = -1; dir = "checkpt"; }
checkpoint::checkpoint (const std::stringdirectory, const long intfrequency, simSystem &sys, const boolsnaps = false, const booloverride = false)
Read system state from a file. If checkpoint directory is found and json file is valid, data is loaded from it. Note that although this stores the frequency, it does not use the value it dumps to file. This class always uses the frequency given when the class is instantiated.
Parameters:
dir Directory where system state was saved
frequency Frquency to take snapshots/checkpoints of the system (< 0 disables)
sys System to checkpoint
snaps Take snapshots each time a record is made to make a movie? (default = false)
override Manually override exceptions, use with extreme caution (default=false)
Definition at line 14 of file checkpoint.cpp.
References chkptName, crossoverDone, dir, fileExists(), freq, hasCheckpoint, load(), moveCounter, resFromCross, resFromTMMC, resFromWALA, simSystem::restartFromTMMC, sweepCounter, takeSnaps, tmmcDone, and walaDone.
                                                                                                                                  {
    tmmcDone = false;
    crossoverDone = false;
    walaDone = false;
    hasCheckpoint = false;
    takeSnaps = snaps;
    dir = directory;
    freq = frequency;
    moveCounter = 0;
    sweepCounter = 0;
    resFromWALA = false;
    resFromCross = false;
    resFromTMMC = false;
    chkptName = dir+"/state.json";
    if (fileExists(chkptName)) {
        try {
            load(sys, override);
        } catch (std::exception &ex) {
            std::string a = "Unable to load checkpoint "+chkptName+" : ";
            std::string b = ex.what();
            throw customException (a+b);
        }
    } else {
        // Forcible skip to TMMC stage if want to manually start TMMC
        if (sys.restartFromTMMC){
            walaDone = true;
            crossoverDone = true;
        }
    }
    time(&lastCheckPt_); // Take time when object was instantiated as initial time so that check() has a point of reference
}
checkpoint::~checkpoint () [inline]
Definition at line 26 of file checkpoint.h.
{};
Member Function Documentation
bool checkpoint::check (simSystem &sys, const long long intmoveCounter = 0, const long long intsweepCounter = 0, const boolrefine = false)
Check how long it has been since last checkpoint, and write new one if has exceeded frequency.
Parameters:
sys System to checkpoint
moveCounter Number of moves out of a given sweep that have executed
sweepCounter Number of loops/sweeps that have executed
refine Refine the histogram boundaries before printing any? (default=false)
Returns:
bool Is a checkpoint being generated or not
Definition at line 297 of file checkpoint.cpp.
References dump(), and freq.
Referenced by performCrossover(), performTMMC(), and performWALA().
                                                                                                                            {
    if (freq > 0) {
        if (std::abs(difftime(time(&now_), lastCheckPt_)) >= freq) {
            dump(sys, moveCounter, sweepCounter, refine);
            return true;
        }
    }
    return false;
}
void checkpoint::dump (simSystem &sys, const long long intmoveCounter = 0, const long long intsweepCounter = 0, const boolrefine = false)
Save the state of a system to a json file. Creates the checkpoint directory if it doesn't exist.
Parameters:
sys System to checkpoint
moveCounter Number of moves out of a given sweep that have executed
sweepCounter Number of loops/sweeps that have executed
refine Refine the histogram boundaries before printing any? (default=false)
Definition at line 162 of file checkpoint.cpp.
References chkptName, crossoverDone, simSystem::crossoverTotalStepCounter, dir, elb, eub, simSystem::extMomCounter(), fileExists(), freq, simSystem::getELB(), simSystem::getEUB(), getTimeStamp(), simSystem::getTMMCBias(), simSystem::getWALABias(), hasCheckpoint, wala::lnF(), tmmc::print(), wala::print(), simSystem::printEnergyHistogram(), simSystem::printExtMoments(), simSystem::printPkHistogram(), simSystem::printSnapshot(), simSystem::refineEnergyHistogramBounds(), simSystem::refinePkHistogramBounds(), takeSnaps, tmmcDone, simSystem::tmmcTotalStepCounter, walaDone, and simSystem::walaTotalStepCounter.
Referenced by check().
                                                                                                                           {
    if (!fileExists(chkptName)) {
        std::string command = "mkdir -p "+dir+" && touch "+chkptName;
        const int succ = system(command.c_str());
        if (succ != 0) {
            throw customException("Unable to initialize checkpoint");
        }
    }
    rapidjson::StringBuffer s;
    rapidjson::PrettyWriter < rapidjson::StringBuffer > writer(s);
    hasCheckpoint = true;
    // Write restart/checkpoint options
    writer.StartObject();
    writer.String("tmmcDone");
    writer.Bool(tmmcDone);
    writer.String("crossoverDone");
    writer.Bool(crossoverDone);
    writer.String("walaDone");
    writer.Bool(walaDone);
    writer.String("hasCheckpoint");
    writer.Bool(hasCheckpoint);
    writer.String("takeSnaps");
    writer.Bool(takeSnaps);
    writer.String("freq");
    writer.Int64(freq);
    writer.String("dir");
    writer.String(dir.c_str());
    writer.String("moveCounter");
    writer.Double(moveCounter);
    writer.String("sweepCounter");
    writer.Double(sweepCounter);
    writer.String("walaTotalStepCounter");
    writer.Double(sys.walaTotalStepCounter);
    writer.String("crossoverTotalStepCounter");
    writer.Double(sys.crossoverTotalStepCounter);
    writer.String("tmmcTotalStepCounter");
    writer.Double(sys.tmmcTotalStepCounter);
    if (walaDone && crossoverDone) { // In final TMMC stage or just finished the TMMC (end of simulation)
        sys.getTMMCBias()->print(dir+"/tmmc", true, true);
        if (refine) {
            sys.refineEnergyHistogramBounds();
        }
        sys.printEnergyHistogram(dir+"/eHist", false); // Un-normalized Energy histogram
        if (refine) {
            sys.refinePkHistogramBounds();
        }
        sys.printPkHistogram(dir+"/pkHist", false); // Un-normalized Particle histogram
        sys.printExtMoments(dir+"/extMom", false); // Un-normalized Extensive moments, plus counter (number of times each recorded)
        writer.String("extMomCounter");
        std::vector < double > ctr = sys.extMomCounter();
        writer.StartArray();
        for (std::vector < double >::iterator it = ctr.begin(); it < ctr.end(); ++it) {
            writer.Double(*it);
        }
        writer.EndArray();
    } else if (walaDone && !crossoverDone && !tmmcDone) { // In crossover stage
        sys.getTMMCBias()->print(dir+"/tmmc", true, true);
        sys.getWALABias()->print(dir+"/wala", true);
        writer.String("wala_lnF");
        writer.Double(sys.getWALABias()->lnF());
        // Energy upper and lower bounds for histogram
        std::vector < double > elb = sys.getELB(), eub = sys.getEUB();
        writer.String("energyHistogramLB");
        writer.StartArray();
        for (std::vector < double >::iterator it = elb.begin(); it < elb.end(); ++it) {
            writer.Double(*it);
        }
        writer.EndArray();
        writer.String("energyHistogramUB");
        writer.StartArray();
        for (std::vector < double >::iterator it = eub.begin(); it < eub.end(); ++it) {
            writer.Double(*it);
        }
        writer.EndArray();
    } else if (!walaDone && !crossoverDone && !tmmcDone) { // In WALA stage
        sys.getWALABias()->print(dir+"/wala", true);
        writer.String("wala_lnF");
        writer.Double(sys.getWALABias()->lnF());
        // Energy upper and lower bounds for histogram
        std::vector < double > elb = sys.getELB(), eub = sys.getEUB();
        writer.String("energyHistogramLB");
        writer.StartArray();
        for (std::vector < double >::iterator it = elb.begin(); it < elb.end(); ++it) {
            writer.Double(*it);
        }
        writer.EndArray();
        writer.String("energyHistogramUB");
        writer.StartArray();
        for (std::vector < double >::iterator it = eub.begin(); it < eub.end(); ++it) {
            writer.Double(*it);
        }
        writer.EndArray();
    } else {
        throw customException ("Uncertain which stage simulation is in, so cannot checkpoint");
    }
    writer.EndObject();
    std::ofstream outData(chkptName.c_str());
    outData << s.GetString() << std::endl;
    sys.printSnapshot(dir+"/snap.xyz", getTimeStamp(), true); // Instantaneous snapshot
    if (takeSnaps) { // This only prints M = 0 atoms (fully inserted) to create a movie
        sys.printSnapshot(dir+"/movie.xyz", getTimeStamp(), false);
    }
    time(&lastCheckPt_);
}
void checkpoint::load (simSystem &sys, const booloverride)
Read state of a system from a json file.
Parameters:
sys System to checkpoint
override Manually override exceptions, use with extreme caution (default=false)
Definition at line 54 of file checkpoint.cpp.
References tmmc::calculatePI(), chkptName, crossoverDone, simSystem::crossoverTotalStepCounter, dir, elb, eub, fileExists(), simSystem::getTMMCBias(), simSystem::getTotalM(), simSystem::getWALABias(), hasCheckpoint, moveCounter, parseJson(), tmmc::readC(), simSystem::readConfig(), wala::readH(), tmmc::readHC(), wala::readlnPI(), resFromCross, resFromTMMC, resFromWALA, simSystem::restartEnergyHistogram(), simSystem::restartExtMoments(), simSystem::restartPkHistogram(), sendErr(), sendMsg(), simSystem::setELB(), simSystem::setEUB(), simSystem::startTMMC(), simSystem::startWALA(), sweepCounter, SYS_FAILURE, takeSnaps, tmmcDone, simSystem::tmmcSweepSize, simSystem::tmmcTotalStepCounter, simSystem::wala_g, wala_lnF, simSystem::wala_s, walaDone, and simSystem::walaTotalStepCounter.
Referenced by checkpoint().
                                                          {
    if (!fileExists(chkptName) && !override) {
        throw customException ("No checkpoint by the name: "+chkptName);
    }
    rapidjson::Document doc;
    try {
        parseJson (chkptName, doc);
        tmmcDone = doc["tmmcDone"].GetBool();
        crossoverDone = doc["crossoverDone"].GetBool();
        walaDone = doc["walaDone"].GetBool();
        hasCheckpoint = doc["hasCheckpoint"].GetBool();
        takeSnaps = doc["takeSnaps"].GetBool();
        dir = doc["dir"].GetString();
        moveCounter = (long long int)doc["moveCounter"].GetDouble();
        sweepCounter = (long long int)doc["sweepCounter"].GetDouble();
        sys.walaTotalStepCounter = (long double)doc["walaTotalStepCounter"].GetDouble();
        sys.crossoverTotalStepCounter = (long double)doc["crossoverTotalStepCounter"].GetDouble();
        sys.tmmcTotalStepCounter = (long double)doc["tmmcTotalStepCounter"].GetDouble();
        if (walaDone && crossoverDone) { // In final TMMC stage or just finished the TMMC (end of simulation)
            resFromTMMC = true;
            sys.startTMMC(sys.tmmcSweepSize, sys.getTotalM());
            sys.getTMMCBias()->readC(dir+"/tmmc_C.dat");
            sys.getTMMCBias()->readHC(dir+"/tmmc_HC.dat");
            sys.getTMMCBias()->calculatePI();
            std::vector < double > ctr (doc["extMomCounter"].Size(), 0);
            for (unsigned int i = 0; i < doc["extMomCounter"].Size(); ++i) {
                ctr[i] = doc["extMomCounter"][i].GetDouble();
            }
            sys.restartEnergyHistogram(dir+"/eHist");
            sys.restartPkHistogram(dir+"/pkHist");
            sys.restartExtMoments(dir+"/extMom", ctr);
        } else if (walaDone && !crossoverDone && !tmmcDone) { // In crossover stage
            resFromCross = true;
            sys.startTMMC(sys.tmmcSweepSize, sys.getTotalM());
            wala_lnF = doc["wala_lnF"].GetDouble();
            sys.startWALA (wala_lnF, sys.wala_g, sys.wala_s, sys.getTotalM());
            sys.getTMMCBias()->readC(dir+"/tmmc_C.dat");
            sys.getTMMCBias()->readHC(dir+"/tmmc_HC.dat");
            sys.getWALABias()->readlnPI(dir+"/wala_lnPI.dat");
            sys.getWALABias()->readH(dir+"/wala_H.dat");
            // Energy upper and lower bounds for histogram
            elb.resize(doc["energyHistogramLB"].Size(), 0);
            for (unsigned int i = 0; i < doc["energyHistogramLB"].Size(); ++i) {
                elb[i] = doc["energyHistogramLB"][i].GetDouble();
            }
            sys.setELB(elb);
            eub.resize(doc["energyHistogramUB"].Size(), 0);
            for (unsigned int i = 0; i < doc["energyHistogramUB"].Size(); ++i) {
                eub[i] = doc["energyHistogramUB"][i].GetDouble();
            }
            sys.setEUB(eub);
        } else if (!walaDone && !crossoverDone && !tmmcDone) { // In WALA stage and printed 1st checkpoint already
            resFromWALA = true;
            wala_lnF = doc["wala_lnF"].GetDouble();
            sys.startWALA (wala_lnF, sys.wala_g, sys.wala_s, sys.getTotalM());
            sys.getWALABias()->readlnPI(dir+"/wala_lnPI.dat");
            sys.getWALABias()->readH(dir+"/wala_H.dat");
            // Energy upper and lower bounds for histogram
            elb.resize(doc["energyHistogramLB"].Size(), 0);
            for (unsigned int i = 0; i < doc["energyHistogramLB"].Size(); ++i) {
                elb[i] = doc["energyHistogramLB"][i].GetDouble();
            }
            sys.setELB(elb);
            eub.resize(doc["energyHistogramUB"].Size(), 0);
            for (unsigned int i = 0; i < doc["energyHistogramUB"].Size(); ++i) {
                eub[i] = doc["energyHistogramUB"][i].GetDouble();
            }
            sys.setEUB(eub);
        } else {
            if (!override) {
                sendErr("Uncertain which stage simulation is in, so cannot checkpoint");
                exit(SYS_FAILURE);
            }
        }
        sys.readConfig(dir+"/snap.xyz");
        hasCheckpoint = true;
    } catch (std::exception &ex) {
        std::string msg = ex.what();
        if (!override) {
            hasCheckpoint = false;
            sendErr("Unable to load checkpoint "+msg);
            exit(SYS_FAILURE);
        } else {
            sendErr("Overriding the following errors to load checkpoint "+msg);
        }
    }
    sendMsg("Checkpoint loaded from "+chkptName);
}
Field Documentation
std::string checkpoint::chkptName
Name of checkpoint file.
Definition at line 43 of file checkpoint.h.
Referenced by checkpoint(), dump(), and load().
bool checkpoint::crossoverDone
Definition at line 34 of file checkpoint.h.
Referenced by checkpoint(), dump(), load(), and performCrossover().
std::string checkpoint::dir
Name of the checkpoint directory containing the information to reinitialize the system (json)
Definition at line 42 of file checkpoint.h.
Referenced by checkpoint(), dump(), and load().
std::vector< double > checkpoint::elb
Definition at line 45 of file checkpoint.h.
Referenced by dump(), and load().
std::vector< double > checkpoint::eub
Upper and lower energy bounds for energy histogram.
Definition at line 45 of file checkpoint.h.
Referenced by dump(), and load().
long int checkpoint::freq
Frequency (in seconds) that the system should print a new instantaneous snapshot of itself, does not load from checkpoints but is assigned when instantiated (is dumped though)
Definition at line 37 of file checkpoint.h.
Referenced by check(), checkpoint(), and dump().
bool checkpoint::hasCheckpoint
At least one checkpoint has been made that the system can restart from.
Definition at line 32 of file checkpoint.h.
Referenced by checkpoint(), dump(), and load().
long long int checkpoint::moveCounter
Tracks the number of moves in a given sweep that have executed.
Definition at line 38 of file checkpoint.h.
Referenced by checkpoint(), load(), performCrossover(), performTMMC(), and performWALA().
bool checkpoint::resFromCross
Definition at line 35 of file checkpoint.h.
Referenced by checkpoint(), load(), and performCrossover().
bool checkpoint::resFromTMMC
Flags corresponding to which stage the checkpoint indicated to restart from.
Definition at line 35 of file checkpoint.h.
Referenced by checkpoint(), load(), and performTMMC().
bool checkpoint::resFromWALA
Definition at line 35 of file checkpoint.h.
Referenced by checkpoint(), load(), and performWALA().
long long int checkpoint::sweepCounter
Tracks the number of sweeps that have executed.
Definition at line 39 of file checkpoint.h.
Referenced by checkpoint(), load(), performCrossover(), and performTMMC().
bool checkpoint::takeSnaps
Save snapshot of the system each time a record is made.
Definition at line 33 of file checkpoint.h.
Referenced by checkpoint(), dump(), and load().
bool checkpoint::tmmcDone
Definition at line 34 of file checkpoint.h.
Referenced by checkpoint(), dump(), load(), and performTMMC().
double checkpoint::wala_lnF
Current value of lnF from WALA.
Definition at line 40 of file checkpoint.h.
Referenced by load().
bool checkpoint::walaDone
Progress of each stage, regardless of where the checkpoint indicated to start from.
Definition at line 34 of file checkpoint.h.
Referenced by checkpoint(), dump(), load(), and performWALA().
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.