compositeBarrier
NAME
compositeBarrier -
Class which tracks all barriers (superimposed) which interact with a given species.
SYNOPSIS
#include <barrier.h>
Public Member Functions
compositeBarrier ()
~compositeBarrier ()
Deallocate any system barriers present.
void clearAll ()
Clear any barriers that are currently in the class.
void addHardWallZ (const double lb, const double ub, const double sigma, const int M=1)
Add a hard wall to interact with.
void addSquareWellWallZ (const double lb, const double ub, const double sigma, const double range, const double eps, const int M=1)
Add a square well wall to interact with.
void addCylinderZ (const double x, const double y, const double radius, const double width, const double sigma, const double eps, const int M=1)
Add a cylinder along z = 0 axis wall to interact with.
void addRightTriangleXZ (const double width, const double theta, const double lamW, const double eps, const double sigma, const double sep, const double offset, const std::vector< double > &box, const double zbase, bool top=false, const int M=1)
Add a rightTriangleZ feature to interact with.
bool inside (const atom *a1, const std::vector< double > &box)
Test if inside ALL the barriers.
double energy (const atom *a1, const std::vector< double > &box)
Find the total energy of interaction from ALL the barriers.
Detailed Description
Class which tracks all barriers (superimposed) which interact with a given species.
Definition at line 111 of file barrier.h.
Constructor & Destructor Documentation
compositeBarrier::compositeBarrier () [inline]
Definition at line 113 of file barrier.h.
{};
compositeBarrier::~compositeBarrier ()
Deallocate any system barriers present.
Definition at line 789 of file barrier.cpp.
                                     {
    if (sysBarriers_.begin() != sysBarriers_.end()) {
        for (unsigned int i = 0; i < sysBarriers_.size(); ++i) {
            delete sysBarriers_[i];
        }
        sysBarriers_.clear();
    }
}
Member Function Documentation
void compositeBarrier::addCylinderZ (const doublex, const doubley, const doubleradius, const doublewidth, const doublesigma, const doubleeps, const intM = 1)
Add a cylinder along z = 0 axis wall to interact with.
Parameters:
x x-coordinate of cylinder's center
y y-coordinate of cylinder's center
radius Radius of cylinder
width Width of square-well-like interaction (distance from wall)
sigma Hard-sphere diameter the species this wall interacts with can approach within
eps Magnitude of the wall interaction (U = -eps)
M Total number of expanded ensemble states possible for this atom type (defaults to 1)
Definition at line 727 of file barrier.cpp.
References customException::what().
                                                                                                                                                               {
    if (sysBarriers_.begin() == sysBarriers_.end()) {
        try {
            sysBarriers_.resize(1);
        } catch (std::bad_alloc &ba) {
            throw customException ("Unable to allocate space for a new barrier");
        }
    } else {
        try {
            sysBarriers_.resize(sysBarriers_.size()+1);
        } catch (std::bad_alloc &ba) {
            throw customException ("Unable to allocate space for a new barrier");
        }
    }
    try {
        sysBarriers_[sysBarriers_.size()-1] = new cylinderZ (x, y, radius, width, sigma, eps, M);
    } catch (customException &ce) {
        const std::string msg = ce.what();
        throw customException ("Cannot add cylinderZ to composite barrier : "+msg);
    }
}
void compositeBarrier::addHardWallZ (const doublelb, const doubleub, const doublesigma, const intM = 1)
Add a hard wall to interact with.
Parameters:
lb z-Position of the lower wall
ub z-Position of the upper wall
sigma Hard-sphere diameter the species this wall interacts with can approach within
M Total number of expanded ensemble states possible for this atom type (defaults to 1)
Definition at line 662 of file barrier.cpp.
References customException::what().
                                                                                                      {
    if (sysBarriers_.begin() == sysBarriers_.end()) {
        try {
            sysBarriers_.resize(1);
        } catch (std::bad_alloc &ba) {
            throw customException ("Unable to allocate space for a new barrier");
        }
    } else {
        try {
            sysBarriers_.resize(sysBarriers_.size()+1);
        } catch (std::bad_alloc &ba) {
            throw customException ("Unable to allocate space for a new barrier");
        }
    }
    try {
        sysBarriers_[sysBarriers_.size()-1] = new hardWallZ (lb, ub, sigma, M);
    } catch (customException &ce) {
        const std::string msg = ce.what();
        throw customException ("Cannot add hardWallZ to composite barrier : "+msg);
    }
}
void compositeBarrier::addRightTriangleXZ (const doublewidth, const doubletheta, const doublelamW, const doubleeps, const doublesigma, const doublesep, const doubleoffset, const std::vector< double > &box, const doublezbase, booltop = false, const intM = 1)
Add a rightTriangleZ feature to interact with.
Parameters:
width Width of triangle's feature
theta Elevation angle of the feature in radians (0, PI)
lamW Attractive range ratio relative to hard sphere in contact with the feature (akin to square well), must be >= 1
eps Attraction strength to feature
sigma Hard sphere diameter of interaction with the feature
sep Distance between features
offset Offset from x = 0 position of the first feature
box System box size to check the feature (as specified) is periodic in the box
zbase Z-coordinate of XY plane that defines the base of the feature. To avoid periodicity effects be sure it is > 0 and less than Lz, but this depends on other interactions so it cannot be checked automatically here.
top If true, feature is on the 'top', else is on the bottom (default)
Number of expanded ensemble states to recognize (default = 1)
Definition at line 764 of file barrier.cpp.
References customException::what().
                                                                                                                                                                                                                                                             {
    if (sysBarriers_.begin() == sysBarriers_.end()) {
        try {
            sysBarriers_.resize(1);
        } catch (std::bad_alloc &ba) {
            throw customException ("Unable to allocate space for a new barrier");
        }
    } else {
        try {
            sysBarriers_.resize(sysBarriers_.size()+1);
        } catch (std::bad_alloc &ba) {
            throw customException ("Unable to allocate space for a new barrier");
        }
    }
    try {
        sysBarriers_[sysBarriers_.size()-1] = new rightTriangleXZ (width, theta, lamW, eps, sigma, sep, offset, box, zbase, top, M);
    } catch (customException &ce) {
        const std::string msg = ce.what();
        throw customException ("Cannot add rightTriangleXZ to composite barrier : "+msg);
    }
}
void compositeBarrier::addSquareWellWallZ (const doublelb, const doubleub, const doublesigma, const doublerange, const doubleeps, const intM = 1)
Add a square well wall to interact with.
Parameters:
lb z-Position of the lower wall
ub z-Position of the upper wall
sigma Hard-sphere diameter the species this wall interacts with can approach within
range Distance normal to the wall's surface where there is an interaction
eps Magnitude of the wall interaction (U = -eps)
M Total number of expanded ensemble states possible for this atom type (defaults to 1)
Definition at line 694 of file barrier.cpp.
References customException::what().
                                                                                                                                                  {
    if (sysBarriers_.begin() == sysBarriers_.end()) {
        try {
            sysBarriers_.resize(1);
        } catch (std::bad_alloc &ba) {
            throw customException ("Unable to allocate space for a new barrier");
        }
    } else {
        try {
            sysBarriers_.resize(sysBarriers_.size()+1);
        } catch (std::bad_alloc &ba) {
            throw customException ("Unable to allocate space for a new barrier");
        }
    }
    try {
        sysBarriers_[sysBarriers_.size()-1] = new squareWellWallZ (lb, ub, sigma, range, eps, M);
    } catch (customException &ce) {
        const std::string msg = ce.what();
        throw customException ("Cannot add squareWellWallZ to composite barrier : "+msg);
    }
}
void compositeBarrier::clearAll () [inline]
Clear any barriers that are currently in the class.
Definition at line 116 of file barrier.h.
double compositeBarrier::energy (const atom *a1, const std::vector< double > &box)
Find the total energy of interaction from ALL the barriers.
Parameters:
a1 Pointer to atom with position to test - this does NOT need to be in the simulation box a priori
box Simulation box
Definition at line 819 of file barrier.cpp.
References NUM_INFINITY.
                                                                                {
    double U = 0.0;
    for (std::vector < barrier* >::iterator it = sysBarriers_.begin(); it != sysBarriers_.end(); ++it) {
        double dU = (*it)->energy (a1, box);
        if (dU < NUM_INFINITY) {
            U += dU;
        } else {
            return NUM_INFINITY;
        }
    }
    return U;
}
bool compositeBarrier::inside (const atom *a1, const std::vector< double > &box)
Test if inside ALL the barriers. Returns false if outside any single one, but defaults to true (infinitely far away walls/barriers).
Parameters:
a1 Pointer to atom with position to test - this does NOT need to be in the simulation box a priori
box Simulation box
Definition at line 804 of file barrier.cpp.
                                                                              {
    for (std::vector < barrier* >::iterator it = sysBarriers_.begin(); it != sysBarriers_.end(); ++it) {
        if (!(*it)->inside (a1, box)) {
            return false;
        }
    }
    return true;
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.