.TH "compositeBarrier" 3 "Wed Jan 4 2017" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compositeBarrier \- 
.PP
Class which tracks all barriers (superimposed) which interact with a given species\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <barrier\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcompositeBarrier\fP ()"
.br
.ti -1c
.RI "\fB~compositeBarrier\fP ()"
.br
.RI "\fIFree any system barriers present\&. \fP"
.ti -1c
.RI "void \fBclearAll\fP ()"
.br
.RI "\fIClear any barriers that are currently in the class\&. \fP"
.ti -1c
.RI "void \fBaddHardWallZ\fP (const double lb, const double ub, const double sigma, const int M=1)"
.br
.RI "\fIAdd a hard wall to interact with\&. \fP"
.ti -1c
.RI "void \fBaddSquareWellWallZ\fP (const double lb, const double ub, const double sigma, const double range, const double eps, const int M=1)"
.br
.RI "\fIAdd a square well wall to interact with\&. \fP"
.ti -1c
.RI "void \fBaddCylinderZ\fP (const double x, const double y, const double radius, const double width, const double sigma, const double eps, const int M=1)"
.br
.RI "\fIAdd a cylinder along z = 0 axis wall to interact with\&. \fP"
.ti -1c
.RI "void \fBaddRightTriangleXZ\fP (const double width, const double theta, const double lamW, const double eps, const double sigma, const double sep, const double offset, const std::vector< double > &box, const double zbase, bool top=false, const int M=1)"
.br
.RI "\fIAdd a rightTriangleZ feature to interact with\&. \fP"
.ti -1c
.RI "bool \fBinside\fP (const \fBatom\fP *a1, const std::vector< double > &box)"
.br
.RI "\fITest if inside ALL the barriers\&. \fP"
.ti -1c
.RI "double \fBenergy\fP (const \fBatom\fP *a1, const std::vector< double > &box)"
.br
.RI "\fIFind the total energy of interaction from ALL the barriers\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class which tracks all barriers (superimposed) which interact with a given species\&. 
.PP
Definition at line 112 of file barrier\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "compositeBarrier::compositeBarrier ()\fC [inline]\fP"

.PP
Definition at line 114 of file barrier\&.h\&.
.PP
References clearAll()\&.
.PP
.nf
114 { clearAll(); }
.fi
.SS "compositeBarrier::~compositeBarrier ()"

.PP
Free any system barriers present\&. 
.PP
Definition at line 740 of file barrier\&.cpp\&.
.PP
.nf
740                                      {
741     sysBarriers_\&.clear();
742 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void compositeBarrier::addCylinderZ (const doublex, const doubley, const doubleradius, const doublewidth, const doublesigma, const doubleeps, const intM = \fC1\fP)"

.PP
Add a cylinder along z = 0 axis wall to interact with\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP x-coordinate of cylinder's center 
.br
\fIy\fP y-coordinate of cylinder's center 
.br
\fIradius\fP Radius of cylinder 
.br
\fIwidth\fP Width of square-well-like interaction (distance from wall) 
.br
\fIsigma\fP Hard-sphere diameter the species this wall interacts with can approach within 
.br
\fIeps\fP Magnitude of the wall interaction (U = -eps) 
.br
\fIM\fP Total number of expanded ensemble states possible for this atom type (defaults to 1) 
.RE
.PP

.PP
Definition at line 702 of file barrier\&.cpp\&.
.PP
.nf
702                                                                                                                                                                {
703     try {
704         auto barr = std::make_shared < cylinderZ > (x, y, radius, width, sigma, eps, M);
705         sysBarriers_\&.push_back(barr);
706     } catch (std::exception &ex) {
707         const std::string msg = ex\&.what();
708         throw customException ("Cannot add cylinderZ to composite barrier : "+msg);
709     }
710 }
.fi
.SS "void compositeBarrier::addHardWallZ (const doublelb, const doubleub, const doublesigma, const intM = \fC1\fP)"

.PP
Add a hard wall to interact with\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlb\fP z-Position of the lower wall 
.br
\fIub\fP z-Position of the upper wall 
.br
\fIsigma\fP Hard-sphere diameter the species this wall interacts with can approach within 
.br
\fIM\fP Total number of expanded ensemble states possible for this atom type (defaults to 1) 
.RE
.PP

.PP
Definition at line 661 of file barrier\&.cpp\&.
.PP
.nf
661                                                                                                       {
662     try {
663         auto barr = std::make_shared < hardWallZ > (lb, ub, sigma, M);
664         sysBarriers_\&.push_back(barr);
665     } catch (std::exception &ex) {
666         const std::string msg = ex\&.what();
667         throw customException ("Cannot add hardWallZ to composite barrier : "+msg);
668     }
669 }
.fi
.SS "void compositeBarrier::addRightTriangleXZ (const doublewidth, const doubletheta, const doublelamW, const doubleeps, const doublesigma, const doublesep, const doubleoffset, const std::vector< double > &box, const doublezbase, booltop = \fCfalse\fP, const intM = \fC1\fP)"

.PP
Add a rightTriangleZ feature to interact with\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwidth\fP Width of triangle's feature 
.br
\fItheta\fP Elevation angle of the feature in radians (0, PI) 
.br
\fIlamW\fP Attractive range ratio relative to hard sphere in contact with the feature (akin to square well), must be >= 1 
.br
\fIeps\fP Attraction strength to feature 
.br
\fIsigma\fP Hard sphere diameter of interaction with the feature 
.br
\fIsep\fP Distance between features 
.br
\fIoffset\fP Offset from x = 0 position of the first feature 
.br
\fIbox\fP System box size to check the feature (as specified) is periodic in the box 
.br
\fIzbase\fP Z-coordinate of XY plane that defines the base of the feature\&. To avoid periodicity effects be sure it is > 0 and less than Lz, but this depends on other interactions so it cannot be checked automatically here\&. 
.br
\fItop\fP If true, feature is on the 'top', else is on the bottom (default) 
.br
\fINumber\fP of expanded ensemble states to recognize (default = 1) 
.RE
.PP

.PP
Definition at line 727 of file barrier\&.cpp\&.
.PP
.nf
727                                                                                                                                                                                                                                                              {
728     try {
729         auto barr = std::make_shared < rightTriangleXZ > (width, theta, lamW, eps, sigma, sep, offset, box, zbase, top, M);
730         sysBarriers_\&.push_back(barr);
731     } catch (std::exception &ex) {
732         const std::string msg = ex\&.what();
733         throw customException ("Cannot add rightTriangleXZ to composite barrier : "+msg);
734     }
735 }
.fi
.SS "void compositeBarrier::addSquareWellWallZ (const doublelb, const doubleub, const doublesigma, const doublerange, const doubleeps, const intM = \fC1\fP)"

.PP
Add a square well wall to interact with\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlb\fP z-Position of the lower wall 
.br
\fIub\fP z-Position of the upper wall 
.br
\fIsigma\fP Hard-sphere diameter the species this wall interacts with can approach within 
.br
\fIrange\fP Distance normal to the wall's surface where there is an interaction 
.br
\fIeps\fP Magnitude of the wall interaction (U = -eps) 
.br
\fIM\fP Total number of expanded ensemble states possible for this atom type (defaults to 1) 
.RE
.PP

.PP
Definition at line 681 of file barrier\&.cpp\&.
.PP
.nf
681                                                                                                                                                   {
682     try {
683         auto barr = std::make_shared < squareWellWallZ > (lb, ub, sigma, range, eps, M);
684         sysBarriers_\&.push_back(barr);
685     } catch (std::exception &ex) {
686         const std::string msg = ex\&.what();
687         throw customException ("Cannot add squareWellWallZ to composite barrier : "+msg);
688     }
689 }
.fi
.SS "void compositeBarrier::clearAll ()\fC [inline]\fP"

.PP
Clear any barriers that are currently in the class\&. 
.PP
Definition at line 117 of file barrier\&.h\&.
.PP
Referenced by compositeBarrier()\&.
.SS "double compositeBarrier::energy (const \fBatom\fP *a1, const std::vector< double > &box)"

.PP
Find the total energy of interaction from ALL the barriers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa1\fP Pointer to atom with position to test - this does NOT need to be in the simulation box a priori 
.br
\fIbox\fP Simulation box 
.RE
.PP

.PP
Definition at line 765 of file barrier\&.cpp\&.
.PP
References NUM_INFINITY\&.
.PP
.nf
765                                                                                 {
766     double U = 0\&.0;
767     for (std::vector < std::shared_ptr < barrier > >::iterator it = sysBarriers_\&.begin(); it != sysBarriers_\&.end(); ++it) {
768         double dU = (*it)->energy (a1, box);
769         if (dU < NUM_INFINITY) {
770             U += dU;
771         } else {
772             return NUM_INFINITY;
773         }
774     }
775     return U;
776 }
.fi
.SS "bool compositeBarrier::inside (const \fBatom\fP *a1, const std::vector< double > &box)"

.PP
Test if inside ALL the barriers\&. Returns false if outside any single one, but defaults to true (infinitely far away walls/barriers)\&.
.PP
\fBParameters:\fP
.RS 4
\fIa1\fP Pointer to atom with position to test - this does NOT need to be in the simulation box a priori 
.br
\fIbox\fP Simulation box 
.RE
.PP

.PP
Definition at line 750 of file barrier\&.cpp\&.
.PP
.nf
750                                                                               {
751     for (std::vector < std::shared_ptr < barrier > >::iterator it = sysBarriers_\&.begin(); it != sysBarriers_\&.end(); ++it) {
752         if (!(*it)->inside (a1, box)) {
753             return false;
754         }
755     }
756     return true;
757 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
