.TH "/home/nam4/Desktop/sandbox/FHMCSimulation/src/crossover.h" 3 "Thu Dec 29 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/crossover.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'checkpoint\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'mover\&.h'\fP
.br
\fC#include 'sanity\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBperformCrossover\fP (\fBsimSystem\fP &sys, \fBcheckpoint\fP &res, \fBmoves\fP *usedMovesEq)"
.br
.RI "\fIPerform crossover from Wang-Landau stage of simulation to TMMC\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void performCrossover (\fBsimSystem\fP &sys, \fBcheckpoint\fP &res, \fBmoves\fP *usedMovesEq)"

.PP
Perform crossover from Wang-Landau stage of simulation to TMMC\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsys\fP System to simulate 
.br
\fIres\fP Restart/checkpoint information 
.br
\fIusedMovesEq\fP Move class to use 
.RE
.PP

.PP
Definition at line 10 of file crossover\&.cpp\&.
.PP
References tmmc::calculatePI(), checkpoint::check(), simSystem::checkEnergyHistogramBounds(), tmmc::checkFullyVisited(), checkpoint::crossoverDone, tmmc::dumpVisited(), wala::evaluateFlatness(), simSystem::getCurrentM(), simSystem::getTMMCBias(), simSystem::getTotalM(), simSystem::getWALABias(), tmmc::iterateForward(), wala::iterateForward(), wala::lnF(), moves::makeMove(), checkpoint::moveCounter, simSystem::nCrossoverVisits, tmmc::numSweeps(), numToStr(), moves::print(), tmmc::print(), simSystem::reInitializeEnergyHistogram(), checkpoint::resFromCross, sanityChecks(), sendErr(), sendMsg(), simSystem::startTMMC(), simSystem::stopWALA(), checkpoint::sweepCounter, SYS_FAILURE, simSystem::tmmcSweepSize, simSystem::useWALA, customException::what(), and simSystem::wlSweepSize\&.
.PP
.nf
10                                                                             {
11     if (res\&.crossoverDone) {
12         throw customException ("Checkpoint indicates crossover already finished");
13     }
14     sendMsg("Crossing over to build TMMC matrix");
15 
16     res\&.crossoverDone = false;
17     long long int timesFullyVisited = 0, moveStart = 0;
18     if (!res\&.resFromCross) {
19         if (!sys\&.useWALA) {
20             throw customException ("WALA not configured, cannot proceeed with crossover");
21         }
22         sys\&.startTMMC (sys\&.tmmcSweepSize, sys\&.getTotalM());
23     } else {
24         timesFullyVisited = res\&.sweepCounter;
25         moveStart = res\&.moveCounter;
26     }
27 
28     sendMsg("Starting from lnF = "+numToStr(sys\&.getWALABias()->lnF()));
29     sendMsg("Starting from "+numToStr(moveStart)+" moves in current sweep");
30     sendMsg("Starting from "+numToStr(timesFullyVisited)+" out of "+numToStr(sys\&.nCrossoverVisits)+" sweeps");
31 
32     while (timesFullyVisited < sys\&.nCrossoverVisits) {
33         for (long long int move = moveStart; move < sys\&.wlSweepSize; ++move) {
34             try {
35                 usedMovesEq->makeMove(sys);
36             } catch (customException &ce) {
37                 sendErr(ce\&.what());
38                 exit(SYS_FAILURE);
39             }
40             if (sys\&.getCurrentM() == 0) {
41                 sys\&.checkEnergyHistogramBounds ();
42             }
43             res\&.check(sys, move, timesFullyVisited);
44         }
45 
46         if (sys\&.getTMMCBias()->checkFullyVisited()) {
47             try {
48                 sys\&.getTMMCBias()->calculatePI();
49             } catch (customException &ce) {
50                 sendErr(ce\&.what());
51                 sys\&.getTMMCBias()->print("tmmc-crossover-fail", true);
52                 sys\&.getTMMCBias()->dumpVisited("tmmc-crossover-fail-visited");
53                 exit(SYS_FAILURE);
54             }
55             sys\&.getTMMCBias()->iterateForward (); // Reset the counting matrix and increment total sweep number
56             timesFullyVisited = sys\&.getTMMCBias()->numSweeps();
57             sendMsg("Times C fully visited = "+numToStr(timesFullyVisited));
58             usedMovesEq->print("crossover\&.stats");
59         }
60 
61         // Check if bias has flattened out, just for continuous improvement
62         bool flat = sys\&.getWALABias()->evaluateFlatness();
63         if (flat) {
64             sys\&.getWALABias()->iterateForward(); // If flat, need to reset H and reduce lnF
65             sendMsg("Wang-Landau is now flat, new lnF = "+numToStr(sys\&.getWALABias()->lnF()));
66         }
67     }
68 
69     // Switch over to TMMC completely
70     sendMsg("Switching over to TMMC completely, ending Wang-Landau");
71     sys\&.stopWALA();
72     try {
73         sys\&.getTMMCBias()->calculatePI();
74     } catch (customException &ce) {
75         sendErr(ce\&.what());
76         sys\&.getTMMCBias()->print("tmmc-beginning-fail", true);
77         sys\&.getTMMCBias()->dumpVisited("tmmc-beginning-fail-visited");
78         exit(SYS_FAILURE);
79     }
80 
81     sys\&.reInitializeEnergyHistogram(); // If doing initial WL "equilibration" re-initialize the histogram using bounds
82     sanityChecks(sys);
83     res\&.crossoverDone = true;
84 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
