/home/nam4/Desktop/sandbox/FHMCSimulation/src/crossover.h
NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/crossover.h -
SYNOPSIS
#include <string>
#include <memory>
#include 'system.h'
#include 'checkpoint.h'
#include 'utilities.h'
#include 'mover.h'
#include 'sanity.h'
Functions
void performCrossover (simSystem &sys, checkpoint &res, moves *usedMovesEq)
Perform crossover from Wang-Landau stage of simulation to TMMC.
Function Documentation
void performCrossover (simSystem &sys, checkpoint &res, moves *usedMovesEq)
Perform crossover from Wang-Landau stage of simulation to TMMC.
Parameters:
sys System to simulate
res Restart/checkpoint information
usedMovesEq Move class to use
Definition at line 10 of file crossover.cpp.
References tmmc::calculatePI(), checkpoint::check(), simSystem::checkEnergyHistogramBounds(), tmmc::checkFullyVisited(), checkpoint::crossoverDone, simSystem::crossoverTotalStepCounter, tmmc::dumpVisited(), wala::evaluateFlatness(), simSystem::getCurrentM(), simSystem::getTMMCBias(), simSystem::getTotalM(), simSystem::getWALABias(), tmmc::iterateForward(), wala::iterateForward(), wala::lnF(), moves::makeMove(), checkpoint::moveCounter, simSystem::nCrossoverVisits, tmmc::numSweeps(), numToStr(), moves::print(), tmmc::print(), simSystem::reInitializeEnergyHistogram(), checkpoint::resFromCross, sanityChecks(), sendErr(), sendMsg(), simSystem::startTMMC(), simSystem::stopWALA(), checkpoint::sweepCounter, SYS_FAILURE, simSystem::tmmcSweepSize, simSystem::useWALA, simSystem::walaTotalStepCounter, customException::what(), and simSystem::wlSweepSize.
                                                                            {
    if (res.crossoverDone) {
        throw customException ("Checkpoint indicates crossover already finished");
    }
    sendMsg("Crossing over to build TMMC matrix");
    res.crossoverDone = false;
    long long int timesFullyVisited = 0, moveStart = 0;
    if (!res.resFromCross) {
        if (!sys.useWALA) {
            throw customException ("WALA not configured, cannot proceeed with crossover");
        }
        sys.startTMMC (sys.tmmcSweepSize, sys.getTotalM());
    } else {
        timesFullyVisited = res.sweepCounter;
        moveStart = res.moveCounter;
    }
    sendMsg("Starting from lnF = "+numToStr(sys.getWALABias()->lnF()));
    sendMsg("Starting from "+numToStr(moveStart)+" moves in current sweep");
    sendMsg("Starting from "+numToStr(timesFullyVisited)+" out of "+numToStr(sys.nCrossoverVisits)+" sweeps");
    while (timesFullyVisited < sys.nCrossoverVisits) {
        for (long long int move = moveStart; move < sys.wlSweepSize; ++move) {
            try {
                usedMovesEq->makeMove(sys);
                sys.crossoverTotalStepCounter += 1.0;
            } catch (customException &ce) {
                sendErr(ce.what());
                exit(SYS_FAILURE);
            }
            if (sys.getCurrentM() == 0) {
                sys.checkEnergyHistogramBounds ();
            }
            res.check(sys, move, timesFullyVisited, false);
        }
        if (sys.getTMMCBias()->checkFullyVisited()) {
            try {
                sys.getTMMCBias()->calculatePI();
            } catch (customException &ce) {
                sendErr(ce.what());
                sys.getTMMCBias()->print("tmmc-crossover-fail", true);
                sys.getTMMCBias()->dumpVisited("tmmc-crossover-fail-visited");
                exit(SYS_FAILURE);
            }
            sys.getTMMCBias()->iterateForward (); // Reset the counting matrix and increment total sweep number
            timesFullyVisited = sys.getTMMCBias()->numSweeps();
            sendMsg("Times C fully visited = "+numToStr(timesFullyVisited));
            usedMovesEq->print("crossover.stats");
        }
        // Check if bias has flattened out, just for continuous improvement
        bool flat = sys.getWALABias()->evaluateFlatness();
        if (flat) {
            sys.getWALABias()->iterateForward(); // If flat, need to reset H and reduce lnF
            sendMsg("Wang-Landau is now flat, new lnF = "+numToStr(sys.getWALABias()->lnF()));
        }
    }
    // Switch over to TMMC completely
    sendMsg("Switching over to TMMC completely, ending Wang-Landau");
    sys.stopWALA();
    try {
        sys.getTMMCBias()->calculatePI();
    } catch (customException &ce) {
        sendErr(ce.what());
        sys.getTMMCBias()->print("tmmc-beginning-fail", true);
        sys.getTMMCBias()->dumpVisited("tmmc-beginning-fail-visited");
        exit(SYS_FAILURE);
    }
    sys.reInitializeEnergyHistogram(); // If doing initial WL "equilibration" re-initialize the histogram using bounds
    sanityChecks(sys);
    res.crossoverDone = true; // Do not need to dump a checkpoint
    sendMsg("Completed "+numToStr(sys.crossoverTotalStepCounter)+" total MC steps as part of crossover stage");
    sendMsg("Total MC steps taken in simulation: "+numToStr(sys.walaTotalStepCounter+sys.crossoverTotalStepCounter));
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.