.TH "cylinderZ" 3 "Fri Dec 30 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cylinderZ \- 
.PP
Cylinder along z = 0 axis at a given (x,y) coordinate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <barrier\&.h>\fP
.PP
Inherits \fBbarrier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~cylinderZ\fP ()"
.br
.ti -1c
.RI "\fBcylinderZ\fP (const double x, const double y, const double radius, const double width, const double sigma, const double eps, const int M=1)"
.br
.RI "\fIInstantiate a cylinderical pore in the z-direction\&. \fP"
.ti -1c
.RI "bool \fBinside\fP (const \fBatom\fP *a1, const std::vector< double > &box)"
.br
.RI "\fIReturn whether or not a point falls inside the cylinder (subject to a hard-sphere exclusion radius)\&. \fP"
.ti -1c
.RI "double \fBenergy\fP (const \fBatom\fP *a1, const std::vector< double > &box)"
.br
.RI "\fIInteraction energy with the cylinder\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Cylinder along z = 0 axis at a given (x,y) coordinate\&. 
.PP
Definition at line 64 of file barrier\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cylinderZ::~cylinderZ ()\fC [inline]\fP"

.PP
Definition at line 66 of file barrier\&.h\&.
.PP
.nf
66 {};
.fi
.SS "cylinderZ::cylinderZ (const doublex, const doubley, const doubleradius, const doublewidth, const doublesigma, const doubleeps, const intM = \fC1\fP)"

.PP
Instantiate a cylinderical pore in the z-direction\&. Expanded ensembles primarily scale the magnitude of interaction\&. The repulsive boundary scales with sigma at the boundary, but the attractive cutoff remains fixed relative to the boundary\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP x-coordinate of cylinder's center 
.br
\fIy\fP y-coordinate of cylinder's center 
.br
\fIradius\fP Radius of cylinder 
.br
\fIwidth\fP Width of square-well-like interaction (distance from wall) 
.br
\fIsigma\fP Hard-sphere diameter the species this wall interacts with can approach within 
.br
\fIeps\fP Magnitude of the wall interaction (U = -eps) 
.br
\fIM\fP Total number of expanded ensemble states possible for this atom type (defaults to 1) 
.RE
.PP

.PP
Definition at line 463 of file barrier\&.cpp\&.
.PP
References barrier::M_\&.
.PP
.nf
463                                                                                                                                                 {
464     if (radius <= sigma) {
465         throw customException ("cylinderZ radius <= sigma so practically no particles will fit");
466     }
467     if (sigma < 0) {
468         throw customException ("cylinderZ must have sigma >= 0");
469     }
470     if (width < 0) {
471         throw customException ("cylinderZ must have width >= 0");
472     }
473     if (eps < 0) {
474         throw customException ("cylinderZ must have epsilon >= 0");
475     }
476     if (sigma/2\&.0 >= width) {
477         throw customException ("cylinderZ must have sigma/2 < width to have a finite range of interaction");
478     }
479     if (M < 1) {
480         throw customException ("cylinderZ must have M >= 1");
481     }
482 
483     eps_ = eps;
484     sigma_ = sigma;
485     width_ = width;
486     radius_ = radius;
487     M_ = M;
488 
489     center_\&.resize(3, 0);
490     center_[0] = x;
491     center_[1] = y;
492 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "double cylinderZ::energy (const \fBatom\fP *a1, const std::vector< double > &box)\fC [virtual]\fP"

.PP
Interaction energy with the cylinder\&. Sigma and epsilon are scaled linearly with expanded ensemble state\&.
.PP
\fBParameters:\fP
.RS 4
\fIa1\fP Pointer to atom with position to test - this does NOT need to be in the simulation box a priori 
.br
\fIbox\fP Simulation box 
.RE
.PP

.PP
Implements \fBbarrier\fP\&.
.PP
Definition at line 526 of file barrier\&.cpp\&.
.PP
References barrier::M_, atom::mState, NUM_INFINITY, pbcDist2(), and atom::pos\&.
.PP
.nf
526                                                                          {
527     center_[2] = a1->pos[2]; // same z-plane
528     double rv2 = pbcDist2 (a1->pos, center_, box);
529     double U = 0\&.0, sig = sigma_, eps = eps_;
530 
531     if (a1->mState > 0) {
532         sig = (sigma_/M_)*a1->mState;
533         eps = (eps_/M_)*a1->mState;
534     }
535     if (a1->mState < 0 || a1->mState > M_-1) {
536         throw customException ("mState out of bounds for cylinderZ");
537     }
538 
539     // Return infinity if out of bounds
540     double rc = radius_ - sig/2\&.0, ri = radius_ - width_;
541     if (rv2 >= rc*rc) {
542         return NUM_INFINITY;
543     }
544 
545     // Interaction with the wall - return infinity if it was out of bounds already
546     if (rv2 > ri*ri) {
547         U += -eps;
548     }
549 
550     return U;
551 }
.fi
.SS "bool cylinderZ::inside (const \fBatom\fP *a1, const std::vector< double > &box)\fC [virtual]\fP"

.PP
Return whether or not a point falls inside the cylinder (subject to a hard-sphere exclusion radius)\&. Sigma is scaled linearly with expanded ensemble state\&.
.PP
\fBParameters:\fP
.RS 4
\fIa1\fP Pointer to atom with position to test - this does NOT need to be in the simulation box a priori 
.br
\fIbox\fP Simulation box 
.RE
.PP

.PP
Implements \fBbarrier\fP\&.
.PP
Definition at line 500 of file barrier\&.cpp\&.
.PP
References barrier::M_, atom::mState, pbcDist2(), and atom::pos\&.
.PP
.nf
500                                                                        {
501     center_[2] = a1->pos[2]; // same z-plane
502     double rv2 = pbcDist2 (a1->pos, center_, box);
503 
504     double sig = sigma_;
505     if (a1->mState > 0) {
506         sig = (sigma_/M_)*a1->mState;
507     }
508     if (a1->mState < 0 || a1->mState > M_-1) {
509         throw customException ("mState out of bounds for cylinderZ");
510     }
511 
512     double rc = radius_ - sig/2\&.0;
513     if (rv2 >= rc*rc) {
514         return false;
515     } else {
516         return true;
517     }
518 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
