dynamic_one_dim_histogram
NAME
dynamic_one_dim_histogram -
SYNOPSIS
#include <histogram.h>
Public Member Functions
~dynamic_one_dim_histogram ()
dynamic_one_dim_histogram ()
dynamic_one_dim_histogram (const double lb, const double ub, const double delta)
Instantiate a 1D histogram that grow as needed to record values.
void reinitialize (const double lb, const double ub, const double delta)
Re-initialize histogram and its bounds.
void trim_edges ()
Trim the size of the histogram to remove leading and trailing zeros.
void prepend_bins (const unsigned int nbins)
Add a number of bins to the beginning of the histogram.
void append_bins (const unsigned int nbins)
Add a number of bins to the end of the histogram.
void record (const double value)
Record an entry in the histogram at the bin corresponding to where value falls.
void set_hist (const std::deque< double > h)
Set the histogram.
const double get_delta ()
const double get_lb ()
const double get_ub ()
std::deque< double > get_hist ()
Detailed Description
Definition at line 41 of file histogram.h.
Constructor & Destructor Documentation
dynamic_one_dim_histogram::~dynamic_one_dim_histogram () [inline]
Definition at line 43 of file histogram.h.
{;}
dynamic_one_dim_histogram::dynamic_one_dim_histogram () [inline]
Definition at line 44 of file histogram.h.
{;}
dynamic_one_dim_histogram::dynamic_one_dim_histogram (const doublelb, const doubleub, const doubledelta)
Instantiate a 1D histogram that grow as needed to record values. Aligns against the lower bound, and uses this as the bin's 'center.' The upper bound is internally re-calculated from the lower bound and the value of delta. Bins include values between [lo, hi) where a bin's value = (low+hi)/2.
Parameters:
lb Lowest value that must be covered by histogram. This is used to align the histogram when ub and lb not integer delta's apart.
ub Largest value that must be covered by histogram. Less relevant than lb, which is used for alignment. This value is only used to determined the number of bins necessary.
delta Bin width.
Definition at line 114 of file histogram.cpp.
                                                                                                          {
    try {
        initialize_ (lb, ub, delta);
    } catch (customException &ce) {
        throw customException ("Unable to initialize dynamic_one_dim_histogram");
    }
}
Member Function Documentation
void dynamic_one_dim_histogram::append_bins (const unsigned intnbins)
Add a number of bins to the end of the histogram.
Parameters:
nbins Number of bins to add to the end
Definition at line 144 of file histogram.cpp.
Referenced by record().
                                                                     {
    for (unsigned int i = 0; i < nbins; i++) {
        try {
            h_.push_back (0.0);
            nbins_++;
            ub_ += delta_;
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory for dynamic_one_dim_histogram");
        }
    }
}
const double dynamic_one_dim_histogram::get_delta () [inline]
Definition at line 53 of file histogram.h.
{ return delta_; }
std::deque< double > dynamic_one_dim_histogram::get_hist () [inline]
Definition at line 56 of file histogram.h.
{ return h_; }
const double dynamic_one_dim_histogram::get_lb () [inline]
Definition at line 54 of file histogram.h.
{ return lb_; }
const double dynamic_one_dim_histogram::get_ub () [inline]
Definition at line 55 of file histogram.h.
{ return ub_; }
void dynamic_one_dim_histogram::prepend_bins (const unsigned intnbins)
Add a number of bins to the beginning of the histogram.
Parameters:
nbins Number of bins to add to the beginning
Definition at line 127 of file histogram.cpp.
Referenced by record().
                                                                      {
    for (unsigned int i = 0; i < nbins; i++) {
        try {
            h_.push_front (0.0);
            nbins_++;
            lb_ -= delta_;
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory for dynamic_one_dim_histogram");
        }
    }
}
void dynamic_one_dim_histogram::record (const doublevalue)
Record an entry in the histogram at the bin corresponding to where value falls.
Parameters:
value Raw value, bin this corresponds to is internally calculated
Definition at line 161 of file histogram.cpp.
References append_bins(), prepend_bins(), and customException::what().
                                                          {
    int bin = round((value - lb_)/delta_); // this "centers" the bin
    if (std::abs(bin) < tol_) {
        // prevent -0 case and set to 0
        bin = 0;
    }
    if (bin < 0) {
        // prepend and fill
        try {
            prepend_bins(-bin);
        } catch (customException &ce) {
            std::string a = "Unable to prepend dynamic_one_dim_histogram: ", b = ce.what();
            throw customException (a+b);
        }
    } else if (bin >= nbins_) {
        // append and fill
        try {
            append_bins (bin - nbins_ + 1);
        } catch (customException &ce) {
            std::string a = "Unable to append dynamic_one_dim_histogram: ", b = ce.what();
            throw customException (a+b);
        }
    }
    // re-calculate after lb potentially adjusted
    bin = round((value - lb_)/delta_);
    if (std::abs(bin) < tol_) {
            // prevent -0 case and set to 0
            bin = 0;
    }
    h_[bin] += 1.0;
}
void dynamic_one_dim_histogram::reinitialize (const doublelb, const doubleub, const doubledelta)
Re-initialize histogram and its bounds. All entries are zeroed. Aligns against the lower bound, and uses this as the bin's 'center.' The upper bound is internally re-calculated from the lower bound and the value of delta. Bins include values between [lo, hi) where a bin's value = (low+hi)/2.
Parameters:
lb Lowest value that must be covered by histogram. This is used to align the histogram when ub and lb not integer delta's apart.
ub Largest value that must be covered by histogram. Less relevant than lb, which is used for alignment. This value is only used to determined the number of bins necessary.
delta Bin width.
Definition at line 98 of file histogram.cpp.
                                                                                                  {
    try {
        initialize_ (lb, ub, delta);
    } catch (customException &ce) {
        throw customException ("Unable to re-initialize dynamic_one_dim_histogram");
    }
}
void dynamic_one_dim_histogram::set_hist (const std::deque< double >h)
Set the histogram. Intended to be used to restart from a checkpoint.
Parameters:
h Histogram to set to.
Definition at line 82 of file histogram.cpp.
                                                                     {
    if (h.size() != h_.size()) {
        throw customException ("Histogram using to set is not the same as inherent, aborting");
    } else {
        h_ = (std::deque < double >)h;
    }
}
void dynamic_one_dim_histogram::trim_edges ()
Trim the size of the histogram to remove leading and trailing zeros.
Definition at line 7 of file histogram.cpp.
                                            {
    long unsigned int leading = 0, trailing = 0;
    for (std::deque < double >::iterator it = h_.begin(); it != h_.end(); ++it) {
        if (*it <= 0) {
            leading++;
        } else {
            break;
        }
    }
    for (std::deque < double >::reverse_iterator rit = h_.rbegin(); rit != h_.rend(); ++rit) {
        if (*rit <= 0) {
            trailing++;
        } else {
            break;
        }
    }
    if (leading + trailing >= h_.size()) {
        throw customException ("Cannot trim dynamic_one_dim_histogram because it is empty");
    }
    nbins_ -= (leading + trailing);
    lb_ += leading*delta_;
    ub_ -= trailing*delta_;
    for (unsigned int i = 0; i < leading; ++i) {
        h_.pop_front();
    }
    for (unsigned int i = 0; i < trailing; ++i) {
        h_.pop_back();
    }
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.