.TH "/home/nam4/Desktop/sandbox/FHMCSimulation/src/global.h" 3 "Thu Dec 29 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/global.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <exception>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBcustomException\fP"
.br
.RI "\fIError handling via custom exceptions\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSYS_FAILURE\fP   -1"
.br
.RI "\fIReturned from main the simualtion encountered a major error\&. \fP"
.ti -1c
.RI "#define \fBSAFE_EXIT\fP   0"
.br
.RI "\fIReturned from main the simulation ran without error\&. \fP"
.ti -1c
.RI "#define \fBPI\fP   3\&.14159265359"
.br
.RI "\fINumerical approximation of pi\&. \fP"
.ti -1c
.RI "#define \fBMAX_BARRIERS_PER_SPECIES\fP   100"
.br
.RI "\fIMax barrier number allowed for each species in input file\&. \fP"
.ti -1c
.RI "#define \fBH2_2PI\fP   1\&.0"
.br
.RI "\fIPortion of de Broglie wavelength that is not mass or T-dependent, Delta = sqrt(H2_2PI/mass/kT) \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBRNG_SEED\fP"
.br
.RI "\fIDefault RNG seed\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define H2_2PI   1\&.0"

.PP
Portion of de Broglie wavelength that is not mass or T-dependent, Delta = sqrt(H2_2PI/mass/kT) 
.PP
Definition at line 116 of file global\&.h\&.
.PP
Referenced by deleteParticle::make(), and insertParticle::make()\&.
.SS "#define MAX_BARRIERS_PER_SPECIES   100"

.PP
Max barrier number allowed for each species in input file\&. 
.PP
Definition at line 115 of file global\&.h\&.
.PP
Referenced by setSystemBarriers()\&.
.SS "#define PI   3\&.14159265359"

.PP
Numerical approximation of pi\&. 
.PP
Definition at line 114 of file global\&.h\&.
.PP
Referenced by aggVolBias3::make(), rightTriangleXZ::rightTriangleXZ(), quaternion::setRandomRot(), and lennardJones::tailCorrection()\&.
.SS "#define SAFE_EXIT   0"

.PP
Returned from main the simulation ran without error\&. 
.PP
Definition at line 113 of file global\&.h\&.
.SS "#define SYS_FAILURE   -1"

.PP
Returned from main the simualtion encountered a major error\&. 
.PP
Definition at line 112 of file global\&.h\&.
.PP
Referenced by simSystem::addPotential(), checkBounds(), initialize(), checkpoint::load(), moves::moves(), performCrossover(), performTMMC(), performWALA(), simSystem::readConfig(), sanityChecks(), setConfig(), setMoves(), setPairPotentials(), setSystemBarriers(), and simSystem::simSystem()\&.
.SH "Variable Documentation"
.PP 
.SS "int RNG_SEED"

.PP
Default RNG seed\&. 
.PP
Definition at line 3 of file utilities\&.cpp\&.
.PP
Referenced by initialize(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), insertParticle::make(), swapParticles::make(), moves::makeMove(), random3DSurfaceVector(), and quaternion::setRandomRot()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
