histogram
NAME
histogram -
SYNOPSIS
#include <histogram.h>
Public Member Functions
~histogram ()
histogram ()
histogram (const std::vector< double > lbound, const std::vector< double > ubound, const std::vector< long long unsigned int > nbins)
Instantiate a multidimensional histogram.
void print (const std::string fileName)
Print RAW (UN-NORMALIZED) histogram to file.
void increment (const long long unsigned int address, const double val)
Increment the histogram by a given value at a given address.
void increment (const std::vector< double > &coords, const double val)
Increment the histogram by a given value at a given coordinate.
void set (const std::vector< double > &h, const std::vector< double > &ctr)
Assign the histogram and its corresponding counter.
const long long unsigned int getAddress (const std::vector< double > &coords)
Get the linear address of the multidimensional coordinate.
const std::vector< double > getCoords (long long unsigned int address)
Given an address, return the (center of the) coordinate this refers to.
std::vector< double > getRawHistogram ()
Return the current histogram.
std::vector< double > getCounter ()
Return the current histogram counter.
Detailed Description
Definition at line 14 of file histogram.h.
Constructor & Destructor Documentation
histogram::~histogram () [inline]
Definition at line 16 of file histogram.h.
{;}
histogram::histogram () [inline]
Definition at line 17 of file histogram.h.
{;}
histogram::histogram (const std::vector< double >lbound, const std::vector< double >ubound, const std::vector< long long unsigned int >nbins)
Instantiate a multidimensional histogram. Bounds and widths must be specified for each dimension. A bin is considered 'centered' on its value.
Parameters:
lbound Vector of lower bounds for each dimension
ubound Vector of upper bounds for each dimension
nbins Number of bins to use along each dimension
Definition at line 203 of file histogram.cpp.
                                                                                                                                            {
    if (lbound.size() != ubound.size()) {
        throw customException ("Upper and lower bounds for histogram do have the same size");
    }
    if (nbins.size() != lbound.size()) {
        throw customException ("Number of bins for histogram's dimensions does not have the same size as its bounds");
    }
    dim_ = nbins.size();
    widths_.resize(dim_, 0);
    delta_.resize(dim_, 0);
    size_ = 1;
    for (unsigned int i = 0; i < dim_; ++i) {
        if (lbound[i] > ubound[i]) {
            throw customException ("Lower bound > upper bound illegal for a histogram");
        }
        if (lbound[i] < ubound[i]) {
            if (nbins[i] <= 1) {
                throw customException ("Must > 1 bins for each dimensions in the histogram");
            }
            size_ *= nbins[i];
            delta_[i] = (ubound[i] - lbound[i])/(nbins[i]-1);
        } else {
            // special case when upper and lower bound are the same (nbins = 1)
            if (nbins[i] != 1) {
                throw customException ("nbins must be 1 if upper and lower bounds are equal in histogram");
            }
            size_ *= nbins[i];
            delta_[i] = 1.0; // arbitrary
        }
        // build projected widths
        if (i == 0) {
            widths_[i] = 1;
        } else {
            widths_[i] = widths_[i-1]*nbins[i-1];
        }
    }
    lbound_ = lbound;
    ubound_ = ubound;
    nbins_ = nbins;
    // initialize the histogram to 0
    try {
        h_.resize(size_, 0);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory for histogram");
    }
    try {
        counter_.resize(size_, 0);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory for histogram");
    }
}
Member Function Documentation
const long long unsigned int histogram::getAddress (const std::vector< double > &coords)
Get the linear address of the multidimensional coordinate.
Parameters:
coords Coordinates
Definition at line 298 of file histogram.cpp.
Referenced by increment(), simSystem::printExtMoments(), and simSystem::restartExtMoments().
                                                                                    {
        if (coords.size() != dim_) {
            throw customException ("Illegal number of coordinate dimensions, cannot locate histogram address");
        }
        long long unsigned int address = 0;
        for (unsigned int i = 0; i < dim_; ++i) {
            address += round((coords[i] - lbound_[i])/delta_[i])*widths_[i]; // will work safely for integers too
        }
        return address;
}
const std::vector< double > histogram::getCoords (long long unsigned intaddress)
Given an address, return the (center of the) coordinate this refers to.
Parameters:
address Address to check
Definition at line 314 of file histogram.cpp.
                                                                             {
        std::vector <double> coords (dim_, 0);
        if (address >= size_) {
            throw customException ("Histogram address out of bounds");
        }
        for (unsigned int i = dim_-1; i > 0; --i) {
            long long int diff = floor(address/widths_[i]);
            coords[i] = diff*delta_[i] + lbound_[i];
            address -= diff*widths_[i];
        }
        coords[0] = address*delta_[0] + lbound_[0];
        return coords;
}
std::vector< double > histogram::getCounter () [inline]
Return the current histogram counter.
Definition at line 27 of file histogram.h.
Referenced by simSystem::extMomCounter(), and simSystem::printExtMoments().
std::vector< double > histogram::getRawHistogram () [inline]
Return the current histogram.
Definition at line 26 of file histogram.h.
Referenced by simSystem::printExtMoments(), and simSystem::restartExtMoments().
void histogram::increment (const long long unsigned intaddress, const doubleval)
Increment the histogram by a given value at a given address.
Parameters:
address Address of the histogram to increment
val Value to add to the histogram at address
Definition at line 267 of file histogram.cpp.
Referenced by simSystem::recordExtMoments().
                                                                                 {
        if (address < size_) {
            h_[address] += val;
            counter_[address] += 1.0;
        } else {
            throw customException ("Histogram address out of bounds");
        }
}
void histogram::increment (const std::vector< double > &coords, const doubleval)
Increment the histogram by a given value at a given coordinate.
Parameters:
coords Vector of coordinates correponding to a location in the histogram to increment
val Value to add to the histogram at address
Definition at line 282 of file histogram.cpp.
References getAddress().
                                                                             {
        long long unsigned int address = 0;
        try {
            address = getAddress (coords);
        } catch (customException &ce) {
            throw customException ("Histogram address out of bounds");
        }
        h_[address] += val;
        counter_[address] += 1.0;
}
void histogram::print (const std::stringfileName)
Print RAW (UN-NORMALIZED) histogram to file.
Parameters:
fileName Name of file to print to
Definition at line 335 of file histogram.cpp.
                                               {
    // Print histogram
    std::ofstream of;
    of.open(fileName.c_str(), std::ofstream::out);
    if (!of.is_open()) {
        throw customException ("Unable to write histogram to "+fileName);
    }
    of << "# Histogram in single row (vectorized) notation." << std::endl;
    for (unsigned int i = 0; i < dim_; ++i) {
        of << "# dim_"+std::to_string(i+1)+"_upper_bound:" << ubound_[i] << std::endl;
        of << "# dim_"+std::to_string(i+1)+"_lower_bound:" << lbound_[i] << std::endl;
        of << "# dim_"+std::to_string(i+1)+"_number_of_bins:" << nbins_[i] << std::endl;
    }
    for (unsigned long long int i = 0; i < h_.size(); ++i) {
        of << h_[i] << std::endl;
    }
    of.close();
}
void histogram::set (const std::vector< double > &h, const std::vector< double > &ctr)
Assign the histogram and its corresponding counter.
Parameters:
h histogram
ctr Counter
Definition at line 360 of file histogram.cpp.
Referenced by simSystem::restartExtMoments().
                                                                               {
    if (h.size() != ctr.size()) {
        throw customException ("Cannot set the histogram since counter and histogram have different lengths");
    }
    if (h.size() != h_.size()) {
        throw customException ("Cannot set the histogram since new histogram has different length compared to current one");
    }
    if (ctr.size() != counter_.size()) {
        throw customException ("Cannot set the histogram since new counter has different length compared to current one");
    }
    h_ = h;
    counter_ = ctr;
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.