.TH "mcMove" 3 "Thu Dec 29 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mcMove \- 
.PP
Virtual base class for all Monte Carlo moves\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <moves\&.h>\fP
.PP
Inherited by \fBaggVolBias3\fP, \fBaggVolBiasDelete\fP, \fBaggVolBiasInsert\fP, \fBdeleteParticle\fP, \fBinsertParticle\fP, \fBswapParticles\fP, and \fBtranslateParticle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmcMove\fP ()"
.br
.ti -1c
.RI "\fBmcMove\fP (const int typeIndex, const std::string tag)"
.br
.ti -1c
.RI "virtual \fB~mcMove\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBmake\fP (\fBsimSystem\fP &sys)=0"
.br
.RI "\fIMake a MC move, return MOVE_SUCCESS or MOVE_FAILURE\&. \fP"
.ti -1c
.RI "const bool \fBchangeN\fP ()"
.br
.RI "\fIReturns whether or not the move has the ability to change the net number of particles in the system\&. \fP"
.ti -1c
.RI "const int \fBwhatType\fP ()"
.br
.RI "\fIReturns the index referring to the atom type this move operates on\&. \fP"
.ti -1c
.RI "const std::string \fBmyName\fP ()"
.br
.RI "\fIReturn the name of this move\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBchangeN_\fP"
.br
.RI "\fIDoes this move have the capacity to create a net change in the total number of particles? \fP"
.ti -1c
.RI "int \fBtypeIndex_\fP"
.br
.RI "\fISpecies index this move will operate on\&. \fP"
.ti -1c
.RI "std::string \fBname_\fP"
.br
.RI "\fIMove name\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Virtual base class for all Monte Carlo moves\&. 
.PP
Definition at line 15 of file moves\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mcMove::mcMove ()\fC [inline]\fP"

.PP
Definition at line 17 of file moves\&.h\&.
.PP
.nf
17 {};
.fi
.SS "mcMove::mcMove (const inttypeIndex, const std::stringtag)\fC [inline]\fP"

.PP
Definition at line 18 of file moves\&.h\&.
.PP
References name_, and typeIndex_\&.
.PP
.nf
18 { typeIndex_ = typeIndex; name_ = tag+std::to_string(typeIndex); }
.fi
.SS "mcMove::~mcMove ()\fC [pure virtual]\fP"

.PP
Definition at line 3 of file moves\&.cpp\&.
.PP
.nf
3                  {
4     ;
5 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "const bool mcMove::changeN ()\fC [inline]\fP"

.PP
Returns whether or not the move has the ability to change the net number of particles in the system\&. 
.PP
Definition at line 21 of file moves\&.h\&.
.PP
References changeN_\&.
.SS "virtual int mcMove::make (\fBsimSystem\fP &sys)\fC [pure virtual]\fP"

.PP
Make a MC move, return MOVE_SUCCESS or MOVE_FAILURE\&. 
.PP
Implemented in \fBaggVolBiasDelete\fP, \fBaggVolBiasInsert\fP, \fBinsertParticle\fP, \fBswapParticles\fP, \fBdeleteParticle\fP, \fBtranslateParticle\fP, and \fBaggVolBias3\fP\&.
.SS "const std::string mcMove::myName ()\fC [inline]\fP"

.PP
Return the name of this move\&. 
.PP
Definition at line 23 of file moves\&.h\&.
.PP
References name_\&.
.SS "const int mcMove::whatType ()\fC [inline]\fP"

.PP
Returns the index referring to the atom type this move operates on\&. 
.PP
Definition at line 22 of file moves\&.h\&.
.PP
References typeIndex_\&.
.SH "Field Documentation"
.PP 
.SS "bool mcMove::changeN_\fC [protected]\fP"

.PP
Does this move have the capacity to create a net change in the total number of particles? 
.PP
Definition at line 26 of file moves\&.h\&.
.PP
Referenced by aggVolBias3::aggVolBias3(), aggVolBiasDelete::aggVolBiasDelete(), aggVolBiasInsert::aggVolBiasInsert(), changeN(), deleteParticle::deleteParticle(), insertParticle::insertParticle(), swapParticles::swapParticles(), and translateParticle::translateParticle()\&.
.SS "std::string mcMove::name_\fC [protected]\fP"

.PP
Move name\&. 
.PP
Definition at line 28 of file moves\&.h\&.
.PP
Referenced by aggVolBias3::aggVolBias3(), aggVolBiasDelete::aggVolBiasDelete(), aggVolBiasInsert::aggVolBiasInsert(), deleteParticle::deleteParticle(), insertParticle::insertParticle(), mcMove(), myName(), swapParticles::swapParticles(), and translateParticle::translateParticle()\&.
.SS "int mcMove::typeIndex_\fC [protected]\fP"

.PP
Species index this move will operate on\&. 
.PP
Definition at line 27 of file moves\&.h\&.
.PP
Referenced by aggVolBias3::aggVolBias3(), aggVolBiasDelete::aggVolBiasDelete(), aggVolBiasInsert::aggVolBiasInsert(), deleteParticle::deleteParticle(), insertParticle::insertParticle(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), mcMove(), swapParticles::swapParticles(), translateParticle::translateParticle(), and whatType()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
