moves
NAME
moves -
Class that tracks and decides which moves whould be made.
SYNOPSIS
#include <mover.h>
Public Member Functions
moves (const int M=1)
Instantiate moves class.
~moves ()
Destructor for moves class.
void clearAll ()
Clear all moves and related information from the class, but leaves M intact.
void makeMove (simSystem &sys)
Choose a move to make.
void print (const std::string filename)
Print move information to file.
void addInsert (const int index, const double prob)
Add insertion move.
void addDelete (const int index, const double prob)
Add deletion move.
void addSwap (const int index1, const int index2, const double prob)
Add swap move.
void addTranslate (const int index, const double prob, const double maxD, const std::vector< double > &box)
Add translate move.
void setM (const int M)
Set the value of M.
int getM ()
std::vector< std::vector
< double > > reportMoveStatistics ()"
Report the statistics on the success/failure of each move made so far.
std::vector< double > reportProbabilities ()
Echo the normalized probabilities of each move in the object.
Detailed Description
Class that tracks and decides which moves whould be made.
However, it does NOT store the moves themselves so they should be fixed in memory elsewhere.
Definition at line 20 of file mover.h.
Constructor & Destructor Documentation
moves::moves (const intM = 1)
Instantiate moves class.
Parameters:
in M Number of expanded ensemble stages for insert/delete moves
Definition at line 8 of file mover.cpp.
References sendErr(), setM(), SYS_FAILURE, and customException::what().
                         {
    try {
        setM (M);
    } catch (customException &ce) {
        sendErr(ce.what());
        exit(SYS_FAILURE);
    }
}
moves::~moves ()
Destructor for moves class.
Definition at line 20 of file mover.cpp.
               {
    ;
}
Member Function Documentation
void moves::addDelete (const intindex, const doubleprob)
Add deletion move.
Parameters:
index Particle index to operate on
prob Probability
Definition at line 95 of file mover.cpp.
References numToStr().
Referenced by setMoves().
                                                         {
    auto om = std::make_shared < deleteParticle > (index, "delete");
    ownedMoves_.push_back(om);
    try {
        addOn_(ownedMoves_.back()->changeN(), prob);
    } catch (std::exception &ex) {
        const std::string msg = ex.what();
        throw customException ("Cannot add deletion move for species "+numToStr(index+1)+" : "+msg);
    }
}
void moves::addInsert (const intindex, const doubleprob)
Add insertion move.
Parameters:
index Particle index to operate on
prob Probability
Definition at line 78 of file mover.cpp.
References numToStr().
Referenced by setConfig(), and setMoves().
                                                         {
    auto om = std::make_shared < insertParticle > (index, "insert");
    ownedMoves_.push_back(om);
    try {
        addOn_(ownedMoves_.back()->changeN(), prob);
    } catch (std::exception &ex) {
        const std::string msg = ex.what();
        throw customException ("Cannot add insertion move for species "+numToStr(index+1)+" : "+msg);
    }
}
void moves::addSwap (const intindex1, const intindex2, const doubleprob)
Add swap move.
Parameters:
index1 Particle index 1 to operate on
index2 Particle index 2 to operate on
prob Probability
Definition at line 113 of file mover.cpp.
References numToStr().
Referenced by setMoves().
                                                                          {
    auto om = std::make_shared < swapParticles > (index1, index2, "swap");
    ownedMoves_.push_back(om);
    try {
        addOn_(ownedMoves_.back()->changeN(), prob);
    } catch (std::exception &ex) {
        const std::string msg = ex.what();
        throw customException ("Cannot add swap move for species pair ("+numToStr(index1+1)+","+numToStr(index2+1)+") : "+msg);
    }
}
void moves::addTranslate (const intindex, const doubleprob, const doublemaxD, const std::vector< double > &box)
Add translate move.
Parameters:
index Particle index to operate on
prob Probability
maxD Maximium translation
box Box dimensions
Definition at line 132 of file mover.cpp.
References numToStr().
Referenced by setMoves().
                                                                                                                {
    auto om = std::make_shared < translateParticle > (index, "translate");
    try {
        om->setMaxTranslation (maxD, box);
        ownedMoves_.push_back(om);
        addOn_(ownedMoves_.back()->changeN(), prob);
    } catch (std::exception &ex) {
        const std::string msg = ex.what();
        throw customException ("Cannot add translation move for species "+numToStr(index+1)+" : "+msg);
    }
}
void moves::clearAll ()
Clear all moves and related information from the class, but leaves M intact.
Definition at line 27 of file mover.cpp.
Referenced by setMoves().
                      {
    normProbabilities_.clear();
    rawProbabilities_.clear();
    succeeded_.clear();
    attempted_.clear();
    ownedMoves_.clear();
}
int moves::getM () [inline]
Definition at line 33 of file mover.h.
{ return M_; }
void moves::makeMove (simSystem &sys)
Choose a move to make. If in an expanded ensemble, will restrict moves which change the number of particles to the atom type that is currently on partially in the system.
Parameters:
sys simSystem object to make a move in.
Definition at line 191 of file mover.cpp.
References simSystem::getCurrentM(), simSystem::getFractionalAtomType(), simSystem::getTotalM(), rng(), RNG_SEED, and customException::what().
Referenced by performCrossover(), performTMMC(), and performWALA().
                                    {
    if (sys.getTotalM() != M_) {
        throw customException ("Error, M in system different from M in moves class operating on the system");
    }
    int moveChosen = -1, succ = 0, mIndex = 0;
    bool done = false;
    while (!done) {
        const double ran = rng (&RNG_SEED);
        for (unsigned int i = 0; i < normProbabilities_.size(); ++i) {
            if (ran < normProbabilities_[i]) {
                if (sys.getTotalM() > 1) {
                    // expanded ensemble has to check the moves because have to only work on the partially inserted atom
                    if ((ownedMoves_[i]->changeN() == true) && (ownedMoves_[i]->whatType() != sys.getFractionalAtomType()) && (sys.getCurrentM() > 0)) {
                        // reject this choice because we must only insert/delete the type that is already partially inserted IFF we are *already* in a partially inserted state
                        // choose a new move
                        done = false;
                        break;
                    } else {
                        // get M before move happens which can change the state of the system
                        if (ownedMoves_[i]->changeN()) {
                            mIndex = sys.getCurrentM();
                        }
                        try {
                            succ = ownedMoves_[i]->make(sys);
                        } catch (customException &ce) {
                            std::string a = "Failed to make a move properly: ";
                            std::string b = ce.what();
                            throw customException(a+b);
                        }
                        done = true;
                        moveChosen = i;
                        break;
                    }
                } else {
                    // without expanded ensemble, inserts/deletes can proceed unchecked
                    try {
                        succ = ownedMoves_[i]->make(sys);
                    } catch (customException &ce) {
                        std::string a = "Failed to make a move properly: ";
                        std::string b = ce.what();
                        throw customException(a+b);
                    }
                    done = true;
                    moveChosen = i;
                    mIndex = 0;
                    break;
                }
            }
        }
    }
    if (moveChosen < 0) {
        throw customException("Failed to choose a move properly");
    }
    attempted_[moveChosen][mIndex] += 1.0;
    succeeded_[moveChosen][mIndex] += succ;
}
void moves::print (const std::stringfilename)
Print move information to file. Appends by default.
Parameters:
filename Name of file to print to.
Definition at line 53 of file mover.cpp.
References getTimeStamp(), and reportMoveStatistics().
Referenced by performCrossover(), performTMMC(), and performWALA().
                                           {
    std::ofstream statFile (filename.c_str(), std::ofstream::out | std::ofstream::app);
    std::vector < std::vector < double > > stats = reportMoveStatistics();
    statFile << "Time: " << getTimeStamp() << std::endl;
    statFile << "---------- Move Statistics --------- " << std::endl << "Move\t Success" << std::endl;
    for (unsigned int i = 0; i < stats.size(); ++i) {
        double prod = 1.0;
        for (unsigned int j = 0; j < stats[i].size(); ++j) {
            prod *= stats[i][j];
            statFile << ownedMoves_[i]->myName() << " (from M = " << j << ")\t" << stats[i][j]*100.0 << std::endl;
        }
        if (stats[i].size() > 1) {
            statFile << "-------------------------------------\nProduct of percentages (%) = " << prod*100 << "\n-------------------------------------" << std::endl;
        }
    }
    statFile << "------------------------------------ " << std::endl;
    statFile.close();
}
std::vector< std::vector< double > > moves::reportMoveStatistics ()
Report the statistics on the success/failure of each move made so far. If the move changes total number of particles in the system, there is a column for each expanded state it traverses.
Returns:
ans Number of Success / Total Attempts for each move
Definition at line 256 of file mover.cpp.
Referenced by print().
                                                                {
    std::vector < std::vector < double > > ans = succeeded_;
    if (attempted_.begin() == attempted_.end()) {
        throw customException ("No moves added to system");
    }
    for (unsigned int i = 0; i < attempted_.size(); ++i) {
        for (unsigned int j = 0; j < attempted_[i].size(); ++j) {
            ans[i][j] /= attempted_[i][j];
        }
    }
    return ans;
}
std::vector< double > moves::reportProbabilities () [inline]
Echo the normalized probabilities of each move in the object.
Definition at line 35 of file mover.h.
void moves::setM (const intM)
Set the value of M.
Parameters:
in M Number of expanded ensemble stages for insert/delete moves
Definition at line 40 of file mover.cpp.
Referenced by moves(), and setMoves().
                             {
    if (M > 0) {
        M_ = M;
    } else {
        throw customException ("Error, number of expanded ensemble stages must be > 0");
    }
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.