quaternion
NAME
quaternion -
SYNOPSIS
#include <quaternion.h>
Public Member Functions
quaternion ()
~quaternion ()
void set (const std::vector< double > &q)
Set the quaternion's value.
void setAxisAngle (const std::vector< double > &u, const double angle)
Set the quaternion based on angle, axis desired.
void setRandomRot ()
Pick a quaternion that corresponds to a random 3D rotation.
void conjugate ()
Transform quaternion into its conjugate.
void normalize ()
Normalize a quaternion.
void inverse ()
Transform a quanternion into its inverse.
void translate (const std::vector< double > &t)
Translate a quaternion in 3D space.
double getNorm ()
Return the norm of the quaternion.
std::vector< double > get ()
std::vector< double > rotateVec (const std::vector< double > &vec)
Use this quaternion to operate on a vector, that causes its rotation.
quaternion operator+ (const quaternion &p)
Add a quaternion to this one.
quaternion operator- (const quaternion &p)
Subtract a quaternion from this one.
quaternion operator* (const quaternion &other)
Multiply this quaternion by another.
bool operator== (const quaternion &other)
Check if two quaternions are equal to each other to within a tolerance of 1.0e-12.
bool operator!= (const quaternion &other)
Check if two quaternions are not equal to each other to within a tolerance of 1.0e-12.
Detailed Description
Definition at line 9 of file quaternion.h.
Constructor & Destructor Documentation
quaternion::quaternion () [inline]
Definition at line 11 of file quaternion.h.
References setRandomRot().
{ q_.resize(4, 0.0); std::vector < double > dummy (3, 0); R_.resize(3, dummy); setRandomRot (); }
quaternion::~quaternion () [inline]
Definition at line 12 of file quaternion.h.
{};
Member Function Documentation
void quaternion::conjugate ()
Transform quaternion into its conjugate.
Definition at line 53 of file quaternion.cpp.
Referenced by inverse().
                            {
    for (unsigned int i = 1; i < 4; ++i) {
        q_[i] = -q_[i];
    }
}
std::vector< double > quaternion::get () [inline]
Definition at line 24 of file quaternion.h.
{ return q_; } // Return the quaternion's values
double quaternion::getNorm ()
Return the norm of the quaternion.
Definition at line 102 of file quaternion.cpp.
Referenced by normalize().
                            {
    double n2 = 0.0;
    for (unsigned int i = 0; i < 4; ++i) {
        n2 += q_[i]*q_[i];
    }
    return std::sqrt(n2);
}
void quaternion::inverse ()
Transform a quanternion into its inverse.
Definition at line 74 of file quaternion.cpp.
References conjugate().
                          {
    conjugate();
    double n2 = 0.0;
    for (unsigned int i = 0; i < 4; ++i) {
        n2 += q_[i]*q_[i];
    }
    for (unsigned int i = 0; i < 4; ++i) {
        q_[i] /= n2;
    }
}
void quaternion::normalize ()
Normalize a quaternion.
Parameters:
t Translation vector.
Definition at line 64 of file quaternion.cpp.
References getNorm().
                            {
    const double norm = getNorm();
    for (unsigned int i = 0; i < 4; ++i) {
        q_[i] /= norm;
    }
}
bool quaternion::operator!= (const quaternion &other) [inline]
Check if two quaternions are not equal to each other to within a tolerance of 1.0e-12.
Parameters:
other Other quaternion to compare with.
Definition at line 94 of file quaternion.h.
                                              {
        return !(*this == other);
    }
quaternion quaternion::operator* (const quaternion &other) [inline]
Multiply this quaternion by another. Does this in order of self*other.
Parameters:
other Quaternion to multiply this one by.
Returns:
self*other
Definition at line 64 of file quaternion.h.
References set().
                                                   {
        quaternion ans;
        std::vector < double > prod (4, 0);
        prod[0] = this->q_[0]*other.q_[0] - this->q_[1]*other.q_[1] - this->q_[2]*other.q_[2] - this->q_[3]*other.q_[3];
        prod[1] = this->q_[0]*other.q_[1] + this->q_[1]*other.q_[0] + this->q_[2]*other.q_[3] - this->q_[3]*other.q_[2];
        prod[2] = this->q_[0]*other.q_[2] - this->q_[1]*other.q_[3] + this->q_[2]*other.q_[0] + this->q_[3]*other.q_[1];
        prod[3] = this->q_[0]*other.q_[3] + this->q_[1]*other.q_[2] - this->q_[2]*other.q_[1] + this->q_[3]*other.q_[0];
        ans.set(prod);
        return ans;
    }
quaternion quaternion::operator+ (const quaternion &p) [inline]
Add a quaternion to this one.
Parameters:
p Quaternion to add to this one.
Definition at line 32 of file quaternion.h.
References set().
                                               {
        quaternion ans;
        std::vector < double > sum (4, 0);
        for (unsigned int i = 0; i < 4; ++i) {
            sum[i] = this->q_[i] + p.q_[i];
        }
        ans.set(sum);
        return ans;
    }
quaternion quaternion::operator- (const quaternion &p) [inline]
Subtract a quaternion from this one.
Parameters:
p Quaternion to subtract from this one.
Definition at line 47 of file quaternion.h.
References set().
                                               {
        quaternion ans;
        std::vector < double > sum (4, 0);
        for (unsigned int i = 0; i < 4; ++i) {
            sum[i] = this->q_[i] - p.q_[i];
        }
        ans.set(sum);
        return ans;
    }
bool quaternion::operator== (const quaternion &other) [inline]
Check if two quaternions are equal to each other to within a tolerance of 1.0e-12.
Parameters:
other Other quaternion to compare with.
Definition at line 80 of file quaternion.h.
                                              {
        for (unsigned int i = 0; i < 4; ++i) {
            if (fabs(this->q_[i] - other.q_[i]) > 1.0e-12) {
                return false;
            }
        }
        return true;
    }
std::vector< double > quaternion::rotateVec (const std::vector< double > &vec)
Use this quaternion to operate on a vector, that causes its rotation.
Parameters:
vec Vector to rotate.
Definition at line 115 of file quaternion.cpp.
                                                                           {
    std::vector < double > ans (3, 0);
    assignr_ (q_);
    for (unsigned int i = 0; i < 3; ++i) {
        for (unsigned int j = 0; j < 3; ++j) {
            ans[i] += R_[i][j]*vec[j];
        }
    }
    return ans;
}
void quaternion::set (const std::vector< double > &qv)
Set the quaternion's value.
Parameters:
qv 4 component vector, [x, x, y, z]
Definition at line 8 of file quaternion.cpp.
Referenced by operator*(), operator+(), and operator-().
                                                    {
    assignq_ (qv);
}
void quaternion::setAxisAngle (const std::vector< double > &u, const doubleangle)
Set the quaternion based on angle, axis desired. Does not need to be normalized.
Parameters:
angle Angle of rotation desired relative to axis (in radians)
aixs 3D axis to rotate about (in right-handed coordinates)
Definition at line 150 of file quaternion.cpp.
                                                                                {
    if (u.size() != 3) {
        throw customException ("Axis for Quaternion must have 3 elements");
    }
    q_[0] = std::cos(angle/2.0);
    const double s = std::sin(angle/2.0);
    q_[1] = s*u[0];
    q_[2] = s*u[1];
    q_[3] = s*u[2];
}
void quaternion::setRandomRot ()
Pick a quaternion that corresponds to a random 3D rotation.
Definition at line 131 of file quaternion.cpp.
References PI, rng(), and RNG_SEED.
Referenced by quaternion().
                                {
     // spherical coordinates to get random unit vector
     const double theta = std::acos(2.0*rng(&RNG_SEED) - 1.0);
     const double phi = 2.0*PI*rng(&RNG_SEED), sin_phi = std::sin(phi);
     // randomly pick angle
     const double angle = 2.0*PI*rng(&RNG_SEED), s = std::sin(angle/2.0);
     q_[0] = std::cos(angle/2.0);
     q_[1] = s*1.0*sin_phi*std::cos(theta);
     q_[2] = s*1.0*sin_phi*std::sin(theta);
     q_[3] = s*1.0*std::cos(phi);
 }
void quaternion::translate (const std::vector< double > &t)
Translate a quaternion in 3D space.
Parameters:
t Translation vector.
Definition at line 90 of file quaternion.cpp.
                                                         {
    if (t.size() != 3) {
        throw customException ("Translation vector for Quaternion must have 3 elements");
    }
    for (unsigned int i = 1; i < 4; ++i) {
        q_[i] += t[i-1];
    }
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.