.TH "/home/nam4/Desktop/sandbox/FHMCSimulation/src/quaternion.h" 3 "Fri Dec 30 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/quaternion.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'global\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBquaternion\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
