rightTriangleXZ
NAME
rightTriangleXZ -
SYNOPSIS
#include <barrier.h>
Inherits barrier.
Public Member Functions
~rightTriangleXZ ()
rightTriangleXZ (const double width, const double theta, const double lamW, const double eps, const double sigma, const double sep, const double offset, const std::vector< double > &box, const double zbase, bool top=false, const int M=1)
Instantiate a right triangle feature with its base in the xy-plane.
bool inside (const atom *a1, const std::vector< double > &box)
Check if an atom is overlapping the feature.
double energy (const atom *a1, const std::vector< double > &box)
Get the energy of a position assuming it is located within window 8.
Additional Inherited Members
Detailed Description
Definition at line 81 of file barrier.h.
Constructor & Destructor Documentation
rightTriangleXZ::~rightTriangleXZ () [inline]
Definition at line 83 of file barrier.h.
{};
rightTriangleXZ::rightTriangleXZ (const doublewidth, const doubletheta, const doublelamW, const doubleeps, const doublesigma, const doublesep, const doubleoffset, const std::vector< double > &box, const doublezbase, booltop = false, const intM = 1)
Instantiate a right triangle feature with its base in the xy-plane. It is raised in the z-direction and extends in the x-direction. Expanded ensembles scale the range of interaction as well as the magnitude.
Parameters:
width Width of triangle's feature
theta Elevation angle of the feature in radians (0, PI)
lamW Attractive range ratio relative to hard sphere in contact with the feature (akin to a square well potential's lambda), must be >= 1
eps Attraction strength to feature
sigma Hard sphere diameter of interaction with the feature
sep Distance between features
offset Offset from x = 0 position of the first feature. A positive offset shifts the feature in the +x direction.
box System box size to check the feature (as specified) is periodic in the box
zbase Z-coordinate of XY plane that defines the base of the feature. To avoid periodicity effects be sure it is > 0 and less than Lz, but this depends on other interactions so it cannot be checked automatically here.
top If true, feature is on the 'top', else is on the bottom (default)
M Number of expanded ensemble states to recognize (default = 1)
Definition at line 18 of file barrier.cpp.
References barrier::M_, NUM_INFINITY, and PI.
                                                                                                                                                                                                                                                    {
    if (sep < 0.0) {
        throw customException ("rightTriangle sep is out of bounds");
    }
    // Check the feature fits periodically in the box
    if ( fmod(box[0]/(sep+width), 1) != 0.0 ) {
        throw customException ("rightTriangle width+separation is not commensurate with the box size");
    }
    if (theta <= 0.0 || theta >= PI/2.0) {
        throw customException ("rightTriangle elevation angle is out of bounds");
    }
    if (sigma <= 0.0) {
        throw customException ("rightTriangle sigma is out of bounds");
    }
    if (lamW < 1.0) {
        throw customException ("rightTriangle lamW is out of bounds");
    }
    if (eps < 0.0) {
        throw customException ("rightTriangle eps is out of bounds");
    }
    if (M < 1) {
        throw customException ("rightTriangle M value is out of bounds");
    }
    if (zbase < 0.0 || zbase > box[2]) {
        throw customException ("rightTriangle zbase value is out of bounds");
    }
    if (offset >= box[0] || offset < 0) {
        throw customException ("rightTriangle offset value is out of bounds");
    }
    // store variables internally and do conversion to conventions in which derivation was done
    zbase_ = zbase;
    width_ = width;
    sep_ = sep;
    theta_ = theta;
    xOffset_ = offset;
    top_ = top;
    M_ = M;
    lamW_ = lamW;
    x_max_image_ = (int) round(box[0]/(sep+width)) - 1;
    // precompute points and trigonometry
    a_ = width_*cos(theta_)*sin(theta_);
    b_ = width_*sin(theta_)*cos(PI/2.0-theta_);
    c_ = width_*cos(theta_)*cos(theta_);
    try {
        sigma_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    try {
        eps_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    try {
        box_.resize(3);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    box_ = box;
    try {
        ub_check_.resize(M_, -NUM_INFINITY);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    try {
        ub_seg_x_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    for (int i = 0; i < M_; ++i) {
        try {
            ub_seg_x_[i].resize(4);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory");
        }
    }
    try {
        lb_seg_x_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    for (int i = 0; i < M_; ++i) {
        try {
            lb_seg_x_[i].resize(4);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory");
        }
    }
    try {
        ub_seg_z_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    for (int i = 0; i < M_; ++i) {
        try {
            ub_seg_z_[i].resize(4);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory");
        }
    }
    try {
        lb_seg_z_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    for (int i = 0; i < M_; ++i) {
        try {
            lb_seg_z_[i].resize(4);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory");
        }
    }
    try {
        ub_slope_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    for (int i = 0; i < M_; ++i) {
        try {
            ub_slope_[i].resize(5);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory");
        }
    }
    try {
        lb_slope_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    for (int i = 0; i < M_; ++i) {
        try {
            lb_slope_[i].resize(5);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory");
        }
    }
    try {
        ub_int_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    for (int i = 0; i < M_; ++i) {
        try {
            ub_int_[i].resize(5);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory");
        }
    }
    try {
        lb_int_.resize(M_);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory");
    }
    for (int i = 0; i < M_; ++i) {
        try {
            lb_int_[i].resize(5);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory");
        }
    }
    for (int i = 0; i < M_; ++i) {
        if (i == 0) {
            sigma_[i] = sigma;
            eps_[i] = eps;
        } else {
            sigma_[i] = sigma_[0]/M_*i;
            eps_[i] = eps_[0]/M_*i;
        }
        ub_seg_x_[i][0] = -lamW_*sigma_[i]*sin(theta_);
        ub_seg_x_[i][1] = c_ - lamW_*sigma_[i]*sin(theta_);
        ub_seg_x_[i][2] = c_ + lamW_*sigma_[i]*cos(theta_);
        ub_seg_x_[i][3] = width_ + lamW_*sigma_[i]*cos(theta_);
        lb_seg_x_[i][0] = -sigma_[i]/2.0*sin(theta_);
        lb_seg_x_[i][1] = c_ - sigma_[i]/2.0*sin(theta_);
        lb_seg_x_[i][2] = c_ + sigma_[i]/2.0*cos(theta_);
        lb_seg_x_[i][3] = width_ + sigma_[i]/2.0*cos(theta_);
        ub_seg_z_[i][0] = lamW_*sigma_[i]*cos(theta_);
        ub_seg_z_[i][1] = a_ + lamW_*sigma_[i]*cos(theta_);
        ub_seg_z_[i][2] = a_ + lamW_*sigma_[i]*sin(theta_);
        ub_seg_z_[i][3] = lamW_*sigma_[i]*sin(theta_);
        lb_seg_z_[i][0] = sigma_[i]/2.0*cos(theta_);
        lb_seg_z_[i][1] = a_ + sigma_[i]/2.0*cos(theta_);
        lb_seg_z_[i][2] = a_ + sigma_[i]/2.0*sin(theta_);
        lb_seg_z_[i][3] = sigma_[i]/2.0*sin(theta_);
        ub_check_[i] = *std::max_element(ub_seg_z_[i].begin(), ub_seg_z_[i].end());
        ub_slope_[i][0] = 0.0;
        ub_slope_[i][1] = (ub_seg_z_[i][1] - ub_seg_z_[i][0])/(ub_seg_x_[i][1] - ub_seg_x_[i][0]);
        ub_slope_[i][2] = (ub_seg_z_[i][2] - ub_seg_z_[i][1])/(ub_seg_x_[i][2] - ub_seg_x_[i][1]);
        ub_slope_[i][3] = (ub_seg_z_[i][3] - ub_seg_z_[i][2])/(ub_seg_x_[i][3] - ub_seg_x_[i][2]);
        ub_slope_[i][4] = 0.0;
        ub_int_[i][0] = 0.0;
        ub_int_[i][1] = ub_seg_z_[i][0];
        ub_int_[i][2] = ub_seg_z_[i][1];
        ub_int_[i][3] = ub_seg_z_[i][2];
        ub_int_[i][4] = 0.0;
        lb_slope_[i][0] = 0.0;
        lb_slope_[i][1] = (lb_seg_z_[i][1] - lb_seg_z_[i][0])/(lb_seg_x_[i][1] - lb_seg_x_[i][0]);
        lb_slope_[i][2] = (lb_seg_z_[i][2] - lb_seg_z_[i][1])/(lb_seg_x_[i][2] - lb_seg_x_[i][1]);
        lb_slope_[i][3] = (lb_seg_z_[i][3] - lb_seg_z_[i][2])/(lb_seg_x_[i][3] - lb_seg_x_[i][2]);
        lb_slope_[i][4] = 0.0;
        lb_int_[i][0] = 0.0;
        lb_int_[i][1] = lb_seg_z_[i][0];
        lb_int_[i][2] = lb_seg_z_[i][1];
        lb_int_[i][3] = lb_seg_z_[i][2];
        lb_int_[i][4] = 0.0;
    }
}
Member Function Documentation
double rightTriangleXZ::energy (const atom *a1, const std::vector< double > &box) [virtual]
Get the energy of a position assuming it is located within window 8.
Parameters:
atom Pointer to atom to examine
box System box size. Will be checked that it is identical to value at class instantiation.
Implements barrier.
Definition at line 292 of file barrier.cpp.
References barrier::M_, atom::mState, NUM_INFINITY, pbc(), and atom::pos.
Referenced by inside().
                                                                               {
    for (unsigned int i = 0; i < box_.size(); ++i) {
        if (box[i] != box_[i]) {
            throw customException ("System box size has changed from when rightTriangleXZ was instantiated");
        }
    }
    const int mv = a1->mState;
    std::vector < double > p = a1->pos;
    if (mv < 0 || mv > M_-1) {
        throw customException ("mState out of bounds for rightTriangleZ");
    }
    // First find nearest feature (the one right below)
    pbc (p, box);
    double dx = p[0] - xOffset_, dz = 0.0;
    int x_image = int(floor(dx/(width_+sep_)));
    double x_shift = x_image*(width_+sep_);
    if (top_) {
        dz = zbase_ - p[2];
    } else {
        dz = p[2] - zbase_;
    }
    if (dz > ub_check_[mv]) {
        return 0.0;
    }
    double U = featureInteraction_ (dx, dz, x_shift, mv);
    if (U == NUM_INFINITY) {
        return U;
    }
    // Must check all neighboring images, including images beyond edge of each box for periodicity effects
    int x_i = x_image+1;
    if (x_i > x_max_image_+1) {
        x_i = -1;
    }
    while (x_i != x_image) { // Stop once one complete cycle is finished
        x_shift = x_i*(width_+sep_);
        double dU = featureInteraction_ (dx, dz, x_shift, mv);
        if (dU == NUM_INFINITY) {
            return NUM_INFINITY;
        } else {
            U += dU;
        }
        x_i += 1;
        if (x_i > x_max_image_+1) {
            x_i = -1;
        }
    }
    return U;
}
bool rightTriangleXZ::inside (const atom *a1, const std::vector< double > &box) [virtual]
Check if an atom is overlapping the feature. The term 'inside' can be a bit confusing here. This function returns true if an atom does NOT overlap the feature (have infinite interaction energy), which might be considered as being 'outside' the feature depending on how you look at it. However, to be consistent with the expected behavior of this virtual function, this is how this function must behave.
Parameters:
a1 Atom whose position to test.
box System box size. Not actually used, but will be checked that it is identical to value at class instantiation.
Implements barrier.
Definition at line 360 of file barrier.cpp.
References energy(), NUM_INFINITY, and customException::what().
                                                                             {
    double U = NUM_INFINITY;
    try {
        U = energy (a1, box); // takes care of pbc internally
    } catch (customException &ce) {
        throw customException ("Unable to test if inside rightTriangleXZ : "+std::to_string(*ce.what()));
        //exit (SYS_FAILURE);
    }
    if (U < NUM_INFINITY) {
        return true;
    } else {
        return false;
    }
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.