simSystem
NAME
simSystem -
System information for the simulation.
SYNOPSIS
#include <system.h>
Public Member Functions
simSystem ()
simSystem (const unsigned int nSpecies, const double beta, const std::vector< double > box, const std::vector< double > mu, const std::vector< int > maxSpecies, const std::vector< int > minSpecies, const int Mtot, const double energyHistDelta=10.0, const int max_order=2)
Initialize the system.
~simSystem ()
bool addKECorrection ()
void toggleKE ()
Toggle KE adjustment to energy setting.
void incrementEnergy (const double dU)
Increment the system's energy.
void addPotential (const int spec1, const int spec2, const std::string ppot_name, const std::vector< double > &params, const bool useCellList=false, const std::string tabFile='')
Add a pair potential to the system which governs the pair (spec1, spec2).
void printSnapshot (std::string filename, std::string comment, bool overwrite=true)
Print an XYZ file of the instantaneous system configuration.
void insertAtom (const int typeIndex, atom *newAtom, bool override=false)
Insert an atom into the system.
void deleteAtom (const int typeIndex, const int atomIndex, bool override=false)
Delete an atom from the system.
void translateAtom (const int typeIndex, const int atomIndex, std::vector< double > oldPos)
Translate an atom in the system.
void readConfig (std::string filename)
Read an XYZ file as the system's initial configuration.
void setEUB (const std::vector< double > eub)
Assign energy upper bound from restart.
void setELB (const std::vector< double > elb)
Assign energy lower bound from restart.
void checkEnergyHistogramBounds ()
Monitor the energy histogram bounds at each Ntot.
void refineEnergyHistogramBounds ()
Check the histogram entries and trim off zero-valued entries and bounds.
void recordEnergyHistogram ()
Record the energy histogram for the system at a given Ntot.
void reInitializeEnergyHistogram ()
Re-initialize the energy histogram with internal estimates of bounds.
void printEnergyHistogram (const std::string fileName, const bool normalize=true)
Print the (normalized by default) energy histogram for each Ntot.
void restartEnergyHistogram (const std::string prefix)
Restart the energy histogram for each Ntot from unnormalized checkpoint.
void refinePkHistogramBounds ()
Check the histogram entries and trim off zero-valued entries and bounds.
void recordPkHistogram ()
Record the particle number histogram for the system at a given Ntot.
void printPkHistogram (const std::string fileName, const bool normalize=true)
Print the (normalized by default) particle number histogram for each Ntot.
void restartPkHistogram (const std::string prefix)
Restart the particle histogram for each Ntot from unnormalized checkpoint.
void recordExtMoments ()
Record the extensive moment at a given Ntot.
void printExtMoments (const std::string fileName, const bool normalize=true)
Print the (normalized by default) extensive energy histogram for each Ntot.
void restartExtMoments (const std::string prefix, const std::vector< double > &ctr)
Restart the extensive energy histogram for each Ntot from unnormalized checkpoint.
void startWALA (const double lnF, const double g, const double s, const int Mtot)
Start using Wang-Landau and instantiate the bias object.
void stopWALA ()
Stop using Wang-Landau and free the bias object.
void startTMMC (const long long int tmmcSweepSize, const int Mtot)
Start using TMMC and instantiate the bias object.
void stopTMMC ()
Stop using TMMC and free the bias object.
void setTotNBounds (const std::vector< int > &bounds)
Set the bounds on the total number of particles in a system.
void incrementMState ()
Increase the expanded ensemble state of the system by 1.
void decrementMState ()
Decrease the expanded ensemble state of the system by 1.
bool potentialIsSet (const int spec1, const int spec2)
Boolean which returns whether or not a pair has had its potential specified by the user yet.
const int nSpecies ()
Return the number of different species in the system.
const int maxSpecies (const int index)
Returns the absolute maximum number of a given species type allowed in the system.
const int minSpecies (const int index)
Returns the absolute minimum number of a given species type allowed in the system.
const int totNMax ()
Return upper bound on the total number of atoms in the system.
const int totNMin ()
Return lower bound on the total number of atoms in the system.
const int getTotN ()
Return a sum of the total number of atoms currently in the system.
const int getMaxOrder ()
Return the max order the extensive moments are being stored out to.
const int getCurrentM ()
Return the system's current expanded ensemble fractional state.
const int getTotalM ()
Return the total number of fractional states available to species in the expanded ensemble.
const int getFractionalAtomType ()
Return the atom type of the fractional atom.
const double energy ()
Return the system's instantaneous energy.
const double scratchEnergy ()
Recalculate the energy of the system from scratch.
const double beta ()
Return 1/kT.
const double mu (const int index)
Return the chemical potential for a given species' index.
const double mass (const int index)
Return the mass of a given species' index.
const std::vector< double > extMomCounter ()
Get counter for extensive moments needed for restarting system from a checkpoint.
const std::vector< double > box ()
Return the system box dimensions.
std::vector< double > getELB ()
Returns current tally of energy min at each Ntot for checkpointing.
std::vector< double > getEUB ()
Returns current tally of energy max at each Ntot for checkpointing.
std::vector< atom * > getNeighborAtoms (const unsigned int typeIndexA, const unsigned int typeIndexB, atom *_atom)
Return the list of neighbors of type A, around a particle of type B which is passed.
tmmc * getTMMCBias ()
Return pointer to the TMMC bias.
wala * getWALABias ()
Return pointer to the Wang-Landau bias.
atom * getFractionalAtom ()
Returns a pointer the atom in the system that is currently only fractionally inserted/deleted.
Data Fields
bool useTMMC
Logical stating whether or not to use TMMC biasing.
bool useWALA
Logical stating whether or not to use Wang-Landau biasing.
bool restartFromWALA
bool restartFromTMMC
Flags to restart from WALA or TMMC initially.
long long int tmmcSweepSize
Size of a sweep in TMMC.
long long int totalTMMCSweeps
Total number of sweeps to perform during TMMC.
long long int wlSweepSize
Size of Wang-Landau sweep.
long long int nCrossoverVisits
Number of crossovers that must occur before switching from WALA to TMMC.
double lnF_start
double lnF_end
Starting and ending lnF for Wang-Landau.
double wala_g
double wala_s
Wang-Landau g and s factors.
double gcmcEqSteps
In the case of unbiased GCMC, number of equilibration steps to perform.
double gcmcPrSteps
In the case of unbiased GCMC, number of production steps to perform.
double gcmcSnapFreq
In the case of unbiased GCMC, frequency with which to take snapshots of the system.
double gcmcThermoFreq
In the case of unbiased GCMC, frequency with which to record thermo properties.
long double walaTotalStepCounter
Tracks the total MC steps taken during WALA stage.
long double crossoverTotalStepCounter
Tracks the total MC steps taken during crossover stage.
long double tmmcTotalStepCounter
Tracks the total MC steps taken during TMMC stage.
tmmc * tmmcBias
TMMC biasing function.
wala * wlBias
WALA biasing function.
std::string restartFromWALAFile
std::string restartFromTMMCFile
Files to restart from WALA or TMMC initially.
std::vector< int > numSpecies
Total number of each type of atom the system contains.
std::vector< std::vector< atom > > atoms
Atoms in a matrix by type, and particle index, respectively that a system CAN hold but not all are actually 'in' the system.
std::vector< std::vector
< std::shared_ptr
< pairPotential > > > ppot"
Matrix of pair potentials for atom types i, j.
std::vector< compositeBarrier > speciesBarriers
Barriers, if any, for each species.
Detailed Description
System information for the simulation.
Definition at line 26 of file system.h.
Constructor & Destructor Documentation
simSystem::simSystem () [inline]
Definition at line 28 of file system.h.
{;}
simSystem::simSystem (const unsigned intnSpecies, const doublebeta, const std::vector< double >box, const std::vector< double >mu, const std::vector< int >maxSpecies, const std::vector< int >minSpecies, const intMtot, const doubleenergyHistDelta = 10.0, const intmax_order = 2)
Initialize the system. Sets the use of both WL and TMMC biasing to false.
Parameters:
nSpecies Number of unqiue species types to allow in the system
beta Inverse temperature (1/kT)
box Box dimensions [x, y, z]
mu Chemical potential of each species
maxSpecies Maximum number of each species to allow in the system
Mtot Total number of expanded ensemble states
energyHistDelta Bin width of energy histogram at each Ntot (optional, default = 10.0)
max_order Maximum order to record correlations to (default = 2)
Definition at line 431 of file system.cpp.
References atoms, beta(), box(), crossoverTotalStepCounter, lnF_end, lnF_start, maxSpecies(), minSpecies(), mu(), nCrossoverVisits, nSpecies(), numSpecies, ppot, restartFromTMMC, restartFromTMMCFile, restartFromWALA, restartFromWALAFile, speciesBarriers, SYS_FAILURE, tmmcTotalStepCounter, totalTMMCSweeps, useTMMC, useWALA, wala_g, wala_s, walaTotalStepCounter, and wlSweepSize.
                                                                                                                                                                                                                                                                              {
    if ((box.size() != 3) || (nSpecies != mu.size()) || (maxSpecies.size() != nSpecies)) {
        throw customException ("Invalid system initialization parameters");
        exit(SYS_FAILURE);
    } else {
        nSpecies_ = nSpecies;
        maxSpecies_ = maxSpecies;
        minSpecies_ = minSpecies;
        box_ = box;
        mu_ = mu;
        beta_ = beta;
    }
    lnF_start = 1.0; // default for lnF_start
    lnF_end = 2.0e-18; // default for lnF_end
    toggleKE_ = false; //default, do NOT adjust energy by kinetic contribution of 3/2kT per atom (just record PE)
    totalTMMCSweeps = 0;
    wlSweepSize = 0;
    wala_g = 0.5;
    wala_s = 0.8;
    nCrossoverVisits = 5;
    walaTotalStepCounter = 0;
    crossoverTotalStepCounter = 0;
    tmmcTotalStepCounter = 0;
    if (max_order < 1){
        throw customException ("max_order must be >= 1");
    }
    max_order_ = max_order;
    if (energyHistDelta <= 0) {
        throw customException ("energyHistDelta must be > 0");
    }
    energyHistDelta_ = energyHistDelta;
    for (unsigned int i = 0; i < 3; ++i) {
        if (box_[i] <= 0) {
            throw customException ("Box dimensions must be > 0");
        }
    }
    if (Mtot < 1) {
        throw customException ("Total fractional states for expanded ensemble must be >= 1");
    }
    Mtot_ = Mtot;
    Mcurrent_ = 0; // always start from fully inserted state
    try {
        ppot.resize(nSpecies);
    } catch (std::exception &e) {
        throw customException (e.what());
    }
    for (unsigned int i = 0; i < nSpecies; ++i) {
        try {
            ppot[i].resize(nSpecies);
        } catch (std::exception &e) {
            throw customException (e.what());
        }
    }
    try {
        mass_.resize(nSpecies, 1.0);
    } catch (std::exception &e) {
        throw customException (e.what());
    }
    try {
        ppotSet_.resize(nSpecies);
    } catch (std::exception &e) {
        throw customException (e.what());
    }
    for (unsigned int i = 0; i < nSpecies; ++i) {
        try {
            ppotSet_[i].resize(nSpecies, false);
        } catch (std::exception &e) {
            throw customException (e.what());
        }
    }
    // Wall potentials for each species, if there are any?
    try {
        speciesBarriers.resize(nSpecies);
    } catch (std::exception &e) {
        throw customException (e.what());
    }
    // Prepare vectors and matrices for cell lists.
    // It is crucial to reserve the correct number of cellLists in advance
    // since cellListsByPairType uses the addresses of cellLists. Otherwise,
    // if dynamic memory reallocation takes place, the pointers do not
    // correspond to initial values anymore, causing the simulation to crash.
    cellLists_.reserve(nSpecies_*nSpecies_);
    try {
        useCellList_.resize(nSpecies);
        cellListsByPairType_.resize(nSpecies);
    } catch (std::exception &e) {
        throw customException (e.what());
    }
    for (unsigned int i = 0; i < nSpecies; ++i) {
        try {
            useCellList_[i].resize(nSpecies);
            cellListsByPairType_[i].assign(nSpecies, NULL);
        } catch (std::exception &e) {
            throw customException (e.what());
        }
    }
    totN_ = 0;
        try {
        numSpecies.resize(nSpecies, 0);
    } catch (std::exception &e) {
        throw customException (e.what());
    }
    try {
        atoms.resize(nSpecies);
    } catch (std::exception &e) {
        throw customException (e.what());
    }
    for (unsigned int i = 0; i < nSpecies; ++i) {
        if (minSpecies_[i] < 0) {
            throw customException ("Min species < 0");
        }
        if (maxSpecies_[i] < minSpecies_[i]) {
            throw customException ("Max species < Min species");
        }
        try {
            atoms[i].resize(maxSpecies_[i], atom());
        } catch (std::exception &e) {
            throw customException (e.what());
        }
    }
    energy_ = 0.0;
    useTMMC = false;
    useWALA = false;
    totNBounds_.resize(2, 0);
    for (unsigned int i = 0; i < nSpecies_; ++i) {
        totNBounds_[0] += minSpecies_[i];
        totNBounds_[1] += maxSpecies_[i];
    }
    // allocate space for average U storage matrix - Shen and Errington method implies this size is always the same for
    // both single and multicomponent mixtures
    long long int size = totNBounds_[1] - totNBounds_[0] + 1;
    energyHistogram_lb_.resize(size, -5.0);
    energyHistogram_ub_.resize(size, 5.0);
    for (unsigned int i = 0; i < size; ++i) {
        energyHistogram_lb_[i] = -5.0;
        energyHistogram_ub_[i] = 5.0;
        try {
            dynamic_one_dim_histogram dummyHist (energyHistogram_lb_[i], energyHistogram_ub_[i], energyHistDelta_);
            energyHistogram_.resize(i+1, dummyHist);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory for energy histogram for each Ntot");
        }
    }
    pkHistogram_.resize(0);
    dynamic_one_dim_histogram dummyPkHist (0.0, totNBounds_[1], 1.0);
    try {
        std::vector < dynamic_one_dim_histogram > tmp (totNBounds_[1]-totNBounds_[0]+1, dummyPkHist);
        pkHistogram_.resize(nSpecies_, tmp);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory for particle histogram for each Ntot");
    }
    // initialize moments
    std::vector < double > lbn (6,0), ubn(6,0);
    std::vector < long long unsigned int > nbn (6,0);
    ubn[0] = nSpecies_-1;
    ubn[1] = max_order_;
    ubn[2] = nSpecies_-1;
    ubn[3] = max_order_;
    ubn[4] = max_order_;
    ubn[5] = totNBounds_[1]-totNBounds_[0];
    nbn[0] = nSpecies_;
    nbn[1] = max_order_+1;
    nbn[2] = nSpecies_;
    nbn[3] = max_order_+1;
    nbn[4] = max_order_+1;
    nbn[5] = size;
    histogram hnn (lbn, ubn, nbn);
    extensive_moments_ = hnn;
    restartFromWALA = false;
    restartFromTMMC = false;
    restartFromWALAFile = "";
    restartFromTMMCFile = "";
}
simSystem::~simSystem ()
Definition at line 410 of file system.cpp.
References tmmcBias, useTMMC, useWALA, and wlBias.
                       {
    if (useTMMC) {
        delete tmmcBias;
    }
    if (useWALA) {
        delete wlBias;
    }
}
Member Function Documentation
bool simSystem::addKECorrection () [inline]
Definition at line 32 of file system.h.
Referenced by initialize(), deleteParticle::make(), insertParticle::make(), and setConfig().
{ return toggleKE_; }
void simSystem::addPotential (const intspec1, const intspec2, const std::stringppot_name, const std::vector< double > &params, const booluseCellList = false, const std::stringtabFile = '')
Add a pair potential to the system which governs the pair (spec1, spec2). However, it only stores the pointer so the object must be fixed in memory somewhere else throughout the simulation.
Parameters:
spec1 Species index 1 (>= 0)
spec2 Species index 2 (>= 0)
ppot_name Name of pair potential
params Vector of parameters which define pair potential
bool Optional argument of whether or not to build and maintain a cell list for this pair (spec1, spec2) (default=false)
tabFile Optional argument use for tabulated potentials, this is the file to load from (default='')
Definition at line 1226 of file system.cpp.
References numToStr(), ppot, sendErr(), and sendMsg().
Referenced by setPairPotentials().
                                                                                                                                                                              {
    if (spec1 >= nSpecies_ || spec1 < 0) {
        throw customException ("Trying to define pair potential for species (1) that does not exist yet/is invalid");
    }
    if (spec2 >= nSpecies_ || spec2 < 0) {
        throw customException ("Trying to define pair potential for species (2) that does not exist yet/is invalid");
    }
    if (ppot_name == "square_well") {
        try {
            auto pp1 = std::make_shared < squareWell > ();
            pp1->setParameters(params);
            ppot[spec1][spec2] = pp1;
            auto pp2 = std::make_shared < squareWell > ();
            pp2->setParameters(params);
            ppot[spec2][spec1] = pp2;
        } catch (std::exception &ex) {
            throw customException(ex.what());
        }
    } else if (ppot_name == "lennard_jones") {
        try {
            auto pp1 = std::make_shared < lennardJones > ();
            pp1->setParameters(params);
            ppot[spec1][spec2] = pp1;
            auto pp2 = std::make_shared < lennardJones > ();
            pp2->setParameters(params);
            ppot[spec2][spec1] = pp2;
        } catch (std::exception &ex) {
            throw customException(ex.what());
        }
    } else if (ppot_name == "fs_lennard_jones") {
        try {
            auto pp1 = std::make_shared < fsLennardJones > ();
            pp1->setParameters(params);
            ppot[spec1][spec2] = pp1;
            auto pp2 = std::make_shared < fsLennardJones > ();
            pp2->setParameters(params);
            ppot[spec2][spec1] = pp2;
        } catch (std::exception &ex) {
            throw customException(ex.what());
        }
    } else if (ppot_name == "hard_sphere") {
        try {
            auto pp1 = std::make_shared < hardCore > ();
            pp1->setParameters(params);
            ppot[spec1][spec2] = pp1;
            auto pp2 = std::make_shared < hardCore > ();
            pp2->setParameters(params);
            ppot[spec2][spec1] = pp2;
        } catch (std::exception &ex) {
            throw customException(ex.what());
        }
    } else if (ppot_name == "tabulated") {
        try {
            auto pp1 = std::make_shared < tabulated > ();
            pp1->setParameters(params);
            pp1->loadPotential(tabFile);
            ppot[spec1][spec2] = pp1;
            auto pp2 = std::make_shared < tabulated > ();
            pp2->setParameters(params);
            pp2->loadPotential(tabFile);
            ppot[spec2][spec1] = pp2;
        } catch (std::exception &ex) {
            throw customException(ex.what());
        }
    } else {
        throw customException("Unrecognized pair potential name for species "+numToStr(spec1)+", "+numToStr(spec2));
    }
    ppotSet_[spec1][spec2] = true;
    ppotSet_[spec2][spec1] = true;
    if (useCellList) {
        sendMsg("Setting up cell list for interactions between type "+numToStr(spec1)+" and "+numToStr(spec2));
        // Add creation of cell lists
        if ((ppot[spec1][spec2]->rcut() > box_[0]/3.0) || (ppot[spec1][spec2]->rcut() > box_[1]/3.0) || (ppot[spec1][spec2] ->rcut() > box_[2]/3.0)) {
            sendErr("Cutoff ("+numToStr(ppot[spec1][spec2]->rcut())+") larger than 1.0/3.0 boxsize, disabling cell lists for this interaction");
            useCellList_[spec1][spec2] = false;
            useCellList_[spec2][spec1] = false;
        } else {
            sendMsg("Creating Cell list with r_cut = "+numToStr(ppot[spec1][spec2]->rcut()));
            useCellList_[spec1][spec2] = true;
            useCellList_[spec2][spec1] = true;
            std::vector <atom*> dummyList(0);
            if (cellListsByPairType_[spec1][spec2] == NULL) {
                cellLists_.push_back(cellList(box_, ppot[spec1][spec2]->rcut(), dummyList));
                cellListsByPairType_[spec1][spec2] = &cellLists_[cellLists_.size()-1];
            }
            if (cellListsByPairType_[spec2][spec1] == NULL) {
                cellLists_.push_back(cellList(box_, ppot[spec2][spec1]->rcut(), dummyList));
                cellListsByPairType_[spec2][spec1] = &cellLists_[cellLists_.size()-1];
            }
        }
    } else {
        useCellList_[spec1][spec2] = false;
        useCellList_[spec2][spec1] = false;
    }
}
const double simSystem::beta () [inline]
Return 1/kT.
Definition at line 87 of file system.h.
Referenced by aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), and simSystem().
const std::vector< double > simSystem::box () [inline]
Return the system box dimensions.
Definition at line 112 of file system.h.
Referenced by checkBounds(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), setBarriers(), setConfig(), setMoves(), and simSystem().
void simSystem::checkEnergyHistogramBounds ()
Monitor the energy histogram bounds at each Ntot.
Definition at line 857 of file system.cpp.
Referenced by performCrossover(), and performWALA().
                                            {
    if (totN_ >= totNBounds_[0] && totN_ <= totNBounds_[1]) {
        const int address = totN_-totNBounds_[0];
        energyHistogram_lb_[address] = std::min(energyHistogram_lb_[address], energy_);
        energyHistogram_ub_[address] = std::max(energyHistogram_ub_[address], energy_);
    }
}
void simSystem::decrementMState ()
Decrease the expanded ensemble state of the system by 1. Accounts for the periodicity of [0, M)
Definition at line 16 of file system.cpp.
                                 {
    Mcurrent_--;
    if (Mcurrent_ < 0) {
        Mcurrent_ += Mtot_;
    }
}
void simSystem::deleteAtom (const inttypeIndex, const intatomIndex, booloverride = false)
Delete an atom from the system. Does all the bookkeepping behind the scenes.
Parameters:
typeIndex What type the atom is (>= 0)
atomIndex Which atom index of type typeIndex to destroy (>= 0)
Optional override command which allows the system to delete a particle even it goes below the minimum allowed. E.g. during a swap move.
Definition at line 241 of file system.cpp.
References atoms, atom::mState, numSpecies, and cellList::swapAndDeleteParticle().
Referenced by deleteParticle::make(), swapParticles::make(), and readConfig().
                                                                                   {
    if (typeIndex < nSpecies_ && typeIndex >= 0) {
        if ((numSpecies[typeIndex] > minSpecies_[typeIndex]) || ((numSpecies[typeIndex] == minSpecies_[typeIndex]) && (Mcurrent_ > 0)) || override) {
            if (override) {
                // doing a swap move
                if (Mtot_ > 1) {
                    // expanded ensemble and not necessarily deleting the partial atom
                    int end = numSpecies[typeIndex] - 1;
                    if (fractionalAtomType_ == typeIndex && Mcurrent_ > 0) {
                        // we are deleting a particle which has to watch out for the partial atom
                        end++;
                    }
                    if (atoms[typeIndex][atomIndex].mState == 0) {
                        // if we are removing a "full" particle, have to decrement Ntot, else not
                        numSpecies[typeIndex]--;
                        totN_--;
                    } else {
                        // but if removing the partial particle, M is affected
                        Mcurrent_ = 0; // regardless of how M was originally, the partial particle is now "entirely" gone
                    }
                    bool replace = false;
                    if (&atoms[typeIndex][end] == fractionalAtom_) {
                        // then the fractional atom is about to be used to replace a "full" one
                        replace = true;
                    }
                    // have to entirely remove the particle
                    for (unsigned int i = 0; i < nSpecies_; ++i) {
                        if (useCellList_[typeIndex][i]) {
                            cellList* cl = cellListsByPairType_[typeIndex][i];
                            cl->swapAndDeleteParticle(&atoms[typeIndex][atomIndex], &atoms[typeIndex][end]);
                        }
                    }
                    atoms[typeIndex][atomIndex] = atoms[typeIndex][end]; // "replacement" operation
                    if (replace) {
                        fractionalAtom_ = &atoms[typeIndex][atomIndex]; // update the pointer if necessary
                    }
                } else {
                    // no expanded ensemble, just delete particle from appropriate cell list
                    for (unsigned int i = 0; i < nSpecies_; ++i) {
                        if (useCellList_[typeIndex][i]) {
                            cellList* cl = cellListsByPairType_[typeIndex][i];
                            cl->swapAndDeleteParticle(&atoms[typeIndex][atomIndex], &atoms[typeIndex][numSpecies[typeIndex] - 1]);
                        }
                    }
                    atoms[typeIndex][atomIndex] = atoms[typeIndex][numSpecies[typeIndex] - 1]; // "replacement" operation
                    numSpecies[typeIndex]--;
                    totN_--;
                }
            } else {
                // not doing a swap move, just a "regular" deletion
                if (Mtot_ > 1) {
                    // expanded ensemble
                    if (Mcurrent_ == 1) {
                        // when we delete this atom, it is entirely gone
                        // first ensure the system pointer is correct if currently a partially inserted atom
                        if (fractionalAtom_ != &atoms[typeIndex][atomIndex] || typeIndex != fractionalAtomType_) {
                            throw customException ("Fractional atom pointer does not point to atom belived to be inserted");
                        }
                        // decrement expanded state
                        fractionalAtom_->mState = 0;
                        Mcurrent_ = 0;
                        // since deleting partial particle, do not update Ntot, etc.
                        // however, do have to remove from cellLists
                        int end = numSpecies[typeIndex]; // includes space for the partially inserted one currently in cellList
                        for (unsigned int i = 0; i < nSpecies_; ++i) {
                            if (useCellList_[typeIndex][i]) {
                                cellList* cl = cellListsByPairType_[typeIndex][i];
                                cl->swapAndDeleteParticle(&atoms[typeIndex][atomIndex], &atoms[typeIndex][end]);
                            }
                        }
                        atoms[typeIndex][atomIndex] = atoms[typeIndex][end]; // "replacement" operation
                    } else if (Mcurrent_ == 0) {
                        // have to decrement Ntot, but keep in cell lists
                        numSpecies[typeIndex]--;
                        totN_--;
                        // this is a new fractional atom
                        fractionalAtom_ = &atoms[typeIndex][atomIndex];
                        fractionalAtomType_ = typeIndex;
                        // decrement expanded state
                        fractionalAtom_->mState = Mtot_-1;
                        Mcurrent_ = Mtot_-1;
                    } else {
                        // further deleting an atom that already partially exists in the system, but remains in cell lists
                        // first ensure the system pointer is correct if currently a partially inserted atom
                        if (fractionalAtom_ != &atoms[typeIndex][atomIndex] || typeIndex != fractionalAtomType_) {
                            throw customException ("Fractional atom pointer does not point to atom belived to be inserted");
                        }
                        // decrement expanded state
                        fractionalAtom_->mState -= 1;
                        Mcurrent_ -= 1;
                    }
                } else {
                    // no expanded ensemble, just delete particle from appropriate cell list
                    for (unsigned int i = 0; i < nSpecies_; ++i) {
                        if (useCellList_[typeIndex][i]) {
                            cellList* cl = cellListsByPairType_[typeIndex][i];
                            cl->swapAndDeleteParticle(&atoms[typeIndex][atomIndex], &atoms[typeIndex][numSpecies[typeIndex] - 1]);
                        }
                    }
                    atoms[typeIndex][atomIndex] = atoms[typeIndex][numSpecies[typeIndex] - 1]; // "replacement" operation
                    numSpecies[typeIndex]--;
                    totN_--;
                }
            }
        } else {
            throw customException ("System going below minimum allowable number of atoms, cannot delete an atom of type index "+std::to_string(typeIndex));
        }
    } else {
        throw customException ("That species index does not exist, cannot delete an atom");
    }
}
const double simSystem::energy () [inline]
Return the system's instantaneous energy.
Definition at line 84 of file system.h.
Referenced by performGCMC(), and sanityChecks().
const std::vector< double > simSystem::extMomCounter () [inline]
Get counter for extensive moments needed for restarting system from a checkpoint.
Definition at line 111 of file system.h.
References histogram::getCounter().
Referenced by checkpoint::dump().
const int simSystem::getCurrentM () [inline]
Return the system's current expanded ensemble fractional state.
Definition at line 80 of file system.h.
Referenced by calculateBias(), aggVolBias3::make(), translateParticle::make(), deleteParticle::make(), insertParticle::make(), swapParticles::make(), moves::makeMove(), performCrossover(), performGCMC(), performTMMC(), performWALA(), and sanityChecks().
std::vector< double > simSystem::getELB () [inline]
Returns current tally of energy min at each Ntot for checkpointing.
Definition at line 113 of file system.h.
Referenced by checkpoint::dump().
std::vector< double > simSystem::getEUB () [inline]
Returns current tally of energy max at each Ntot for checkpointing.
Definition at line 114 of file system.h.
Referenced by checkpoint::dump().
atom* simSystem::getFractionalAtom () [inline]
Returns a pointer the atom in the system that is currently only fractionally inserted/deleted.
Definition at line 118 of file system.h.
Referenced by deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), and sanityChecks().
const int simSystem::getFractionalAtomType () [inline]
Return the atom type of the fractional atom.
Definition at line 82 of file system.h.
Referenced by aggVolBias3::make(), translateParticle::make(), swapParticles::make(), moves::makeMove(), and sanityChecks().
const int simSystem::getMaxOrder () [inline]
Return the max order the extensive moments are being stored out to.
Definition at line 78 of file system.h.
Referenced by restartExtMoments(), and setConfig().
std::vector< atom * > simSystem::getNeighborAtoms (const unsigned inttypeIndexA, const unsigned inttypeIndexB, atom *_atom)
Return the list of neighbors of type A, around a particle of type B which is passed.
Parameters:
typeIndexA Index of first atom type
typeIndexB Index of second atom type
atom Pointer to atom to find neighbors around
Returns:
neighbor_list
Definition at line 1501 of file system.cpp.
References atoms, cellList::calcIndex(), cellList::cells, cellList::neighbours, numSpecies, and atom::pos.
Referenced by deleteParticle::make(), translateParticle::make(), swapParticles::make(), and insertParticle::make().
                                                                                                                         {
    std::vector < atom* > neighbors;
    int end = numSpecies[typeIndexA];
    if (Mcurrent_ > 0 && typeIndexA == fractionalAtomType_) {
        // account for partial atom too
        end++;
    }
    neighbors.reserve(end);
    // if no cell lists are defined for this interaction, return all particles
    if (!useCellList_[typeIndexA][typeIndexB]) {
        for (unsigned int i = 0; i < end; ++i) {
            if (_atom != &atoms[typeIndexA][i]) { // watch out for self in case typeA = typeB
                neighbors.push_back(&atoms[typeIndexA][i]);
            }
        }
    } else if (useCellList_[typeIndexA][typeIndexB]) {
        cellList* cl = cellListsByPairType_[typeIndexA][typeIndexB];
        const unsigned int cellIndex = cl->calcIndex(_atom->pos[0], _atom->pos[1], _atom->pos[2]);
        // loop over own cell
        for (unsigned int i = 0; i < cl->cells[cellIndex].size(); ++i) {
            if (_atom != cl->cells[cellIndex][i]) {
                neighbors.push_back(cl->cells[cellIndex][i]);
            }
        }
        // loop over neighboring cells
        for (unsigned int i = 0; i < cl->neighbours[cellIndex].size(); ++i) {
            const unsigned int neighborCellIndex = cl->neighbours[cellIndex][i];
            for (unsigned int j = 0; j < cl->cells[neighborCellIndex].size(); ++j) {
                if (_atom != cl->cells[neighborCellIndex][j]) {
                    neighbors.push_back(cl->cells[neighborCellIndex][j]);
                }
            }
        }
    }
    return neighbors;
}
tmmc * simSystem::getTMMCBias ()
Return pointer to the TMMC bias. Return a pointer to the TMMC biasing object, if using TMMC, else throws an exception.
Returns:
tmmc Pointer to TMMC biasing object being used.
Definition at line 1704 of file system.cpp.
References tmmcBias, and useTMMC.
Referenced by checkpoint::dump(), checkpoint::load(), performCrossover(), and performTMMC().
                              {
    if (useTMMC == true) {
        return tmmcBias;
    } else {
        throw customException ("Not using TMMC");
    }
}
const int simSystem::getTotalM () [inline]
Return the total number of fractional states available to species in the expanded ensemble.
Definition at line 81 of file system.h.
Referenced by checkpoint::load(), deleteParticle::make(), insertParticle::make(), moves::makeMove(), performCrossover(), performTMMC(), performWALA(), sanityChecks(), setBarriers(), setConfig(), setMoves(), and setPairPotentials().
const int simSystem::getTotN () [inline]
Return a sum of the total number of atoms currently in the system.
Definition at line 77 of file system.h.
Referenced by calculateBias(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), insertParticle::make(), swapParticles::make(), and sanityChecks().
wala * simSystem::getWALABias ()
Return pointer to the Wang-Landau bias. Return a pointer to the TMMC biasing object, if using TMMC, else throws an exception.
Returns:
wala Pointer to WALA biasing object being used.
Definition at line 1717 of file system.cpp.
References useWALA, and wlBias.
Referenced by checkpoint::dump(), checkpoint::load(), aggVolBias3::make(), translateParticle::make(), deleteParticle::make(), swapParticles::make(), insertParticle::make(), performCrossover(), and performWALA().
                              {
    if (useWALA == true) {
        return wlBias;
    } else {
        throw customException ("Not using WALA");
    }
}
void simSystem::incrementEnergy (const doubledU) [inline]
Increment the system's energy.
Definition at line 34 of file system.h.
Referenced by aggVolBias3::make(), translateParticle::make(), deleteParticle::make(), insertParticle::make(), and swapParticles::make().
void simSystem::incrementMState ()
Increase the expanded ensemble state of the system by 1. Accounts for the periodicity of [0, M)
Definition at line 6 of file system.cpp.
                                 {
    Mcurrent_++;
    if (Mcurrent_ == Mtot_) {
        Mcurrent_ = 0;
    }
}
void simSystem::insertAtom (const inttypeIndex, atom *newAtom, booloverride = false)
Insert an atom into the system. Does all the bookkeepping behind the scenes.
Parameters:
typeIndex What type the atom is (>= 0)
newAtom Pointer to new atom. A copy is stored in the system so the original may be destroyed.
override Override command that prevents the expanded ensemble state from being changed. Used during swap moves where 'insertions' are temporary.
Definition at line 140 of file system.cpp.
References atoms, cellList::insertParticle(), atom::mState, and numSpecies.
Referenced by insertParticle::make(), swapParticles::make(), and readConfig().
                                                                             {
    if (typeIndex < nSpecies_ && typeIndex >= 0) {
        if (numSpecies[typeIndex] < maxSpecies_[typeIndex]) {
            if (Mtot_ > 1 && !override) {
                // expanded ensemble behavior, "normal" insertion and deletion
                if (Mcurrent_ > 0) { // further inserting an atom that already partially exists in the system
                    // ensure the system pointer is correct if currently a partially inserted atom
                    if (fractionalAtom_ != newAtom || typeIndex != fractionalAtomType_) {
                        throw customException ("Fractional atom pointer does not point to atom believed to be inserted");
                    }
                    // increment expanded state
                    fractionalAtom_->mState++;
                    Mcurrent_++;
                    // check if now fully inserted
                    if (fractionalAtom_->mState == Mtot_) {
                        fractionalAtom_->mState = 0;
                        Mcurrent_ = 0;
                        totN_++;
                        numSpecies[typeIndex]++;
                    }
                } else {
                    // Inserting a new atom for the first time
                    atoms[typeIndex][numSpecies[typeIndex]] = (*newAtom);
                    // Assign fractional atom
                    fractionalAtom_ = &atoms[typeIndex][numSpecies[typeIndex]];
                    fractionalAtomType_ = typeIndex;
                    // Increment expanded state
                    fractionalAtom_->mState = 1;
                    Mcurrent_ = 1;
                    // Add particle into appropriate cell lists
                    for (unsigned int i = 0; i < nSpecies_; ++i) {
                        if (useCellList_[typeIndex][i]) {
                            cellList* cl = cellListsByPairType_[typeIndex][i];
                            cl->insertParticle(&atoms[typeIndex][numSpecies[typeIndex]]); // numSpecies[typeIndex] is the number of fully inserted ones, this partially inserted one comes after that
                        }
                    }
                }
            } else if (Mtot_ > 1 && override) {
                // Expanded ensemble behavior, but now amidst a "swap move" rather than an actual insertion or deletion.
                // For this, insertions involve just putting the atom "back" into the system / cellLists after being artificially completely removed
                // Ensure we insert at the proper "end"
                int end = numSpecies[typeIndex];
                if (Mcurrent_ > 0 && typeIndex == fractionalAtomType_ && newAtom->mState == 0) {
                    end++; // Insert after the partially inserted one since newAtom is NOT the partial one
                }
                atoms[typeIndex][end] = (*newAtom);
                // If we just added a partially inserted/deleted particle back to the system, need to update the pointer
                if (atoms[typeIndex][end].mState != 0) {
                    fractionalAtom_ = &atoms[typeIndex][end];
                    fractionalAtomType_ = typeIndex;
                    // Set the system's mState back to that of the atom just inserted, iff it was the partial one
                    Mcurrent_ = atoms[typeIndex][end].mState;
                } else {
                    totN_++; // We just added a "full" atom
                    numSpecies[typeIndex]++; // We just added a "full" atom
                }
                // Put newAtom into the cell lists whatever its state
                for (unsigned int i = 0; i < nSpecies_; ++i) {
                    if (useCellList_[typeIndex][i]) {
                        cellList* cl = cellListsByPairType_[typeIndex][i];
                        cl->insertParticle(&atoms[typeIndex][end]);
                    }
                }
            } else {
                // Direct insertion (no expanded ensemble)
                atoms[typeIndex][numSpecies[typeIndex]] = (*newAtom);
                numSpecies[typeIndex]++;
                totN_++;
                // Add particle into appropriate cell lists
                for (unsigned int i = 0; i < nSpecies_; ++i) {
                    if (useCellList_[typeIndex][i]) {
                        cellList* cl = cellListsByPairType_[typeIndex][i];
                        cl->insertParticle(&atoms[typeIndex][numSpecies[typeIndex] - 1]);
                    }
                }
            }
        } else {
            throw customException ("Reached upper bound, cannot insert an atom of type index "+std::to_string(typeIndex));
        }
    } else {
        throw customException ("That species index does not exist, cannot insert an atom");
    }
}
const double simSystem::mass (const intindex) [inline]
Return the mass of a given species' index.
Definition at line 89 of file system.h.
Referenced by deleteParticle::make(), and insertParticle::make().
const int simSystem::maxSpecies (const intindex)
Returns the absolute maximum number of a given species type allowed in the system.
Parameters:
index Species index to query
Returns:
maxSpecies Maximum number of them allowed
Definition at line 1670 of file system.cpp.
Referenced by insertParticle::make(), and simSystem().
                                                {
    if (maxSpecies_.begin() == maxSpecies_.end()) {
            throw customException ("No species in the system, cannot report a maximum");
        }
        if (maxSpecies_.size() <= index) {
            throw customException ("System does not contain that species, cannot report a maximum");
        } else {
            return maxSpecies_[index];
        }
}
const int simSystem::minSpecies (const intindex)
Returns the absolute minimum number of a given species type allowed in the system.
Parameters:
index Species index to query
Returns:
minSpecies Minimum number of them allowed
Definition at line 1688 of file system.cpp.
Referenced by deleteParticle::make(), and simSystem().
                                                {
    if (minSpecies_.begin() == minSpecies_.end()) {
            throw customException ("No species in the system, cannot report a minimum");
        }
        if (minSpecies_.size() <= index) {
            throw customException ("System does not contain that species, cannot report a minimum");
        } else {
            return minSpecies_[index];
        }
}
const double simSystem::mu (const intindex) [inline]
Return the chemical potential for a given species' index.
Definition at line 88 of file system.h.
Referenced by deleteParticle::make(), insertParticle::make(), and simSystem().
const int simSystem::nSpecies () [inline]
Return the number of different species in the system.
Definition at line 72 of file system.h.
Referenced by checkBounds(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), insertParticle::make(), swapParticles::make(), performGCMC(), sanityChecks(), setBarriers(), setConfig(), setMoves(), setPairPotentials(), and simSystem().
bool simSystem::potentialIsSet (const intspec1, const intspec2) [inline]
Boolean which returns whether or not a pair has had its potential specified by the user yet.
Definition at line 70 of file system.h.
Referenced by checkBounds(), and readConfig().
void simSystem::printEnergyHistogram (const std::stringfileName, const boolnormalize = true)
Print the (normalized by default) energy histogram for each Ntot. Refines bounds before each print.
Parameters:
fileName Prefix of the filename to load from
normalize Whether or not to normalize the histogram (default=true)
Definition at line 915 of file system.cpp.
Referenced by checkpoint::dump(), and performTMMC().
                                                                                    {
    std::ofstream of;
    std::string name = fileName+".dat";
    of.open(name.c_str(), std::ofstream::out);
    of << "# <P(U)> as a function of N_tot." << std::endl;
    of << "# number_of_species: " << nSpecies_ << std::endl;
    of << "# species_total_upper_bound: " << totNBounds_[1] << std::endl;
    of << "# species_total_lower_bound: " << totNBounds_[0] << std::endl;
    double V = box_[0]*box_[1]*box_[2];
    of << "# volume: " << std::setprecision(15) << V << std::endl;
    of << "# Bin widths for each" << std::endl;
    for (std::vector < dynamic_one_dim_histogram >::iterator it = energyHistogram_.begin(); it != energyHistogram_.end(); ++it) {
        of << it->get_delta() << "\t";
    }
    of << std::endl;
    of << "# Bin lower bound for each" << std::endl;
    for (std::vector < dynamic_one_dim_histogram >::iterator it = energyHistogram_.begin(); it != energyHistogram_.end(); ++it) {
        of << it->get_lb() << "\t";
    }
    of << std::endl;
    of << "# Bin upper bound for each" << std::endl;
    for (std::vector < dynamic_one_dim_histogram >::iterator it = energyHistogram_.begin(); it != energyHistogram_.end(); ++it) {
        of << it->get_ub() << "\t";
    }
    of << std::endl;
    if (normalize) {
        of << "# Normalized histogram for each" << std::endl;
        for (std::vector < dynamic_one_dim_histogram >::iterator it = energyHistogram_.begin(); it != energyHistogram_.end(); ++it) {
            std::deque <double> h = it->get_hist();
            double sum = 0.0;
            for (std::deque <double>::iterator it2 = h.begin(); it2 != h.end(); ++it2) {
                sum += *it2;
            }
            for (std::deque <double>::iterator it2 = h.begin(); it2 != h.end(); ++it2) {
                of << std::setprecision(15) << *it2/sum << "\t";
            }
            of << std::endl;
        }
    } else {
        of << "# Unnormalized histogram for each" << std::endl;
        for (std::vector < dynamic_one_dim_histogram >::iterator it = energyHistogram_.begin(); it != energyHistogram_.end(); ++it) {
            std::deque <double> h = it->get_hist();
            for (std::deque <double>::iterator it2 = h.begin(); it2 != h.end(); ++it2) {
                of << std::setprecision(15) << *it2 << "\t";
            }
            of << std::endl;
        }
    }
    of.close();
}
void simSystem::printExtMoments (const std::stringfileName, const boolnormalize = true)
Print the (normalized by default) extensive energy histogram for each Ntot.
Parameters:
fileName Name of the file to print to
normalize Whether or not to normalize the histogram (default=true)
Definition at line 661 of file system.cpp.
References histogram::getAddress(), histogram::getCounter(), and histogram::getRawHistogram().
Referenced by checkpoint::dump(), and performTMMC().
                                                                               {
    std::ofstream of;
    std::string name = fileName+".dat";
    of.open(name.c_str(), std::ofstream::out);
    of << "# <N_i^j*N_k^m*U^p> as a function of N_tot." << std::endl;
    of << "# number_of_species: " << nSpecies_ << std::endl;
    of << "# max_order: " << max_order_ << std::endl;
    of << "# species_total_upper_bound: " << totNBounds_[1] << std::endl;
    of << "# species_total_lower_bound: " << totNBounds_[0] << std::endl;
    double V = box_[0]*box_[1]*box_[2];
    of << "# volume: " << std::setprecision(15) << V << std::endl;
    of << "#\tN_tot\t";
    for (unsigned int i = 0; i < nSpecies_; ++i) {
        for (unsigned int j = 0; j <= max_order_; ++j) {
            for (unsigned int k = 0; k < nSpecies_; ++k) {
                for (unsigned int m = 0; m <= max_order_; ++m) {
                    for (unsigned int p = 0; p <= max_order_; ++p) {
                        of << "N_"+std::to_string(i+1)+"^"+std::to_string(j)+"*N_"+std::to_string(k+1)+"^"+std::to_string(m)+"*U^"+std::to_string(p)+"\t";
                    }
                }
            }
        }
    }
    of << std::endl;
    std::vector <double> h = extensive_moments_.getRawHistogram ();
    std::vector <double> ctr = extensive_moments_.getCounter ();
    std::vector <double> coords (6,0);
    long unsigned int idx = 0;
    if (normalize) {
        for (unsigned int n = 0; n < totNBounds_[1]-totNBounds_[0]+1; ++n) {
            of << n+totNBounds_[0] << "\t";
            coords[5] = n;
            for (unsigned int i = 0; i < nSpecies_; ++i) {
                coords[0] = i;
                for (unsigned int j = 0; j <= max_order_; ++j) {
                    coords[1] = j;
                    for (unsigned int k = 0; k < nSpecies_; ++k) {
                        coords[2] = k;
                        for (unsigned int m = 0; m <= max_order_; ++m) {
                            coords[3] = m;
                            for (unsigned int p = 0; p <= max_order_; ++p) {
                                coords[4] = p;
                                idx = extensive_moments_.getAddress(coords);
                                of << std::setprecision(15) << h[idx]/ctr[idx] << "\t";
                            }
                        }
                    }
                }
            }
            of << std::endl;
        }
    } else {
        for (unsigned int n = 0; n < totNBounds_[1]-totNBounds_[0]+1; ++n) {
            of << n+totNBounds_[0] << "\t";
            coords[5] = n;
            for (unsigned int i = 0; i < nSpecies_; ++i) {
                coords[0] = i;
                for (unsigned int j = 0; j <= max_order_; ++j) {
                    coords[1] = j;
                    for (unsigned int k = 0; k < nSpecies_; ++k) {
                        coords[2] = k;
                        for (unsigned int m = 0; m <= max_order_; ++m) {
                            coords[3] = m;
                            for (unsigned int p = 0; p <= max_order_; ++p) {
                                coords[4] = p;
                                idx = extensive_moments_.getAddress(coords);
                                of << std::setprecision(15) << h[idx] << "\t";
                            }
                        }
                    }
                }
            }
            of << std::endl;
        }
    }
    of.close();
}
void simSystem::printPkHistogram (const std::stringfileName, const boolnormalize = true)
Print the (normalized by default) particle number histogram for each Ntot. Refines histograms before each print.
Parameters:
fileName Prefix of filename to print to
normalize Whether or not to normalize the histogram (default=true)
Definition at line 1081 of file system.cpp.
Referenced by checkpoint::dump(), and performTMMC().
                                                                                {
    for (unsigned int i = 0; i < nSpecies_; ++i) {
        std::ofstream of;
        std::string name = fileName+"_"+std::to_string(i+1)+".dat";
        of.open(name.c_str(), std::ofstream::out);
        of << "# <P(N_" << i+1 << ")> as a function of N_tot." << std::endl;
        of << "# number_of_species: " << nSpecies_ << std::endl;
        of << "# species_total_upper_bound: " << totNBounds_[1] << std::endl;
        of << "# species_total_lower_bound: " << totNBounds_[0] << std::endl;
        double V = box_[0]*box_[1]*box_[2];
        of << "# volume: " << std::setprecision(15) << V << std::endl;
        of << "# Bin widths for each species index " << std::endl;
        for (std::vector < dynamic_one_dim_histogram >::iterator it = pkHistogram_[i].begin(); it != pkHistogram_[i].end(); ++it) {
            of << it->get_delta() << "\t";
        }
        of << std::endl;
        of << "# Bin lower bound for each species index " << std::endl;
        for (std::vector < dynamic_one_dim_histogram >::iterator it = pkHistogram_[i].begin(); it != pkHistogram_[i].end(); ++it) {
            of << it->get_lb() << "\t";
        }
        of << std::endl;
        of << "# Bin upper bound for each species index " << std::endl;
        for (std::vector < dynamic_one_dim_histogram >::iterator it = pkHistogram_[i].begin(); it != pkHistogram_[i].end(); ++it) {
            of << it->get_ub() << "\t";
        }
        of << std::endl;
        if (normalize) {
            of << "# Normalized histogram for each species index " << std::endl;
            for (std::vector < dynamic_one_dim_histogram >::iterator it = pkHistogram_[i].begin(); it != pkHistogram_[i].end(); ++it) {
                std::deque <double> h = it->get_hist();
                double sum = 0.0;
                for (std::deque <double>::iterator it2 = h.begin(); it2 != h.end(); ++it2) {
                    sum += *it2;
                }
                for (std::deque <double>::iterator it2 = h.begin(); it2 != h.end(); ++it2) {
                    of << std::setprecision(15) << *it2/sum << "\t";
                }
                of << std::endl;
            }
        } else {
            of << "# Unnormalized histogram for each species index " << std::endl;
            for (std::vector < dynamic_one_dim_histogram >::iterator it = pkHistogram_[i].begin(); it != pkHistogram_[i].end(); ++it) {
                std::deque <double> h = it->get_hist();
                for (std::deque <double>::iterator it2 = h.begin(); it2 != h.end(); ++it2) {
                    of << std::setprecision(15) << *it2 << "\t";
                }
                of << std::endl;
            }
        }
        of.close();
    }
}
void simSystem::printSnapshot (std::stringfilename, std::stringcomment, booloverwrite = true)
Print an XYZ file of the instantaneous system configuration. This can be read in at a later time via estart() function.
Parameters:
filename File to store XYZ coordinates to
comment Comment line for the file
overwrite Flag to overwrite file if it already exists or to append (default = true, overwrite)
Definition at line 1334 of file system.cpp.
References atoms, and numSpecies.
Referenced by checkpoint::dump(), performGCMC(), performTMMC(), and setConfig().
                                                                                    {
    if (overwrite) {
        std::ofstream outfile (filename.c_str(), std::ofstream::trunc);
        int tot = 0;
        for (unsigned int j = 0; j < nSpecies_; ++j) {
            tot += numSpecies[j]; // only count fully inserted species
        }
        outfile << tot << std::endl;
        outfile << comment << std::endl;
        for (unsigned int j = 0; j < nSpecies_; ++j) {
            long long int num = numSpecies[j];
            if (Mcurrent_ > 1 && fractionalAtomType_ == j) {
                num += 1; // account for partially inserted atom
            }
            for (unsigned int i = 0; i < num; ++i) {
                if (atoms[j][i].mState == 0) { // only print fully inserted atoms
                    outfile << j << "\t" << std::setprecision(15) << atoms[j][i].pos[0] << "\t" << std::setprecision(15) << atoms[j][i].pos[1] << "\t" << std::setprecision(15) << atoms[j][i].pos[2] << std::endl;
                }
            }
        }
        outfile.close();
    } else {
        std::ofstream outfile (filename.c_str(), std::ofstream::out | std::ofstream::app);
        int tot = 0;
        for (unsigned int j = 0; j < nSpecies_; ++j) {
            tot += numSpecies[j]; // only count fully inserted species
        }
        outfile << tot << std::endl;
        outfile << comment << std::endl;
        for (unsigned int j = 0; j < nSpecies_; ++j) {
            long long int num = numSpecies[j];
            if (Mcurrent_ > 1 && fractionalAtomType_ == j) {
                num += 1; // account for partially inserted atom
            }
            for (unsigned int i = 0; i < num; ++i) {
                if (atoms[j][i].mState == 0) { // only print fully inserted atoms
                    outfile << j << "\t" << std::setprecision(15) << atoms[j][i].pos[0] << "\t" << std::setprecision(15) << atoms[j][i].pos[1] << "\t" << std::setprecision(15) << atoms[j][i].pos[2] << std::endl;
                }
            }
        }
        outfile.close();
    }
}
void simSystem::readConfig (std::stringfilename)
Read an XYZ file as the system's initial configuration. Note that the number of species, etc. must already be specified in the constructor. Will also reset and calculate the energy from scratch so these potentials should be set before reading in a restart file.
Parameters:
filename File to read XYZ coordinates from
Definition at line 1390 of file system.cpp.
References deleteAtom(), insertAtom(), numSpecies, potentialIsSet(), scratchEnergy(), sendErr(), sendMsg(), SYS_FAILURE, and customException::what().
Referenced by checkpoint::load(), and setConfig().
                                              {
    sendMsg("Reading initial configuration from "+filename);
    std::ifstream infile (filename.c_str());
    if (!infile.is_open()) {
        sendErr("Cannot open "+filename);
        exit(SYS_FAILURE);
    }
    std::string line;
    std::vector < atom > sysatoms;
    std::vector < int > index;
    int natoms = 0;
    int lineIndex = 0;
    while(std::getline(infile,line)) {
        std::stringstream lineStream(line);
        if (lineIndex == 0) {
            lineStream >> natoms;
            index.resize(natoms);
            sysatoms.resize(natoms);
        } else if (lineIndex > 1) {
            lineStream >> index[lineIndex-2] >> sysatoms[lineIndex-2].pos[0] >> sysatoms[lineIndex-2].pos[1] >> sysatoms[lineIndex-2].pos[2];
        }
        lineIndex++;
    }
    infile.close();
    // check if within global bounds
    if (sysatoms.size() > totNBounds_[1] || sysatoms.size() < totNBounds_[0]) {
        throw customException ("Number of particles ("+std::to_string(sysatoms.size())+") in the restart file out of target range ["+std::to_string(totNBounds_[0])+", "+std::to_string(totNBounds_[1])+"]");
    }
    // sort by type
    std::map < int, int > types;
    for (unsigned int j = 0; j < natoms; ++j) {
        if (types.find(index[j]) != types.end()) {
            types[index[j]] += 1;
        } else {
            types[index[j]] = 1;
        }
    }
    int maxType = -1;
    for (std::map < int, int >::iterator it = types.begin(); it != types.end(); ++it) {
        maxType = std::max(maxType, it->first);
        if (it->first < 0 || it->first >= nSpecies_) {
            throw customException ("Restart file corrupted, types out of range");
        }
    }
    // check that pair potentials exist so energy can be calculated
    for (unsigned int i = 0; i < nSpecies_; ++i) {
        for (unsigned int j = 0; j < nSpecies_; ++j) {
            if (!potentialIsSet(i, j)) {
                throw customException("Not all pair potentials are set, so cannot initial from file");
            }
        }
    }
    // empty out the system before adding new atoms in - all atoms "fully inserted" so no partial ones to worry about
    if (Mcurrent_ != 0) {
        throw customException ("System cannot be restarted from "+filename+", for some reason current expanded state != 0");
    }
    for (unsigned int i = 0; i < nSpecies_; ++i) {
        const int ns = numSpecies[i];
        for (int j = ns-1; j >=0; --j) {
            for (int k = 0; k < Mtot_; ++k) {
                deleteAtom (i, j, true);
            }
        }
    }
    if (totN_ != 0) {
        throw customException ("total N = "+std::to_string(totN_)+" != 0 after system supposedly emptied");
    }
    for (unsigned int i = 0; i < nSpecies_; ++i) {
        if (numSpecies[i] != 0) {
            throw customException ("Number of molecules of species #"+std::to_string(i+1)+" = "+std::to_string(numSpecies[i])+" != 0 after system supposedly emptied");
        }
    }
    if (Mcurrent_ != 0) {
        throw customException ("M state != 0 after system supposedly emptied");
    }
    energy_ = 0.0;
    for (unsigned int j = 0; j < sysatoms.size(); ++j) {
        try {
            // "partially" insert each atom so it goes through all the stages
            insertAtom (index[j], &sysatoms[j]);
            for (unsigned int k = 1; k < Mtot_; ++k) {
                insertAtom (index[j], fractionalAtom_); // this will check that within each species own max and min, global bounds handled above
            }
        } catch (customException &ce) {
            std::string a = "Could not initialize system from restart file, ", b = ce.what();
            throw customException (a+b);
        }
    }
    // recalculate system's initial energy
    energy_ = scratchEnergy();
    sendMsg("Successfully loaded initial configuration from "+filename);
}
void simSystem::recordEnergyHistogram ()
Record the energy histogram for the system at a given Ntot. Only records values when N_tot in range of [min, max].
Definition at line 846 of file system.cpp.
Referenced by performTMMC().
                                       {
    // only record if in range (removes equilibration stage to get in this range, if there was any)
    if (totN_ >= totNBounds_[0] && totN_ <= totNBounds_[1]) {
        const int address = totN_-totNBounds_[0];
        energyHistogram_[address].record(energy_);
    }
}
void simSystem::recordExtMoments ()
Record the extensive moment at a given Ntot.
Definition at line 629 of file system.cpp.
References histogram::increment(), and numSpecies.
Referenced by performTMMC().
                                  {
    // only record if in range (removes equilibration stage to get in this range, if there was any)
    if (totN_ >= totNBounds_[0] && totN_ <= totNBounds_[1]) {
        double val = 0.0;
        std::vector < double > coords (6,0);
        coords[5] = totN_-totNBounds_[0];
        for (unsigned int i = 0; i < nSpecies_; ++i) {
            coords[0] = i;
            for (unsigned int j = 0; j <= max_order_; ++j) {
                coords[1] = j;
                for (unsigned int k = 0; k < nSpecies_; ++k) {
                    coords[2] = k;
                    for (unsigned int m = 0; m <= max_order_; ++m) {
                        coords[3] = m;
                        for (unsigned int p = 0; p <= max_order_; ++p) {
                            coords[4] = p;
                            val = pow(numSpecies[i], j)*pow(numSpecies[k], m)*pow(energy_, p);
                            extensive_moments_.increment (coords, val);
                        }
                    }
                }
            }
        }
    }
}
void simSystem::recordPkHistogram ()
Record the particle number histogram for the system at a given Ntot. Only records values when N_tot in range of [min, max].
Definition at line 1050 of file system.cpp.
References numSpecies.
Referenced by performTMMC().
                                   {
    // only record if in range (removes equilibration stage to get in this range, if there was any)
    if (totN_ >= totNBounds_[0] && totN_ <= totNBounds_[1]) {
        const int address = totN_-totNBounds_[0];
        for (unsigned int i = 0; i < nSpecies_; ++i) {
            pkHistogram_[i][address].record(numSpecies[i]);
        }
    }
}
void simSystem::refineEnergyHistogramBounds ()
Check the histogram entries and trim off zero-valued entries and bounds.
Definition at line 868 of file system.cpp.
References customException::what().
Referenced by checkpoint::dump(), and performTMMC().
                                             {
    for (std::vector < dynamic_one_dim_histogram >::iterator it = energyHistogram_.begin(); it != energyHistogram_.end(); ++it) {
        try {
            it->trim_edges();
        } catch (customException &ce) {
            std::string a = "Unable to trim edges in energyHistogram at each Ntot: ", b = ce.what();
            throw customException (a+b);
        }
    }
}
void simSystem::refinePkHistogramBounds ()
Check the histogram entries and trim off zero-valued entries and bounds.
Definition at line 1063 of file system.cpp.
Referenced by checkpoint::dump(), and performTMMC().
                                         {
    for (std::vector < std::vector < dynamic_one_dim_histogram > >::iterator it = pkHistogram_.begin(); it != pkHistogram_.end(); ++it) {
        for (std::vector < dynamic_one_dim_histogram >::iterator it2 = it->begin(); it2 != it->end(); ++it2) {
            try {
                it2->trim_edges();
            } catch (customException &ce) {
                throw customException ("Unable to trim edges in pkHistogram at each Ntot");
            }
        }
    }
}
void simSystem::reInitializeEnergyHistogram ()
Re-initialize the energy histogram with internal estimates of bounds. Intended to be used at crossover stage before TMMC.
Definition at line 882 of file system.cpp.
References totNMax(), and totNMin().
Referenced by performCrossover().
                                             {
    double lb = 0.0, ub = 0.0;
    if (energyHistogram_lb_.size() != energyHistogram_ub_.size()) {
        throw customException ("Bad energy histogram bound sizes");
    }
    if (energyHistogram_lb_.size() != totNMax() - totNMin() + 1) {
        throw customException ("Bad energy histogram bound sizes");
    }
    for (unsigned int i = 0; i < totNMax() - totNMin() + 1; ++i) {
        if (energyHistogram_lb_[i] > energyHistogram_ub_[i]) {
            throw customException ("Bad energy histogram bound sizes");
        }
        // "Standardize" the bounds against U = 0 for to "align" the bins, already done for pkHistogram.
        // This allows overlapping windows to be merged, otherwise they are not "aligned".
        // Rounding does not account for rare edge cases where energy falls exactly on the border between bins, but does not matter since this will be automatically handled.
        // This is just to give the system a good "guess" to conserve memory.
        lb = round((energyHistogram_lb_[i] - 0.0)/energyHistDelta_)*energyHistDelta_;
        ub = round((energyHistogram_ub_[i] - 0.0)/energyHistDelta_)*energyHistDelta_;
        try {
            energyHistogram_[i].reinitialize(lb,ub,energyHistDelta_);
        } catch (customException &ce) {
            throw customException ("Unable to reinitialize the energyHistogram");
        }
    }
}
void simSystem::restartEnergyHistogram (const std::stringprefix)
Restart the energy histogram for each Ntot from unnormalized checkpoint. This will check for 'alignment' of energy bins to 0. So 'manually' prepared files are likely to fail, but this is intended to restart from system-generated files anyway.
Parameters:
prefix Prefix of the filename to load from
Definition at line 972 of file system.cpp.
References totNMax(), and totNMin().
Referenced by checkpoint::load().
                                                              {
    int minBound = 0, maxBound = totNMax() - totNMin() + 1;
    std::vector < double > lb(maxBound - minBound, 0), ub(maxBound - minBound, 0), delta(maxBound - minBound, 0);
    std::string fileName = prefix+".dat";
    std::ifstream infile (fileName.c_str());
    if (!infile.is_open()) {
        throw customException ("Cannot load energyHistogram from "+fileName);
    }
    std::string line, tmp = "";
    int lineIndex = 0;
    while(std::getline(infile,line)) {
        std::stringstream lineStream(line);
        if (lineIndex == 2) {
            // get upper bound
            std::getline(lineStream, tmp, ':');
            std::getline(lineStream, tmp, ':');
            int high = atoi(tmp.c_str());
            if (high != totNMax()) {
                throw customException ("Max bound ("+ std::to_string(high)+") is not Nmax("+std::to_string(totNMax())+"), cannot restart energy histogram from "+fileName);
            }
        } else if (lineIndex == 3) {
            // get lower bound
            std::getline(lineStream, tmp, ':');
            std::getline(lineStream, tmp, ':');
            int low = atoi(tmp.c_str());
            if (low != totNMin()) {
                throw customException ("Min bound ("+ std::to_string(low)+") is not Nmin("+std::to_string(totNMin())+"), cannot restart energy histogram from "+fileName);
            }
        } else if (lineIndex == 6) {
            // delta
            for (unsigned int i = 0; i < maxBound-minBound; ++i) {
                lineStream >> delta[i];
            }
        } else if (lineIndex == 8) {
            // lower bound
            for (unsigned int i = 0; i < maxBound-minBound; ++i) {
                lineStream >> lb[i];
            }
            // check that system "aligned" the lower bounds so that a bin falls centered at U = 0
            for (unsigned int i = 0; i < maxBound-minBound; ++i) {
                const double x = (lb[i] - 0.0)/delta[i];
                const double err = fabs(round(x) - x);
                if (err >= 1.0e-6) {
                    throw customException ("Energy bins not aligned to U = 0, cannot restart energy histogram from "+fileName+" (err, "+std::to_string(i)+") = "+std::to_string(err));
                }
            }
        } else if (lineIndex == 10) {
            // upper bound
            for (unsigned int i = 0; i < maxBound-minBound; ++i) {
                lineStream >> ub[i];
            }
            // now can reinitialize the histogram
            for (unsigned int i = minBound; i < maxBound; ++i) {
                try {
                    energyHistogram_[i-minBound].reinitialize(lb[i-minBound], ub[i-minBound], delta[i-minBound]);
                } catch (...) {
                    throw customException ("Unable to restart energy histogram from "+fileName);
                }
            }
        } else if (lineIndex >= 12) {
            // histogram itself
            std::deque <double> h = energyHistogram_[lineIndex-12].get_hist();
            for (std::deque <double>::iterator it = h.begin(); it != h.end(); ++it) {
                lineStream >> *it;
            }
            energyHistogram_[lineIndex-12].set_hist(h);
        }
        lineIndex++;
    }
    infile.close();
}
void simSystem::restartExtMoments (const std::stringprefix, const std::vector< double > &ctr)
Restart the extensive energy histogram for each Ntot from unnormalized checkpoint.
Parameters:
fileName Name of the file to load from
ctr Counter for each point in the histogram
Definition at line 745 of file system.cpp.
References histogram::getAddress(), getMaxOrder(), histogram::getRawHistogram(), histogram::set(), totNMax(), totNMin(), and customException::what().
Referenced by checkpoint::load().
                                                                                         {
    std::string fileName = prefix+".dat";
    std::ifstream infile (fileName.c_str());
    if (!infile.is_open()) {
        throw customException ("Cannot load extMoments from "+fileName);
    }
    std::string line, tmp = "";
    int lineIndex = 0, dummy;
    long long unsigned int idx;
    std::vector < double > h = extensive_moments_.getRawHistogram (), coords (6, 0);
    while(std::getline(infile,line)) {
        std::stringstream lineStream(line);
        if (lineIndex == 1) {
            std::getline(lineStream, tmp, ':');
            std::getline(lineStream, tmp, ':');
            int ns = atoi(tmp.c_str());
            if (ns != nSpecies_) {
                throw customException ("Number of speces in restart file ("+ std::to_string(ns)+") is not the same as provided in input ("+std::to_string(nSpecies_)+"), cannot restart extMom from "+fileName);
            }
        } else if (lineIndex == 2) {
            std::getline(lineStream, tmp, ':');
            std::getline(lineStream, tmp, ':');
            int mo = atoi(tmp.c_str());
            if (mo != getMaxOrder()) {
                throw customException ("Max order ("+ std::to_string(mo)+") is not the same as provided in input ("+std::to_string(getMaxOrder())+"), cannot restart extMom from "+fileName);
            }
        } if (lineIndex == 3) {
            std::getline(lineStream, tmp, ':');
            std::getline(lineStream, tmp, ':');
            int high = atoi(tmp.c_str());
            if (high != totNMax()) {
                throw customException ("Max bound ("+ std::to_string(high)+") is not Nmax ("+std::to_string(totNMax())+"), cannot restart extMom from "+fileName);
            }
        } else if (lineIndex == 4) {
            std::getline(lineStream, tmp, ':');
            std::getline(lineStream, tmp, ':');
            int low = atoi(tmp.c_str());
            if (low != totNMin()) {
                throw customException ("Min bound ("+ std::to_string(low)+") is not Nmin ("+std::to_string(totNMin())+"), cannot restart extMom from "+fileName);
            }
            // now reinstantiate the histogram
            std::vector < double > lbn (6,0), ubn(6,0);
            std::vector < long long unsigned int > nbn (6,0);
            ubn[0] = nSpecies_-1;
            ubn[1] = max_order_;
            ubn[2] = nSpecies_-1;
            ubn[3] = max_order_;
            ubn[4] = max_order_;
            ubn[5] = totNMax()-totNMin();
            nbn[0] = nSpecies_;
            nbn[1] = max_order_+1;
            nbn[2] = nSpecies_;
            nbn[3] = max_order_+1;
            nbn[4] = max_order_+1;
            nbn[5] = totNMax()-totNMin()+1;
            histogram hnn (lbn, ubn, nbn);
            extensive_moments_ = hnn;
        } else if (lineIndex >= 7) {
            // histogram itself
            lineStream >> dummy;
            coords[5] = lineIndex-7;
            for (unsigned int i = 0; i < nSpecies_; ++i) {
                coords[0] = i;
                for (unsigned int j = 0; j <= max_order_; ++j) {
                    coords[1] = j;
                    for (unsigned int k = 0; k < nSpecies_; ++k) {
                        coords[2] = k;
                        for (unsigned int m = 0; m <= max_order_; ++m) {
                            coords[3] = m;
                            for (unsigned int p = 0; p <= max_order_; ++p) {
                                coords[4] = p;
                                idx = extensive_moments_.getAddress(coords);
                                lineStream >> h[idx];
                            }
                        }
                    }
                }
            }
        }
        lineIndex++;
    }
    infile.close();
    try {
        // this checks h and ctr same size, and by extension that h from file has same size as h in system
        extensive_moments_.set(h, ctr);
    } catch (customException &ce) {
        throw customException ("Unable to restart extMom from "+fileName+" : "+ce.what());
    }
}
void simSystem::restartPkHistogram (const std::stringprefix)
Restart the particle histogram for each Ntot from unnormalized checkpoint.
Parameters:
prefix Prefix of the filename to load from
Definition at line 1139 of file system.cpp.
References totNMax(), and totNMin().
Referenced by checkpoint::load().
                                                          {
    for (unsigned int spec = 0; spec < nSpecies_; ++spec) {
        int minBound = 0, maxBound = totNMax() - totNMin() + 1;
        std::vector < double > lb(maxBound - minBound, 0), ub(maxBound - minBound, 0), delta(maxBound - minBound, 0);
        std::string fileName = prefix+"_"+std::to_string(spec+1)+".dat";
        std::ifstream infile (fileName.c_str());
        if (!infile.is_open()) {
            throw customException ("Cannot load pkHistogram from "+fileName);
        }
        std::string line, tmp = "";
        int lineIndex = 0;
        while(std::getline(infile,line)) {
            std::stringstream lineStream(line);
            if (lineIndex == 2) {
                // get upper bound
                std::getline(lineStream, tmp, ':');
                std::getline(lineStream, tmp, ':');
                int high = atoi(tmp.c_str());
                if (high != totNMax()) {
                    throw customException ("Max bound ("+ std::to_string(high)+") is not Nmax("+std::to_string(totNMax())+"), cannot restart particle histogram from "+fileName);
                }
            } else if (lineIndex == 3) {
                // get lower bound
                std::getline(lineStream, tmp, ':');
                std::getline(lineStream, tmp, ':');
                int low = atoi(tmp.c_str());
                if (low != totNMin()) {
                    throw customException ("Min bound ("+ std::to_string(low)+") is not Nmin("+std::to_string(totNMin())+"), cannot restart particle histogram from "+fileName);
                }
            } else if (lineIndex == 1) {
                // check the number of species is correct
                std::getline(lineStream, tmp, ':');
                std::getline(lineStream, tmp, ':');
                int ns = atoi(tmp.c_str());
                if (ns != nSpecies_) {
                    throw customException ("Number of speces in restart file ("+ std::to_string(ns)+") is not the same as provided in input ("+std::to_string(nSpecies_)+"), cannot restart particle histogram from "+fileName);
                }
            } else if (lineIndex == 6) {
                // delta
                for (unsigned int i = 0; i < maxBound-minBound; ++i) {
                    lineStream >> delta[i];
                }
            } else if (lineIndex == 8) {
                // lower bound
                for (unsigned int i = 0; i < maxBound-minBound; ++i) {
                    lineStream >> lb[i];
                }
            } else if (lineIndex == 10) {
                // upper bound
                for (unsigned int i = 0; i < maxBound-minBound; ++i) {
                    lineStream >> ub[i];
                }
                // now can reinitialize the histogram
                for (unsigned int i = minBound; i < maxBound; ++i) {
                    try {
                        pkHistogram_[spec][i-minBound].reinitialize(lb[i-minBound], ub[i-minBound], delta[i-minBound]);
                    } catch (...) {
                        throw customException ("Unable to restart particle histogram from "+fileName);
                    }
                }
            } else if (lineIndex >= 12) {
                // histogram itself
                std::deque <double> h = pkHistogram_[spec][lineIndex-12].get_hist();
                for (std::deque <double>::iterator it = h.begin(); it != h.end(); ++it) {
                    lineStream >> *it;
                }
                pkHistogram_[spec][lineIndex-12].set_hist(h);
            }
            lineIndex++;
        }
        infile.close();
    }
}
const double simSystem::scratchEnergy ()
Recalculate the energy of the system from scratch.
Returns:
totU Total energy of the system
Definition at line 1548 of file system.cpp.
References atoms, NUM_INFINITY, numSpecies, ppot, speciesBarriers, and customException::what().
Referenced by readConfig(), and sanityChecks().
                                       {
    double totU = 0.0;
    double V = 1.0;
    for (unsigned int i = 0; i < box_.size(); ++i) {
        V *= box_[i];
    }
    for (unsigned int spec1 = 0; spec1 < nSpecies_; ++spec1) {
        int num1 = 0, adj1 = 0;
        try {
            num1 = numSpecies[spec1];
        } catch (customException &ce) {
            std::string a = "Cannot recalculate energy from scratch: ", b = ce.what();
            throw customException (a+b);
        }
        // Possibly have fractionally inserted atom
        if (fractionalAtomType_ == spec1 && Mcurrent_ > 0) {
            adj1 = 1;
        }
        // Wall/barrier interactions
        for (unsigned int j = 0; j < num1+adj1; ++j) {
            double dU = 0.0;
            try {
                dU = speciesBarriers[spec1].energy(&atoms[spec1][j], box_);
            } catch (customException &ce) {
                std::string a = "Cannot recalculate energy from scratch: ", b = ce.what();
                throw customException (a+b);
            }
            if (dU == NUM_INFINITY) {
                return NUM_INFINITY;
            } else {
                totU += dU;
            }
        }
        // Interactions with same type
        for (unsigned int j = 0; j < num1+adj1; ++j) {
            double dU = 0.0;
            for (unsigned int k = j+1; k < num1+adj1; ++k) {
                try {
                    dU = ppot[spec1][spec1]->energy(&atoms[spec1][j], &atoms[spec1][k], box_);
                } catch (customException &ce) {
                    std::string a = "Cannot recalculate energy from scratch: ", b = ce.what();
                    throw customException (a+b);
                }
                if (dU < NUM_INFINITY) {
                    totU += dU;
                } else {
                    return NUM_INFINITY;
                }
            }
        }
        // Add tail correction to potential energy but only for atoms fully inserted
#ifdef FLUID_PHASE_SIMULATIONS
        if ((ppot[spec1][spec1]->useTailCorrection) && (num1 > 1)) {
            totU += (num1)*0.5*ppot[spec1][spec1]->tailCorrection((num1-1)/V); // This is never infinite
        }
#endif
        // Interactions with other unique types
        for (unsigned int spec2 = spec1+1; spec2 < nSpecies_; ++spec2) {
            int num2 = 0, adj2 = 0;
            double dU = 0.0;
            try {
                num2 = numSpecies[spec2];
            } catch (customException &ce) {
                std::string a = "Cannot recalculate energy from scratch: ", b = ce.what();
                throw customException (a+b);
            }
            if (fractionalAtomType_ == spec2 && Mcurrent_ > 0) {
                adj2 = 1;
            }
            for (unsigned int j = 0; j < num1+adj1; ++j) {
                for (unsigned int k = 0; k < num2+adj2; ++k) {
                    try {
                        dU = ppot[spec1][spec2]->energy(&atoms[spec1][j], &atoms[spec2][k], box_);
                    } catch (customException &ce) {
                        std::string a = "Cannot recalculate energy from scratch: ", b = ce.what();
                        throw customException (a+b);
                    }
                    if (dU < NUM_INFINITY) {
                        totU += dU;
                    } else {
                        return NUM_INFINITY;
                    }
                }
            }
            // Add tail correction to potential energy but only bewteen fully inserted species
#ifdef FLUID_PHASE_SIMULATIONS
            if ((ppot[spec1][spec2]->useTailCorrection) && (num2 > 0) && (num1 > 0)) {
                totU += (num1)*ppot[spec1][spec2]->tailCorrection(num2/V); // Never infinite
            }
#endif
        }
    }
    if (toggleKE_ == true) {
        double ns = 0.0;
        for (unsigned int i = 0; i < nSpecies_; ++i) {
            ns += numSpecies[i];
        }
        totU += 1.5/beta_*ns; // Only adjust for FULLY-INSERTED ATOMS
    }
    return totU;
}
void simSystem::setELB (const std::vector< double >elb) [inline]
Assign energy lower bound from restart.
Definition at line 43 of file system.h.
Referenced by checkpoint::load().
void simSystem::setEUB (const std::vector< double >eub) [inline]
Assign energy upper bound from restart.
Definition at line 42 of file system.h.
Referenced by checkpoint::load().
void simSystem::setTotNBounds (const std::vector< int > &bounds)
Set the bounds on the total number of particles in a system. If not set manually, this defaults to the sum of the bounds given for each individual species in the system. Therefore, for single component simulations, this is identical to [minSpecies(0), maxSpecies(0)] unless otherwise set. These bounds are intended to be used to create 'windows' so that specific simulations can sample subregions of [minSpecies(0), maxSpecies(0)] and be stitched together with histogram reweighting later.
However, this routine will ALSO cause the system to reevaluate its bounds. If these total bounds are outside any individual bound for each atom type, nothing will change. However, if the upper bound for total atoms is less than an upper bound for a specific species, that species will have its bounds changed to match the total maximum. As a result sys.atoms can change so this routine should be called at the beginning of a simulation, never during. The total minimum will also be checked. That is, if the sum of the minimum for all species is still higher than this, an exception will be throw since the system will never reach such a low density anyway. Most likely the user has made a mistake.
Be sure to initialize other objects, such as biases, AFTER this routine has been called since it will adjust the allowable number of particles in the system.
Parameters:
bounds Vector of [min, max]
Definition at line 41 of file system.cpp.
References atoms, and numSpecies.
Referenced by initialize().
                                                              {
    if (bounds.size() != 2) {
        throw customException ("Bounds on total N must supplied as vector of <minN, maxN>");
    }
    if (bounds[0] < 0) {
        throw customException ("Lower bound on total particles must be > 0");
    }
    if (bounds[0] > bounds[1]) {
        throw customException ("Upper bound must be greater than lower bound for total number of particles in the system");
    }
    totNBounds_ = bounds;
    int totMin = 0;
    for (unsigned int i = 0; i < nSpecies_; ++i) {
        if (maxSpecies_[i] > totNBounds_[1]) {
            maxSpecies_[i] = totNBounds_[1];
        }
        if (maxSpecies_[i] < totNBounds_[1]) {
            throw customException ("Upper bound for species "+std::to_string(i+1)+" is lower than overall max, so cannot realize possibility of system being full of this species");
        }
        totMin += minSpecies_[i];
    }
    if (totMin > totNBounds_[0]) {
        throw customException ("Lower total N bound is lower than the sum of all individual lower bounds, region cannot be completely sampled");
    }
    // Recheck bounds and possibly resize
    int tmpTot = 0;
    for (unsigned int i = 0; i < nSpecies_; ++i) {
        if (maxSpecies_[i] < minSpecies_[i]) {
            throw customException ("Max species < Min species");
        }
        try {
            atoms[i].resize(maxSpecies_[i], atom());
        } catch (std::exception &e) {
            throw customException (e.what());
        }
        // If numSpecies[i] above maxSpecies_[i] for some reason, destroy the atoms beyond bound
        if (numSpecies[i] > (int)atoms[i].size()) {
            numSpecies[i] = atoms[i].size();
        }
        tmpTot += numSpecies[i];
    }
    totN_ = tmpTot;
    // Allocate space for energy matrix - this will only be recorded when the system is within the specific window we are looking for
    // Because of implementation of Shen and Errington method, this syntax is the same for single and multicomponent systems
    long long int size = totNBounds_[1] - totNBounds_[0] + 1;
    energyHistogram_.resize(0);
    energyHistogram_lb_.resize(size, -5.0);
    energyHistogram_ub_.resize(size, 5.0);
    for (unsigned int i = 0; i < size; ++i) {
        try {
            dynamic_one_dim_histogram dummyHist (energyHistogram_lb_[i], energyHistogram_ub_[i], energyHistDelta_);
            energyHistogram_.resize(i+1, dummyHist);
        } catch (std::bad_alloc &ba) {
            throw customException ("Out of memory for energy histogram for each Ntot");
        }
    }
    pkHistogram_.resize(0);
    dynamic_one_dim_histogram dummyPkHist (0.0, totNBounds_[1], 1.0);
    try {
        std::vector < dynamic_one_dim_histogram > tmp (totNBounds_[1]-totNBounds_[0]+1, dummyPkHist);
        pkHistogram_.resize(nSpecies_, tmp);
    } catch (std::bad_alloc &ba) {
        throw customException ("Out of memory for particle histogram for each Ntot");
    }
    // Initialize moments
    std::vector < double > lbn (6,0), ubn(6,0);
    std::vector < long long unsigned int > nbn (6,0);
    ubn[0] = nSpecies_-1;
    ubn[1] = max_order_;
    ubn[2] = nSpecies_-1;
    ubn[3] = max_order_;
    ubn[4] = max_order_;
    ubn[5] = totNBounds_[1]-totNBounds_[0];
    nbn[0] = nSpecies_;
    nbn[1] = max_order_+1;
    nbn[2] = nSpecies_;
    nbn[3] = max_order_+1;
    nbn[4] = max_order_+1;
    nbn[5] = size;
    histogram hnn (lbn, ubn, nbn);
    extensive_moments_ = hnn;
}
void simSystem::startTMMC (const long long inttmmcSweepSize, const intMtot)
Start using TMMC and instantiate the bias object. Start using a transition-matrix in the simulation.
Throws an exception if input values are illegal or there is another problem (e.g. memory).
Parameters:
tmmcSweepSize Number of times each transition in the collection matrix must be visited for a 'sweep' to be completed
Mtot Total number of expanded ensemble state allowed within the system
Definition at line 1750 of file system.cpp.
References tmmcBias, useTMMC, and customException::what().
Referenced by checkpoint::load(), performCrossover(), and performTMMC().
                                                                            {
    // initialize the tmmc object
    try {
        tmmcBias = new tmmc (totNBounds_[1], totNBounds_[0], Mtot, tmmcSweepSize, box_);
    } catch (customException& ce) {
        throw customException ("Cannot start TMMC biasing in system: "+std::to_string(*ce.what()));
    }
    useTMMC = true;
}
void simSystem::startWALA (const doublelnF, const doubleg, const doubles, const intMtot)
Start using Wang-Landau and instantiate the bias object.
Definition at line 1733 of file system.cpp.
References useWALA, customException::what(), and wlBias.
Referenced by checkpoint::load(), and performWALA().
                                                                                           {
    // initialize the wala object
    try {
        wlBias = new wala (lnF, g, s, totNBounds_[1], totNBounds_[0], Mtot, box_);
    } catch (customException& ce) {
        throw customException ("Cannot start Wang-Landau biasing in system: "+std::to_string(*ce.what()));
    }
    useWALA = true;
}
void simSystem::stopTMMC () [inline]
Stop using TMMC and free the bias object.
Definition at line 63 of file system.h.
References tmmcBias, and useTMMC.
Referenced by performTMMC().
void simSystem::stopWALA () [inline]
Stop using Wang-Landau and free the bias object.
Definition at line 61 of file system.h.
References useWALA, and wlBias.
Referenced by performCrossover().
void simSystem::toggleKE ()
Toggle KE adjustment to energy setting.
Definition at line 399 of file system.cpp.
Referenced by initialize(), and setConfig().
                         {
    if (toggleKE_ == false) {
        toggleKE_ = true;
    } else {
        toggleKE_ = false;
    }
}
const int simSystem::totNMax () [inline]
Return upper bound on the total number of atoms in the system.
Definition at line 75 of file system.h.
Referenced by insertParticle::make(), performTMMC(), reInitializeEnergyHistogram(), restartEnergyHistogram(), restartExtMoments(), and restartPkHistogram().
const int simSystem::totNMin () [inline]
Return lower bound on the total number of atoms in the system.
Definition at line 76 of file system.h.
Referenced by deleteParticle::make(), performTMMC(), reInitializeEnergyHistogram(), restartEnergyHistogram(), restartExtMoments(), restartPkHistogram(), and setConfig().
void simSystem::translateAtom (const inttypeIndex, const intatomIndex, std::vector< double >oldPos)
Translate an atom in the system. Does all the bookkeeping behind the scenes. Do nothing if there is no cell list defined for the type
Parameters:
typeIndex What type the atom is (>= 0)
atomIndex Which atom index of type typeIndex to translate (>= 0)
oldPos Old position of the atom. The current/new position should already be stored in the atom at sys.atoms[typeIndex][atomIndex]
Definition at line 378 of file system.cpp.
References atoms, and cellList::translateParticle().
Referenced by aggVolBias3::make(), and translateParticle::make().
                                                                                                 {
    if (typeIndex < nSpecies_ && typeIndex >= 0) {
        if (atomIndex >= 0) {
            // delete particle from appropriate cell list, move to new one
            for (unsigned int i=0; i<nSpecies_; i++) {
                if (useCellList_[typeIndex][i]) {
                    cellList* cl = cellListsByPairType_[typeIndex][i];
                    cl->translateParticle(&atoms[typeIndex][atomIndex], oldPos);
                }
            }
        } else {
            throw customException ("Number of those atoms in system is out of bounds, cannot translate an atom of type index "+std::to_string(typeIndex));
        }
    } else {
        throw customException ("That species index does not exist, cannot translate the atom");
    }
}
Field Documentation
std::vector< std::vector < atom > > simSystem::atoms
Atoms in a matrix by type, and particle index, respectively that a system CAN hold but not all are actually 'in' the system.
Definition at line 126 of file system.h.
Referenced by deleteAtom(), getNeighborAtoms(), insertAtom(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), printSnapshot(), sanityChecks(), scratchEnergy(), setTotNBounds(), simSystem(), and translateAtom().
long double simSystem::crossoverTotalStepCounter
Tracks the total MC steps taken during crossover stage.
Definition at line 108 of file system.h.
Referenced by checkpoint::dump(), checkpoint::load(), performCrossover(), performTMMC(), and simSystem().
double simSystem::gcmcEqSteps
In the case of unbiased GCMC, number of equilibration steps to perform.
Definition at line 102 of file system.h.
Referenced by initialize(), and performGCMC().
double simSystem::gcmcPrSteps
In the case of unbiased GCMC, number of production steps to perform.
Definition at line 103 of file system.h.
Referenced by initialize(), and performGCMC().
double simSystem::gcmcSnapFreq
In the case of unbiased GCMC, frequency with which to take snapshots of the system.
Definition at line 104 of file system.h.
Referenced by initialize(), and performGCMC().
double simSystem::gcmcThermoFreq
In the case of unbiased GCMC, frequency with which to record thermo properties.
Definition at line 105 of file system.h.
Referenced by initialize(), and performGCMC().
double simSystem::lnF_end
Starting and ending lnF for Wang-Landau.
Definition at line 100 of file system.h.
Referenced by initialize(), performWALA(), and simSystem().
double simSystem::lnF_start
Definition at line 100 of file system.h.
Referenced by initialize(), performWALA(), and simSystem().
long long int simSystem::nCrossoverVisits
Number of crossovers that must occur before switching from WALA to TMMC.
Definition at line 98 of file system.h.
Referenced by initialize(), performCrossover(), and simSystem().
std::vector< int > simSystem::numSpecies
Total number of each type of atom the system contains.
Definition at line 125 of file system.h.
Referenced by deleteAtom(), getNeighborAtoms(), insertAtom(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), insertParticle::make(), swapParticles::make(), performGCMC(), printSnapshot(), readConfig(), recordExtMoments(), recordPkHistogram(), sanityChecks(), scratchEnergy(), setConfig(), setTotNBounds(), and simSystem().
std::vector< std::vector < std::shared_ptr < pairPotential > > > simSystem::ppot
Matrix of pair potentials for atom types i, j.
Definition at line 127 of file system.h.
Referenced by addPotential(), checkBounds(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), scratchEnergy(), setPairPotentials(), and simSystem().
bool simSystem::restartFromTMMC
Flags to restart from WALA or TMMC initially.
Definition at line 93 of file system.h.
Referenced by checkpoint::checkpoint(), initialize(), performTMMC(), and simSystem().
std::string simSystem::restartFromTMMCFile
Files to restart from WALA or TMMC initially.
Definition at line 123 of file system.h.
Referenced by initialize(), performTMMC(), and simSystem().
bool simSystem::restartFromWALA
Definition at line 93 of file system.h.
Referenced by initialize(), performWALA(), and simSystem().
std::string simSystem::restartFromWALAFile
Definition at line 123 of file system.h.
Referenced by initialize(), performWALA(), and simSystem().
std::vector< compositeBarrier > simSystem::speciesBarriers
Barriers, if any, for each species.
Definition at line 128 of file system.h.
Referenced by deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), scratchEnergy(), setBarriers(), and simSystem().
tmmc* simSystem::tmmcBias
TMMC biasing function.
Definition at line 120 of file system.h.
Referenced by calculateBias(), getTMMCBias(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), startTMMC(), stopTMMC(), and ~simSystem().
long long int simSystem::tmmcSweepSize
Size of a sweep in TMMC.
Definition at line 95 of file system.h.
Referenced by initialize(), checkpoint::load(), performCrossover(), and performTMMC().
long double simSystem::tmmcTotalStepCounter
Tracks the total MC steps taken during TMMC stage.
Definition at line 109 of file system.h.
Referenced by checkpoint::dump(), checkpoint::load(), performTMMC(), and simSystem().
long long int simSystem::totalTMMCSweeps
Total number of sweeps to perform during TMMC.
Definition at line 96 of file system.h.
Referenced by initialize(), performTMMC(), and simSystem().
bool simSystem::useTMMC
Logical stating whether or not to use TMMC biasing.
Definition at line 91 of file system.h.
Referenced by calculateBias(), getTMMCBias(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), performTMMC(), performWALA(), simSystem(), startTMMC(), stopTMMC(), and ~simSystem().
bool simSystem::useWALA
Logical stating whether or not to use Wang-Landau biasing.
Definition at line 92 of file system.h.
Referenced by calculateBias(), getWALABias(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), insertParticle::make(), swapParticles::make(), performCrossover(), performTMMC(), performWALA(), simSystem(), startWALA(), stopWALA(), and ~simSystem().
double simSystem::wala_g
Definition at line 101 of file system.h.
Referenced by initialize(), checkpoint::load(), performWALA(), and simSystem().
double simSystem::wala_s
Wang-Landau g and s factors.
Definition at line 101 of file system.h.
Referenced by initialize(), checkpoint::load(), performWALA(), and simSystem().
long double simSystem::walaTotalStepCounter
Tracks the total MC steps taken during WALA stage.
Definition at line 107 of file system.h.
Referenced by checkpoint::dump(), checkpoint::load(), performCrossover(), performTMMC(), performWALA(), and simSystem().
wala* simSystem::wlBias
WALA biasing function.
Definition at line 121 of file system.h.
Referenced by calculateBias(), getWALABias(), startWALA(), stopWALA(), and ~simSystem().
long long int simSystem::wlSweepSize
Size of Wang-Landau sweep.
Definition at line 97 of file system.h.
Referenced by initialize(), performCrossover(), performWALA(), and simSystem().
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.