tabulated
NAME
tabulated -
Tabulated Potential Parameters should be specified in the following order: { r_cut, r_shift, u_shift, u_infinity, Mtot }.
SYNOPSIS
#include <potentials.h>
Inherits pairPotential.
Public Member Functions
~tabulated ()
void setParameters (const std::vector< double > params)
Set the parameters in the tabulated potential.
void loadPotential (std::string filename)
Load a tabulated potential from an external file and store it internally.
double energy (const atom *a1, const atom *a2, const std::vector< double > &box)
Return the energy of two particles.
double tailCorrection (const double rhoBath)
Tail correction for a tabulated potential always returns 0 since no information about what the potential is after its cutoff radius.
double rcut ()
Return the value of r_{cut} for this potential.
Additional Inherited Members
Detailed Description
Tabulated Potential Parameters should be specified in the following order: { r_cut, r_shift, u_shift, u_infinity, Mtot }.
Definition at line 77 of file potentials.h.
Constructor & Destructor Documentation
tabulated::~tabulated () [inline]
Definition at line 79 of file potentials.h.
{;}
Member Function Documentation
double tabulated::energy (const atom *a1, const atom *a2, const std::vector< double > &box) [virtual]
Return the energy of two particles. Use linear interpolation to calculate energy from tabulated values
Parameters:
a1 Atom 1
a2 Atom 2
box Simulation box dimensions
Returns:
U(r)
Implements pairPotential.
Definition at line 381 of file potentials.cpp.
References atom::mState, numToStr(), pairPotential::params_, pairPotential::paramsAreSet_, pbcDist2(), atom::pos, and sendErr().
                                                                                         {
    if (!paramsAreSet_) {
        throw customException ("For tabulated parameters not set");
    }
    const double r = sqrt(pbcDist2(a1->pos, a2->pos, box));
    double en = 0.0;
    // only one of these atoms (at most) should be "partially" inserted
    int mState = 0;
    if (a1->mState != 0) {
        mState = a1->mState;
    }
    if (a2->mState != 0) {
        mState = a2->mState;
    }
    if (r < params_[1]) {
        sendErr("Distance r too small in energy calculation in tabulated potential. Returning value at r = "+numToStr(start));
        en = table[0];
    } else if (r > params_[0]) {
        en = params_[3];
    } else {
        const unsigned int lowerIndex = floor((r-params_[1])/dr);
        const unsigned int upperIndex = ceil((r-params_[1])/dr);
        const double upperFraction = (r-params_[1])/dr-lowerIndex;
        const double lowerFraction = 1.0-upperFraction;
        en = (lowerFraction*table[lowerIndex] + upperFraction*table[upperIndex] + params_[2])*mScale[mState];
    }
    return en;
}
void tabulated::loadPotential (std::stringfilename)
Load a tabulated potential from an external file and store it internally.
Parameters:
filename Name of ASCII file to read (r, U(r)) from
Definition at line 324 of file potentials.cpp.
References fileExists(), numToStr(), pairPotential::params_, pairPotential::paramsAreSet_, and sendMsg().
                                                {
    sendMsg("Loading pair potential from "+filename);
    // first check, if file exists
    if (fileExists(filename)) {
        sendMsg("File found, processing");
        table.clear();
        double r, pot;
        unsigned int lineCounter = 0;
        std::ifstream inputData(filename.c_str());
        while (inputData >> r >> pot) {
            if (lineCounter == 0) {
                start = r;
            }
            else if (lineCounter == 1) {
                dr = r - start;
            }
            table.push_back(pot);
            lineCounter++;
        }
        inputData.close();
        if (lineCounter < 2) {
            paramsAreSet_ = false;
            throw customException ("Tabulated potential "+numToStr(filename)+" needs at least 2 entries, cannot setup potential");
            /*sendErr("Tabulated potential "+numToStr(filename)+" needs at least 2 entries, cannot setup potential");
            return;*/
        }
        // If parameters are not set, set default parameters
        if (!paramsAreSet_) {
            params_.assign(4, 0.0);
            params_[0] = start + (table.size()-1)*dr;
            params_[1] = start;
            params_[2] = 0.0;
            params_[3] = 0.0;
            paramsAreSet_ = true;
        }
    } else {
        throw customException ("File "+numToStr(filename)+" not found, cannot setup potential");
        /*sendErr("File "+numToStr(filename)+" not found, cannot setup potential");
        paramsAreSet_ = false;*/
    }
}
double tabulated::rcut () [virtual]
Return the value of r_{cut} for this potential.
Returns:
rcut
Implements pairPotential.
Definition at line 430 of file potentials.cpp.
References pairPotential::params_, and pairPotential::paramsAreSet_.
                        {
    if (!paramsAreSet_) {
        throw customException ("For tabulated parameters not set");
    } else {
        return params_[0];
    }
}
void tabulated::setParameters (const std::vector< double >params) [virtual]
Set the parameters in the tabulated potential.
Parameters:
params Vector of inputs: {r_cut, r_shift, u_shift, u_infinity, Mtot}
Implements pairPotential.
Definition at line 291 of file potentials.cpp.
References pairPotential::params_, pairPotential::paramsAreSet_, and pairPotential::useTailCorrection.
                                                                {
    if (params.size() != 5) {
        throw customException ("For tabulated must specify 5 parameters: r_cut, r_shift, u_shift, u_infinity, Mtot");
    } else {
        if (params[0] < 0) {
            throw customException ("For tabulated, r_cut >= 0");
        }
        if (int(params[4]) < 1) {
            throw customException ("For tabulated, total expanded ensemble states, Mtot >= 1");
        }
        paramsAreSet_ = true;
        params_ = params;
        useTailCorrection = false;
        // scale energy by a constant factor
        mScale.resize(int(params[4]), 0);
        for (int i = 0; i < mScale.size(); ++i) {
            if (i == 0) {
                mScale[i] = 1.0;
            } else {
                mScale[i] = 1.0/int(params[4])*i;
            }
        }
    }
}
double tabulated::tailCorrection (const doublerhoBath) [virtual]
Tail correction for a tabulated potential always returns 0 since no information about what the potential is after its cutoff radius.
Parameters:
Number density of the surrounding fluid
Returns:
U_tail
Implements pairPotential.
Definition at line 421 of file potentials.cpp.
                                                     {
    return 0.0;
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.