tmmc
NAME
tmmc -
Transition Matrix Monte Carlo biasing class.
SYNOPSIS
#include <bias.h>
Public Member Functions
tmmc ()
tmmc (const int Nmax, const int Nmin, const int Mtot, const long long int tmmcSweepSize, const std::vector< double > box)
Initialize the tmmc object.
void updateC (const int Nstart, const int Nend, const int Mstart, const int Mend, const double pa)
Update the collection matrix.
void calculatePI ()
Calculate the (natural logarithm of the) macrostate density matrix via the probability matrix.
void print (const std::string fileName, bool printC=false, bool printHC=false)
Print the UN-NORMALIZED biasing function (lnPI) and possibly collection matrix to files.
void readC (const std::string fileName)
Read the collection matrix from a file.
void readHC (const std::string fileName)
Read the visited states matrix from a file.
void setlnPI (const std::vector< double > &lnPIguess)
Blindly assign a guess of the macrostate distribution.
void iterateForward ()
Reset the visited state counter which tracks the number of times each point in the collection matrix has been visited.
void dumpVisited (const std::string fileName)
Dump the current visited states counter.
bool checkFullyVisited ()
Check if the the collection matrix has been samples sufficiently, i.e., if each state and transition has been visited tmmcSweepSize_ times.
const __BIAS_INT_TYPE__ getTransitionAddress (const int Nstart, const int Nend, const int Mstart, const int Mend)
For a given multidimensional array which has been cast into 1D, find the address that refers to a given transition.
const __BIAS_INT_TYPE__ getAddress (const int Nval, const int Mval)
Get the address in lnPI that corresponds to a given macrostate.
const long long int numSweeps ()
const double getBias (const int address)
const std::vector< double > getC ()
Return the collection matrix as it is.
const std::vector< double > getHC ()
Detailed Description
Transition Matrix Monte Carlo biasing class.
Definition at line 24 of file bias.h.
Constructor & Destructor Documentation
tmmc::tmmc () [inline]
Definition at line 26 of file bias.h.
{};
tmmc::tmmc (const intNmax, const intNmin, const intMtot, const long long inttmmcSweepSize, const std::vector< double >box)
Initialize the tmmc object.
Parameters:
Nmax Upper bound for total number of particles.
Nmin Lower bound for total number of particles.
Mtot Total number of expanded ensemble states in a system.
tmmcSweepSize Number of times the each point in the collection matrix must be visited for a 'sweep' to be considered finished
box Vector of simulations box dimensions.
Definition at line 12 of file bias.cpp.
References __BIAS_INT_TYPE__.
                                                                                                                            {
    if (Nmin > Nmax) {
        throw customException ("Nmin ("+std::to_string(Nmin)+") > Nmax ("+std::to_string(Nmax)+" in TMMC bias");
    }
    if (Nmin < 0) {
        throw customException ("Nmin < 0 in TMMC bias");
    }
    if (Mtot < 1) {
        throw customException ("Mtot < 1 in TMMC bias");
    }
    __BIAS_INT_TYPE__ size = (Nmax - Nmin + 1);
    Nmin_ = Nmin;
    Nmax_ = Nmax;
    Mtot_ = Mtot;
    if (box.size() != 3) {
        throw customException ("Illegal number of box dimensions in TMMC");
    }
    for (unsigned int i = 0; i < box.size(); ++i) {
        if (box[i] < 0) {
            throw customException ("Illegal box dimensions in TMMC");
        }
    }
    box_.resize(3, 0);
    box_ = box;
    nSweeps_ = 0;
    if (tmmcSweepSize < 1) {
        throw customException ("TMMC sweep size must be >= 1");
    }
    tmmcSweepSize_ = tmmcSweepSize;
    // attempt to allocate memory for collection matrix and initializes it all to 0
    try {
        C_.resize(3*Mtot_*size, 0);
    } catch (const std::bad_alloc &ce) {
        throw customException ("Out of memory, cannot allocate space for collection matrix in tmmc");
    }
    // attempt to allocate memory for probability matrix and initializes it all to 0
    try {
        P_.resize(3*Mtot_*size, 0);
    } catch (const std::bad_alloc &ce) {
        throw customException ("Out of memory, cannot allocate space for probability matrix in tmmc");
    }
    // attempt to allocate memory for states counter to check how often a sweep has been performed
    try {
        HC_.resize(3*Mtot_*size, 0);
    } catch (const std::bad_alloc &ce) {
        throw customException ("Out of memory, cannot allocate space for the sweep counter in tmmc");
    }
    // attempt to allocate memory for lnPI matrix and initializes it all to 0
    try {
        lnPI_.resize(Mtot_*size, 0.0);
    } catch (const std::bad_alloc &ce) {
        throw customException ("Out of memory, cannot allocate space for macrostate distribution matrix in tmmc");
    }
}
Member Function Documentation
void tmmc::calculatePI ()
Calculate the (natural logarithm of the) macrostate density matrix via the probability matrix.
Definition at line 239 of file bias.cpp.
References __BIAS_INT_TYPE__, and getTransitionAddress().
Referenced by checkpoint::load(), performCrossover(), and performTMMC().
                        {
    const int endPoint = C_.size() - (Mtot_-1)*3;
    for (__BIAS_INT_TYPE__ i = 0; i < endPoint; i += 3) {
        double sum = 0.0;
        for (unsigned int j = 0; j < 3; ++j) {
            sum += C_[i+j];
        }
        if (sum > 0) {
            for (unsigned int j = 0; j < 3; ++j) {
                P_[i+j] = C_[i+j] / sum;
            }
        } else {
            // This state has not been visited at all if sum = 0. However, at high system densities this could be the "correct"
            // result so this error may need to be discarded later in favor of:
            // P_[i+j] = 0;
            // However, having this throw an exception is also a good way to find that upper bound where the system is completely packed
            // so I will keep it this way for now.
            throw customException ("Cannot compute TMMC macrostate distribution because probability matrix contains zeros");
        }
    }
    // Reset first value to zero just to start fresh. Since only ratios matter this is perfectly fair.
    lnPI_[0] = 0.0;
    int counter = 0;
    __BIAS_INT_TYPE__ address1 = 0, address2 = 0, nStartForward = 0, mStartForward = 0, nEndForward = 0, mEndForward = 0, nStartBackward = 0, nEndBackward = 0, mStartBackward = 0, mEndBackward = 0;
    for (__BIAS_INT_TYPE__ i = 0; i < (Nmax_ - Nmin_); ++i) { // don't calculate the last N = Nmax when M > 0, stops initially at N = Nmax, M = 0
        nStartForward = Nmin_+i;
        for (__BIAS_INT_TYPE__ j = 0; j < Mtot_; ++j) {
            mStartForward = j;
            if (j == Mtot_-1) {
                nEndForward = nStartForward + 1;
                mEndForward = 0;
            } else {
                nEndForward = nStartForward;
                mEndForward = j + 1;
            }
            nStartBackward = nEndForward;
            nEndBackward = nStartForward;
            mStartBackward = mEndForward;
            mEndBackward = mStartForward;
            address1 = getTransitionAddress(nStartForward, nEndForward, mStartForward, mEndForward);
            address2 = getTransitionAddress(nStartBackward, nEndBackward, mStartBackward, mEndBackward);
            if (!(P_[address1] > 0) || !(P_[address2] > 0)) {
                throw customException ("Cannot compute TMMC macrostate distribution because probability matrix contains zeros at address: P["+std::to_string(address1)+"] = "+std::to_string(P_[address1])+", P["+std::to_string(address2)+"] = "+std::to_string(P_[address2]));
            }
            lnPI_[counter+1] = lnPI_[counter] + log(P_[address1]/P_[address2]); // this is why P_ cannot be zero
            counter++;
        }
    }
}
bool tmmc::checkFullyVisited ()
Check if the the collection matrix has been samples sufficiently, i.e., if each state and transition has been visited tmmcSweepSize_ times.
Definition at line 100 of file bias.cpp.
References __BIAS_INT_TYPE__.
Referenced by performCrossover(), and performTMMC().
                              {
    const int endPoint = HC_.size() - (Mtot_-1)*3; // we don't care about the last chunk where N = Nmax, but M > 0 - stop at N = Nmax, M = 0
    for (__BIAS_INT_TYPE__ i = 0; i < endPoint; i += 3) {
        if (i == 0) {
            // lower bound, so only +1 and 0 moves must be sampled
            if ((HC_[i+1] < tmmcSweepSize_) || (HC_[i] < tmmcSweepSize_)) {
                return false;
            }
        } else if (i == endPoint-3) {
            // upper bound, so only -1 and 0 moves must be sampled
            if ((HC_[i] < tmmcSweepSize_) || (HC_[i+2] < tmmcSweepSize_)) {
                return false;
            }
        } else {
            // midpoints, both +1 and -1 (and 0) moves must be sampled
            if ((HC_[i] < tmmcSweepSize_) || (HC_[i+1] < tmmcSweepSize_) || (HC_[i+2] < tmmcSweepSize_)) {
                return false;
            }
        }
    }
    return true;
}
void tmmc::dumpVisited (const std::stringfileName)
Dump the current visited states counter.
Parameters:
filename Name of file to print to. Prints in column format.
Definition at line 79 of file bias.cpp.
Referenced by performCrossover(), and print().
                                                {
    std::ofstream of;
    std::string name = fileName+".dat";
    of.open(name.c_str(), std::ofstream::out);
    if (!of.is_open()) {
        throw customException ("Unable to write TMMC visited states matrix to "+name);
    }
    of << "# TMMC visited states counter in single row (vectorized) notation." << std::endl;
    of << "# species_total_upper_bound: " << Nmax_ << std::endl;
    of << "# species_total_lower_bound: " << Nmin_ << std::endl;
    double V = box_[0]*box_[1]*box_[2];
    of << "# volume: " << std::setprecision(15) << V << std::endl;
    for (long long int i = 0; i < HC_.size(); ++i) {
        of << std::setprecision(15) << HC_[i] << std::endl;
    }
    of.close();
}
const __BIAS_INT_TYPE__ tmmc::getAddress (const intNval, const intMval)
Get the address in lnPI that corresponds to a given macrostate.
Parameters:
Nval Number of total atoms
Mval Value of expanded ensemble state
Definition at line 199 of file bias.cpp.
Referenced by calculateBias().
                                                                        {
    if (Nval > Nmax_ || Nval < Nmin_ || Mval < 0 || Mval > Mtot_-1) {
        throw customException ("N, M out of bounds in TMMC object, cannot retrieve address");
    }
    return (Nval - Nmin_)*Mtot_ + Mval;
}
const double tmmc::getBias (const intaddress) [inline]
Definition at line 41 of file bias.h.
Referenced by calculateBias().
{ return -lnPI_[address]; }
const std::vector< double > tmmc::getC () [inline]
Return the collection matrix as it is.
Definition at line 42 of file bias.h.
const std::vector< double > tmmc::getHC () [inline]
Definition at line 43 of file bias.h.
{ return HC_; }
const __BIAS_INT_TYPE__ tmmc::getTransitionAddress (const intNstart, const intNend, const intMstart, const intMend)
For a given multidimensional array which has been cast into 1D, find the address that refers to a given transition. Assumes only valid moves are moving by +/-1 M (and subsequently N), will throw exception if this is not met.
Parameters:
Nstart Number of total species initially (before MC move)
Nend Number of total species (in order) after the MC move
Mstart Expanded ensemble state the system begins in
Mend Expanded ensemble state the system ends in
Definition at line 141 of file bias.cpp.
References __BIAS_INT_TYPE__.
Referenced by calculatePI(), and updateC().
                                                                                                                      {
    if (Nstart > Nmax_ || Nstart < Nmin_ || Nend > (Nmax_+1) || Nend < (Nmin_-1) || Mstart < 0 || Mstart > Mtot_-1 || Mend < 0 || Mend > Mtot_-1) { // Nend has array positions for going over end of bounds but are never used, still they are valid
        throw customException ("N, M out of bounds in TMMC object, cannot retrieve address");
    }
    if (Mtot_ > 1) {
        // expanded ensemble
        int y = 0;
        if (Nstart == Nend) {
            // moving within an expanded set
            int addOrSubtract = Mend - Mstart;
            if (addOrSubtract == 0) {
                y = 0;
            } else if (addOrSubtract == 1) {
                y = 1;
            } else if (addOrSubtract == -1) {
                y = 2;
            } else {
                throw customException ("Illegal addOrSubtract value");
            }
        } else {
            // crossing over
            if (Nend > Nstart) {
                y = 1;
                if (Mstart != Mtot_ - 1 || Mend != 0) {
                    throw customException ("Illegal expanded ensemble values");
                }
            } else {
                y = 2;
                if (Mstart != 0 || Mend != (Mtot_-1)) {
                    throw customException ("Illegal expanded ensemble values");
                }
            }
        }
        return 3*((Nstart - Nmin_)*Mtot_ + Mstart) + y;
    } else {
        // no expanded ensemble
        int addOrSubtract = (Nend - Nstart), y = 0;
        if (addOrSubtract == 0) {
            y = 0;
        } else if (addOrSubtract == 1) {
            y = 1;
        } else if (addOrSubtract == -1) {
            y = 2;
        } else {
            throw customException ("Illegal addOrSubtract value");
        }
        __BIAS_INT_TYPE__ x = Nstart - Nmin_;
        return x*3 + y; // equivalent to expanded ensemble because Mstart = 0 always, and Mtot_ = 1
    }
}
void tmmc::iterateForward ()
Reset the visited state counter which tracks the number of times each point in the collection matrix has been visited.
Definition at line 127 of file bias.cpp.
Referenced by performCrossover(), and performTMMC().
                           {
    std::fill(HC_.begin(), HC_.end(), 0);
    nSweeps_++;
}
const long long int tmmc::numSweeps () [inline]
Definition at line 40 of file bias.h.
Referenced by performCrossover().
{ return nSweeps_; }
void tmmc::print (const std::stringfileName, boolprintC = false, boolprintHC = false)
Print the UN-NORMALIZED biasing function (lnPI) and possibly collection matrix to files. Will overwrite the files if another with that name exists.
Parameters:
fileName Name of the file to print to. Will append with '_lnPI' and '_C' for biasing function and collection matrix, respectively.
printC Defaults to false, but if true will also print the collection matrix.
printHC Defaults to false, but if true will also print the visited states matrix.
Definition at line 301 of file bias.cpp.
References dumpVisited().
Referenced by checkpoint::dump(), performCrossover(), and performTMMC().
                                                                     {
    // Print collection matrix
    if (printC) {
        // print all states, including partial ones, so this can be used to restart from, etc.
        std::ofstream of;
        std::string name = fileName+"_C.dat";
        of.open(name.c_str(), std::ofstream::out);
        if (!of.is_open()) {
            throw customException ("Unable to write TMMC collection matrix to "+name);
        }
        of << "# Collection matrix in single row (vectorized) notation." << std::endl;
        of << "# species_total_upper_bound: " << Nmax_ << std::endl;
        of << "# species_total_lower_bound: " << Nmin_ << std::endl;
        double V = box_[0]*box_[1]*box_[2];
        of << "# volume: " << std::setprecision(15) << V << std::endl;
        for (long long int i = 0; i < C_.size(); ++i) {
            of << std::setprecision(15) << C_[i] << std::endl;
        }
        of.close();
    }
    // Print visited states matrix
    if (printHC) {
        // print all states, including partial ones, so this can be used to restart from, etc.
        dumpVisited(fileName+"_HC");
    }
    // Print lnPI (bias) matrix
    std::ofstream of;
    std::string name = fileName+"_lnPI.dat";
    of.open(name.c_str(), std::ofstream::out);
    if (!of.is_open()) {
        throw customException ("Unable to write TMMC lnPI to "+name);
    }
    of << "# lnPI (bias) matrix in single row (vectorized) notation." << std::endl;
    of << "# species_total_upper_bound: " << Nmax_ << std::endl;
    of << "# species_total_lower_bound: " << Nmin_ << std::endl;
    double V = box_[0]*box_[1]*box_[2];
    of << "# volume: " << std::setprecision(15) << V << std::endl;
    for (long long int i = 0; i < lnPI_.size(); i += Mtot_) {
        of << std::setprecision(15) << lnPI_[i] << std::endl; // only print the integral states
    }
    of.close();
}
void tmmc::readC (const std::stringfileName)
Read the collection matrix from a file. This assumes the user has already guaranteed that the bounds are consistent, e.g. Nmin and Nmax, as it will not check this automatically. Also assumes file was generated by this code. 'Hand made' ones might have formatting issues since parsing is done based on tokens.
Parameters:
fileName Name of file containing the collection matrix. Must include file extension.
Definition at line 378 of file bias.cpp.
Referenced by checkpoint::load(), and performTMMC().
                                          {
    std::ifstream infile (fileName.c_str());
    if (!infile.is_open()) {
        throw customException("Unable to read collection matrix from ASCII file "+fileName);
    }
    std::string line;
    int lineIndex = 0;
    while(std::getline(infile,line)) {
        std::stringstream lineStream(line);
        // skip any header information
        if (line.compare(0,1,"#",0,1) != 0) {
            C_[lineIndex] = atof(line.c_str());
            lineIndex++;
        }
    }
    infile.close();
}
void tmmc::readHC (const std::stringfileName)
Read the visited states matrix from a file. This assumes the user has already guaranteed that the bounds are consistent, e.g. Nmin and Nmax, as it will not check this automatically. Also assumes file was generated by this code. 'Hand made' ones might have formatting issues since parsing is done based on tokens.
Parameters:
fileName Name of file containing the visited states matrix. Must include file extension.
Definition at line 353 of file bias.cpp.
Referenced by checkpoint::load().
                                           {
    std::ifstream infile (fileName.c_str());
    if (!infile.is_open()) {
        throw customException("Unable to read visited states matrix from ASCII file "+fileName);
    }
    std::string line;
    int lineIndex = 0;
    while(std::getline(infile,line)) {
        std::stringstream lineStream(line);
        // skip any header information
        if (line.compare(0,1,"#",0,1) != 0) {
            HC_[lineIndex] = atof(line.c_str());
            lineIndex++;
        }
    }
    infile.close();
}
void tmmc::setlnPI (const std::vector< double > &lnPIguess) [inline]
Blindly assign a guess of the macrostate distribution.
Definition at line 34 of file bias.h.
void tmmc::updateC (const intNstart, const intNend, const intMstart, const intMend, const doublepa)
Update the collection matrix. This records the number of times a transition probability is measured with a finite, non-zero probability. This way, when checkFullyVisited() returns true, all the lnPI values can be calculated since all transition probabilities will be finite. Otherwise, transitions could be 'sampled' but if the dU = inf, then the collection matrix is updated with a value of 0. This could theoretically remain zero until the end of a sweep which is later caught when it creates a problem for calculating lnPI in calculatePI().
Parameters:
Nstart Total number of atoms initially (before MC move)
Nend Total number of atoms after the MC move
Mstart Initial value of expanded ensemble state
Mend Final value of expanded ensemble state
pa Unbiased Metropolis criterion for making a MC move (i.e. pa = min(1, exp(...)))
Definition at line 215 of file bias.cpp.
References getTransitionAddress(), and customException::what().
Referenced by aggVolBias3::make(), translateParticle::make(), deleteParticle::make(), insertParticle::make(), and swapParticles::make().
                                                                                                       {
    int i = 0, j = 0;
    try {
        i = getTransitionAddress(Nstart, Nend, Mstart, Mend);
    } catch (customException &ce) {
        throw customException ("Cannot update collection matrix: " + std::to_string(*ce.what()));
    }
    try {
        j = getTransitionAddress(Nstart, Nstart, Mstart, Mstart);
    } catch (customException &ce) {
        throw customException ("Cannot update collection matrix: " + std::to_string(*ce.what()));
    }
    C_[i] += pa;
    C_[j] += (1-pa);
    if (pa > 0.0) {
        HC_[i] += 1.0; // Only count the transition actually proposed, not the Nstart --> Nstart unless that was what was originally proposed, and only count when transition probability is finite.
    } else if (Nstart == 0 && Nend == 0) {
        HC_[i] += 1.0; // Translation move when 0 particles in system is "early rejected" (p = 0), but this is valid - if N_min of window is > 0 checkVisited() works fine, but if includes 0, this state is detected as never being sampled otherwise, which is the incorrect response
    }
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.