.TH "/home/nam4/Desktop/sandbox/FHMCSimulation/src/tmmc.h" 3 "Thu Dec 29 2016" "Version v0.1.0" "Flat-Histogram Monte Carlo Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/tmmc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'checkpoint\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'mover\&.h'\fP
.br
\fC#include 'sanity\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBperformTMMC\fP (\fBsimSystem\fP &sys, \fBcheckpoint\fP &res, \fBmoves\fP *usedMovesPr)"
.br
.RI "\fIPerform TMMC stage of simulation\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void performTMMC (\fBsimSystem\fP &sys, \fBcheckpoint\fP &res, \fBmoves\fP *usedMovesPr)"

.PP
Perform TMMC stage of simulation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsys\fP System to simulate 
.br
\fIres\fP Restart/checkpoint information 
.br
\fIusedMovesPr\fP Move class to use 
.RE
.PP

.PP
Definition at line 10 of file tmmc\&.cpp\&.
.PP
References tmmc::calculatePI(), checkpoint::check(), tmmc::checkFullyVisited(), simSystem::getCurrentM(), simSystem::getTMMCBias(), simSystem::getTotalM(), tmmc::iterateForward(), moves::makeMove(), checkpoint::moveCounter, numToStr(), moves::print(), tmmc::print(), simSystem::printEnergyHistogram(), simSystem::printExtMoments(), simSystem::printPkHistogram(), simSystem::printSnapshot(), tmmc::readC(), simSystem::recordEnergyHistogram(), simSystem::recordExtMoments(), simSystem::recordPkHistogram(), simSystem::refineEnergyHistogramBounds(), simSystem::refinePkHistogramBounds(), checkpoint::resFromTMMC, simSystem::restartFromTMMC, simSystem::restartFromTMMCFile, sanityChecks(), sendErr(), sendMsg(), simSystem::startTMMC(), simSystem::stopTMMC(), checkpoint::sweepCounter, SYS_FAILURE, checkpoint::tmmcDone, simSystem::tmmcSweepSize, simSystem::totalTMMCSweeps, simSystem::totNMax(), simSystem::totNMin(), simSystem::useTMMC, simSystem::useWALA, and customException::what()\&.
.PP
.nf
10                                                                        {
11     if (res\&.tmmcDone) {
12         throw customException ("Checkpoint indicates TMMC already finished");
13     }
14     sendMsg("Beginning TMMC");
15 
16     // Specifically for printing progress every 1% of the simulation
17     const long long int numSweepSnaps = 100;
18     unsigned long long int sweepPrint = sys\&.totalTMMCSweeps, printCounter = 0;
19     if (sys\&.totalTMMCSweeps >= numSweepSnaps) {
20         sweepPrint /= numSweepSnaps;
21     }
22 
23     res\&.tmmcDone = false;
24     unsigned long long int sweep = 0;
25     unsigned long long int counter = 0;
26     if (!res\&.resFromTMMC) {
27         if (sys\&.useWALA) {
28             throw customException ("WALA not deactivated, cannot proceeed with TMMC");
29         }
30         if (sys\&.restartFromTMMC) {
31             if (!sys\&.useTMMC) {
32                 // In case where not restarting from checkpoint, but starting fresh from TMMC, crossover stage was skipped so TMMC has not been activated yet
33                 sys\&.startTMMC (sys\&.tmmcSweepSize, sys\&.getTotalM());
34             }
35             try {
36                 sys\&.getTMMCBias()->readC(sys\&.restartFromTMMCFile); // read collection matrix
37                 sys\&.getTMMCBias()->calculatePI();
38                 sendMsg("Restarted TMMC from collection matrix from "+sys\&.restartFromTMMCFile);
39             } catch (customException &ce) {
40                 sys\&.stopTMMC(); // deallocate
41                 std::string msg = ce\&.what();
42                 sendErr("Failed to initialize from TMMC collection matrix because "+msg);
43                 exit(SYS_FAILURE);
44             }
45         }
46     } else {
47         printCounter = res\&.moveCounter;
48         sweep = res\&.sweepCounter;
49     }
50 
51     sendMsg("Starting progress stage from "+numToStr(printCounter)+"/"+numToStr(std::min(numSweepSnaps, sys\&.totalTMMCSweeps)));
52     sendMsg("Starting from "+numToStr(sweep)+"/"+numToStr(sys\&.totalTMMCSweeps)+" total TMMC sweeps");
53 
54     unsigned long long int checkPoint = sys\&.tmmcSweepSize*(sys\&.totNMax() - sys\&.totNMin() + 1)*3; // how often to check full traversal of collection matrix
55     while (sweep < sys\&.totalTMMCSweeps) {
56         bool done = false;
57 
58         // Perform a sweep
59         while (!done) {
60             try {
61                 usedMovesPr->makeMove(sys);
62             } catch (customException &ce) {
63                 sendErr(ce\&.what());
64                 exit(SYS_FAILURE);
65             }
66 
67             // Only record properties of the system when it is NOT in an intermediate state
68             if (sys\&.getCurrentM() == 0) {
69                 sys\&.recordEnergyHistogram();
70                 sys\&.recordPkHistogram();
71                 sys\&.recordExtMoments();
72             }
73 
74             // Check if sweep is done
75             if (counter%checkPoint == 0) {
76                 done = sys\&.getTMMCBias()->checkFullyVisited();
77                 counter = 0;
78             }
79 
80             counter++;
81             res\&.check(sys, printCounter, sweep);
82         }
83 
84         sys\&.getTMMCBias()->iterateForward(); // reset the counting matrix and increment total sweep number
85         sweep++;
86 
87         sendMsg("Finished "+numToStr(sweep)+"/"+numToStr(sys\&.totalTMMCSweeps)+" total TMMC sweeps");
88 
89         // Update biasing function from collection matrix
90         sys\&.getTMMCBias()->calculatePI();
91 
92         // Periodically write out checkpoints to monitor convergence properties later - all are used in FHMCAnalysis at this point (12/22/16)
93         if (sweep%sweepPrint == 0) {
94             printCounter++;
95             sys\&.getTMMCBias()->print("tmmc-Checkpoint-"+std::to_string(printCounter), false, false); // true, false);
96             sys\&.refineEnergyHistogramBounds();
97             sys\&.printEnergyHistogram("eHist-Checkpoint-"+std::to_string(printCounter));
98             sys\&.refinePkHistogramBounds();
99             sys\&.printPkHistogram("pkHist-Checkpoint-"+std::to_string(printCounter));
100             sys\&.printExtMoments("extMom-Checkpoint-"+std::to_string(printCounter));
101             usedMovesPr->print("tmmc\&.stats");
102         }
103     }
104 
105     // Print final results
106     sys\&.getTMMCBias()->print("final", false, false);
107     sys\&.refineEnergyHistogramBounds();
108     sys\&.printEnergyHistogram("final_eHist");
109     sys\&.refinePkHistogramBounds();
110     sys\&.printPkHistogram("final_pkHist");
111     sys\&.printExtMoments("final_extMom");
112     sys\&.printSnapshot("final\&.xyz", "last configuration");
113     usedMovesPr->print("tmmc\&.stats");
114 
115     sanityChecks(sys);
116     res\&.tmmcDone = true;
117 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code\&.
