/home/nam4/Desktop/sandbox/FHMCSimulation/src/utilities.h
NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/utilities.h -
SYNOPSIS
#include <vector>
#include <string>
#include <sys/stat.h>
#include <cstdio>
#include <sstream>
#include <cmath>
#include <iomanip>
#include <ctime>
#include <time.h>
#include <iostream>
#include <stdio.h>
#include 'global.h'
#include 'rapidjson/include/rapidjson/document.h'
#include 'rapidjson/include/rapidjson/writer.h'
#include 'rapidjson/include/rapidjson/stringbuffer.h'
#include 'rapidjson/include/rapidjson/filereadstream.h'
#include 'rapidjson/include/rapidjson/prettywriter.h'
Functions
void sendMsg (const std::string msg)
Send a message to std::cout.
void sendErr (const std::string msg)
Send a message to std::cerr.
void parseJson (const std::string filename, rapidjson::Document &doc)
Parse a JSON file and return the corresponding document.
void pauseCode (long int dur)
Pause the code for a certain time.
void pbc (std::vector< double > &pos, const std::vector< double > &box)
Replace a position inside a box assuming periodic boundary conditions.
bool fileExists (std::string fileName)
Function to check whether a given file exists or not.
double rng (int *idum)
Random number generator (from Numerical Recipes)
double pbcDist2 (const std::vector< double > &p1, const std::vector< double > &p2, const std::vector< double > &box)
Calculate the minimum image distance squared between two coordinates assuming periodic boundary conditions.
std::string getTimeStamp ()
Obtain instantaneous timestamp.
template<typename T > std::string numToStr (const T &val)
Convert a number to a string with 15 digits of precision.
std::vector< double > random3DSurfaceVector (const double magnitude)
Chose a random vector sampled from a random distribution on the surface of a sphere.
std::vector< std::string > splitstr (const std::string &s, char delim)
C++ explode a string.
std::vector< std::vector
< double > > rotationMatrix (const double alpha, const double beta, const double gamma)"
Create 3D rotation matrix from angles (x, then y, then z)
std::vector< std::vector
< double > > matrixProduct (std::vector< std::vector< double > > &mat1, std::vector< std::vector< double > > &mat2)"
Compute product of 2 matrices, W = UV.
Function Documentation
bool fileExists (std::stringfileName)
Function to check whether a given file exists or not.
Parameters:
fileName Name of file to check
Returns:
If file exists
Definition at line 272 of file utilities.cpp.
Referenced by checkpoint::checkpoint(), checkpoint::dump(), checkpoint::load(), and tabulated::loadPotential().
                                    {
    struct stat stFileInfo;
    if (stat(fileName.c_str(),&stFileInfo) == 0)
        return true;
    else
        return false;
}
std::string getTimeStamp ()
Obtain instantaneous timestamp.
Returns:
char* timestamp
Definition at line 91 of file utilities.cpp.
Referenced by checkpoint::dump(), moves::print(), sendErr(), and sendMsg().
                          {
    time_t rawtime;
    time (&rawtime);
    struct tm * timeinfo;
    timeinfo = localtime (&rawtime);
    char timestamp [80];
    strftime (timestamp,80,"%d/%m/%Y %H:%M:%S",timeinfo);
    std::string ans (timestamp);
    return ans;
}
std::vector< std::vector < double > > matrixProduct (std::vector< std::vector< double > > &mat1, std::vector< std::vector< double > > &mat2)
Compute product of 2 matrices, W = UV.
Parameters:
mat1 Matrix U
mat2 Matrix V
Returns:
W
Definition at line 109 of file utilities.cpp.
Referenced by rotationMatrix().
                                                                                                                                      {
    std::vector < double > dummy (3, 0);
    std::vector < std::vector < double > > W (3, dummy);
    for (unsigned int i = 0; i < 3; ++i) {
        for (unsigned int j = 0; j < 3; ++j) {
            W[i][j] = mat1[i][j]*mat2[j][i];
        }
    }
    return W;
}
template<typename T > std::string numToStr (const T &val)
Convert a number to a string with 15 digits of precision.
Parameters:
val Double precision value
Returns:
string Representation of this value
Definition at line 44 of file utilities.h.
Referenced by moves::addDelete(), moves::addInsert(), simSystem::addPotential(), moves::addSwap(), moves::addTranslate(), checkBounds(), tabulated::energy(), initialize(), tabulated::loadPotential(), performCrossover(), performTMMC(), performWALA(), sanityChecks(), setConfig(), setMoves(), and setPairPotentials().
                                                         {
   std::ostringstream os;
   os << std::setprecision(15) << val;
   return os.str();
}
void parseJson (const std::stringfilename, rapidjson::Document &doc)
Parse a JSON file and return the corresponding document.
Parameters:
filename Input JSON document's filename
doc Document object to store in
Definition at line 45 of file utilities.cpp.
References sendMsg().
Referenced by initialize(), checkpoint::load(), and setConfig().
                                                                  {
    try {
        FILE* fp = fopen(filename.c_str(), "r");
        char readBuffer[65536];
        rapidjson::FileReadStream is(fp, readBuffer, sizeof(readBuffer));
        doc.ParseStream(is);
        fclose(fp);
    } catch (...) {
        throw customException ("Unable to parse "+filename);
    }
    if (doc.IsObject()) {
        sendMsg("Parsed JSON file "+filename);
    } else {
        throw customException ("Error in "+filename+", not begin detected as proper JSON document");
    }
}
void pauseCode (long intdur)
Pause the code for a certain time.
Parameters:
dur Number of seconds to pause for
Definition at line 68 of file utilities.cpp.
                              {
    long int temp = time(NULL) + dur;
    while(temp > time(NULL));
}
void pbc (std::vector< double > &pos, const std::vector< double > &box)
Replace a position inside a box assuming periodic boundary conditions.
Parameters:
pos Position to be placed in box
box Box dimensions
Definition at line 228 of file utilities.cpp.
Referenced by hardWallZ::energy(), squareWellWallZ::energy(), rightTriangleXZ::energy(), hardWallZ::inside(), and squareWellWallZ::inside().
                                                                      {
    // generally while loops are faster than round statements
    for (unsigned int i = 0; i < pos.size(); ++i) {
        while (pos[i] < 0.0) {
            pos[i] += box[i];
        }
        while (pos[i] >= box[i]) {
            pos[i] -= box[i];
        }
    }
}
double pbcDist2 (const std::vector< double > &p1, const std::vector< double > &p2, const std::vector< double > &box)
Calculate the minimum image distance squared between two coordinates assuming periodic boundary conditions. Coordinates do not have to be in the box to begin with.
Parameters:
\p1 Position 1
\p1 Position 2
\box Box size
Returns:
d2 (distance squared)
Definition at line 249 of file utilities.cpp.
Referenced by lennardJones::energy(), fsLennardJones::energy(), cylinderZ::energy(), tabulated::energy(), squareWell::energy(), hardCore::energy(), cylinderZ::inside(), and aggVolBias3::make().
                                                                                                                  {
    double d2 = 0.0;
    for (unsigned int i = 0; i < p2.size(); ++i) {
        double dr = p2[i] - p1[i];
        while (dr < -box[i]/2.0) {
            dr += box[i];
        }
        while (dr > box[i]/2.0) {
            dr -= box[i];
        }
        d2 += dr*dr;
    }
    return d2;
}
std::vector< double > random3DSurfaceVector (const doublemagnitude)
Chose a random vector sampled from a random distribution on the surface of a sphere.
Parameters:
magnitude Mangitude of the vector (radius of sphere)
Returns:
ans double3 containing coordinates of vector
Definition at line 166 of file utilities.cpp.
References rng(), and RNG_SEED.
Referenced by aggVolBias3::make().
                                                                    {
    int success = 0;
    std::vector < double > ans (3, 0);
    while (success == 0) {
        double r1 = rng(&RNG_SEED), r2 = rng(&RNG_SEED), x1 = 1.0-2.0*r1, x2 = 1.0-2.0*r2;
        double sum2 = x1*x1+x2*x2;
        if (sum2 < 1.0) {
            ans[0] = 2*x1*sqrt(1-sum2)*magnitude;
            ans[1] = 2*x2*sqrt(1-sum2)*magnitude;
            ans[2] = (1-2.0*sum2)*magnitude;
            success = 1;
        }
    }
    return ans;
}
double rng (int *idum)
Random number generator (from Numerical Recipes)
Parameters:
idum seed
Returns:
temp Pseudo-random number between [0, 1)
Definition at line 189 of file utilities.cpp.
References AM, IA1, IA2, IM1, IM2, IMM1, IQ1, IQ2, IR1, IR2, NDIV, NTAB, and RNMX.
Referenced by aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), moves::makeMove(), random3DSurfaceVector(), and quaternion::setRandomRot().
                       {
    int j;
    long k;
    static long idum2=123456789;
    static long iy=0;
    static long iv[NTAB];
    double temp;
    if (*idum <= 0) {
        if (-(*idum) < 1) *idum=1;
        else *idum = -(*idum);
        idum2=(*idum);
        for (j=NTAB+7;j>=0;j--) {
            k=(*idum)/IQ1;
            *idum=IA1*(*idum-k*IQ1)-k*IR1;
            if (*idum < 0) *idum += IM1;
            if (j < NTAB) iv[j] = *idum;
        } iy=iv[0];
    }
    k=(*idum)/IQ1;
    *idum=IA1*(*idum-k*IQ1)-k*IR1;
    if (*idum < 0) *idum += IM1;
    k=idum2/IQ2;
    idum2=IA2*(idum2-k*IQ2)-k*IR2;
    if (idum2 < 0) idum2 += IM2;
    j=iy/NDIV;
    iy=iv[j]-idum2;
    iv[j] = *idum;
    if (iy < 1) iy += IMM1;
    if ((temp=AM*iy) > RNMX) return RNMX;
    else return temp;
}
std::vector< std::vector < double > > rotationMatrix (const doublealpha, const doublebeta, const doublegamma)
Create 3D rotation matrix from angles (x, then y, then z)
Parameters:
alpha Radians to rotate centers by around x-axis
beta Radians to rotate centers by around y-axis
gamma Radians to rotate centers by around z-axis
Definition at line 129 of file utilities.cpp.
References matrixProduct().
                                                                                                              {
    std::vector < double > dummy (3, 0);
    std::vector < std::vector < double > > Rx (3, dummy), Ry(3, dummy), Rz(3, dummy), Ryx, Rzyx;
    // https://en.wikipedia.org/wiki/Rotation_matrix#General_rotations
    Rx[0][0] = 1.0;
    Rx[1][1] = cos(alpha);
    Rx[1][2] = -sin(alpha);
    Rx[2][1] = sin(alpha);
    Rx[2][2] = cos(alpha);
    Ry[0][0] = cos(beta);
    Ry[0][2] = sin(beta);
    Ry[1][1] = 1.0;
    Ry[2][0] = -sin(beta);
    Ry[2][2] = cos(beta);
    Rz[0][0] = cos(gamma);
    Rz[0][1] = -sin(gamma);
    Rz[1][0] = sin(gamma);
    Rz[1][1] = cos(gamma);
    Rz[2][2] = 1.0;
    Ryx = matrixProduct(Ry, Rx);
    Rzyx = matrixProduct(Rz, Ryx);
    return Rzyx;
}
void sendErr (const std::stringmsg)
Send a message to std::cerr.
Parameters:
msg Message as string
Definition at line 35 of file utilities.cpp.
References getTimeStamp().
Referenced by simSystem::addPotential(), checkBounds(), tabulated::energy(), initialize(), checkpoint::load(), moves::moves(), performCrossover(), performTMMC(), performWALA(), simSystem::readConfig(), sanityChecks(), setConfig(), and setMoves().
                                   {
    std::cerr << " *** ERROR: " << getTimeStamp() << " : " << msg << " *** " << std::endl;
}
void sendMsg (const std::stringmsg)
Send a message to std::cout.
Parameters:
msg Message as string
Definition at line 26 of file utilities.cpp.
References getTimeStamp().
Referenced by simSystem::addPotential(), initialize(), checkpoint::load(), tabulated::loadPotential(), parseJson(), performCrossover(), performTMMC(), performWALA(), simSystem::readConfig(), sanityChecks(), setBarriers(), and setConfig().
                                   {
    std::cout << getTimeStamp() << " : " << msg << std::endl;
}
std::vector< std::string > splitstr (const std::string &s, chardelim)
C++ explode a string.
Definition at line 76 of file utilities.cpp.
                                                                  {
    std::stringstream ss(s);
    std::string item;
    std::vector <std::string> tokens;
    while (std::getline(ss, item, delim)) {
        tokens.push_back(item);
    }
    return tokens;
}
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.