/home/nam4/Desktop/sandbox/FHMCSimulation/src/utilities.cpp
NAME
/home/nam4/Desktop/sandbox/FHMCSimulation/src/utilities.cpp -
SYNOPSIS
#include 'utilities.h'
Macros
#define IM1 2147483563
#define IM2 2147483399
#define AM (1.0/IM1)
#define IMM1 (IM1-1)
#define IA1 40014
#define IA2 40692
#define IQ1 53668
#define IQ2 52774
#define IR1 12211
#define IR2 3791
#define NTAB 32
#define NDIV (1+IMM1/NTAB)
#define EPS 1.2e-7
#define RNMX (1.0-EPS)
Functions
void sendMsg (const std::string msg)
Send a message to std::cout.
void sendErr (const std::string msg)
Send a message to std::cerr.
void parseJson (const std::string filename, rapidjson::Document &doc)
Parse a JSON file and return the corresponding document.
void pauseCode (long int dur)
Pause the code for a certain time.
std::vector< std::string > splitstr (const std::string &s, char delim)
C++ explode a string.
std::string getTimeStamp ()
Obtain instantaneous timestamp.
std::vector< std::vector
< double > > matrixProduct (std::vector< std::vector< double > > &mat1, std::vector< std::vector< double > > &mat2)"
Compute product of 2 matrices, W = UV.
std::vector< std::vector
< double > > rotationMatrix (const double alpha, const double beta, const double gamma)"
Create 3D rotation matrix from angles (x, then y, then z)
std::vector< double > random3DSurfaceVector (const double magnitude)
Chose a random vector sampled from a random distribution on the surface of a sphere.
double rng (int *idum)
Random number generator (from Numerical Recipes)
void pbc (std::vector< double > &pos, const std::vector< double > &box)
Replace a position inside a box assuming periodic boundary conditions.
double pbcDist2 (const std::vector< double > &p1, const std::vector< double > &p2, const std::vector< double > &box)
Calculate the minimum image distance squared between two coordinates assuming periodic boundary conditions.
bool fileExists (std::string fileName)
Function to check whether a given file exists or not.
Variables
int RNG_SEED = -1024
Default RNG seed.
Macro Definition Documentation
#define AM (1.0/IM1)
Definition at line 8 of file utilities.cpp.
Referenced by rng().
#define EPS 1.2e-7
Definition at line 18 of file utilities.cpp.
#define IA1 40014
Definition at line 10 of file utilities.cpp.
Referenced by rng().
#define IA2 40692
Definition at line 11 of file utilities.cpp.
Referenced by rng().
#define IM1 2147483563
Definition at line 6 of file utilities.cpp.
Referenced by rng().
#define IM2 2147483399
Definition at line 7 of file utilities.cpp.
Referenced by rng().
#define IMM1 (IM1-1)
Definition at line 9 of file utilities.cpp.
Referenced by rng().
#define IQ1 53668
Definition at line 12 of file utilities.cpp.
Referenced by rng().
#define IQ2 52774
Definition at line 13 of file utilities.cpp.
Referenced by rng().
#define IR1 12211
Definition at line 14 of file utilities.cpp.
Referenced by rng().
#define IR2 3791
Definition at line 15 of file utilities.cpp.
Referenced by rng().
#define NDIV (1+IMM1/NTAB)
Definition at line 17 of file utilities.cpp.
Referenced by rng().
#define NTAB 32
Definition at line 16 of file utilities.cpp.
Referenced by rng().
#define RNMX (1.0-EPS)
Definition at line 19 of file utilities.cpp.
Referenced by rng().
Function Documentation
bool fileExists (std::stringfileName)
Function to check whether a given file exists or not.
Parameters:
fileName Name of file to check
Returns:
If file exists
Definition at line 271 of file utilities.cpp.
Referenced by checkpoint::checkpoint(), checkpoint::load(), and tabulated::loadPotential().
                                    {
    struct stat stFileInfo;
    if (stat(fileName.c_str(),&stFileInfo) == 0)
        return true;
    else
        return false;
}
std::string getTimeStamp ()
Obtain instantaneous timestamp.
Returns:
char* timestamp
Definition at line 90 of file utilities.cpp.
Referenced by checkpoint::dump(), moves::print(), sendErr(), and sendMsg().
                          {
    time_t rawtime;
    time (&rawtime);
    struct tm * timeinfo;
    timeinfo = localtime (&rawtime);
    char timestamp [80];
    strftime (timestamp,80,"%d/%m/%Y %H:%M:%S",timeinfo);
    std::string ans (timestamp);
    return ans;
}
std::vector< std::vector < double > > matrixProduct (std::vector< std::vector< double > > &mat1, std::vector< std::vector< double > > &mat2)
Compute product of 2 matrices, W = UV.
Parameters:
mat1 Matrix U
mat2 Matrix V
Returns:
W
Definition at line 108 of file utilities.cpp.
Referenced by rotationMatrix().
                                                                                                                                      {
    std::vector < double > dummy (3, 0);
    std::vector < std::vector < double > > W (3, dummy);
    for (unsigned int i = 0; i < 3; ++i) {
        for (unsigned int j = 0; j < 3; ++j) {
            W[i][j] = mat1[i][j]*mat2[j][i];
        }
    }
    return W;
}
void parseJson (const std::stringfilename, rapidjson::Document &doc)
Parse a JSON file and return the corresponding document.
Parameters:
filename Input JSON document's filename
Definition at line 44 of file utilities.cpp.
References sendMsg().
Referenced by initialize(), checkpoint::load(), and setConfig().
                                                                  {
    try {
        FILE* fp = fopen(filename.c_str(), "r");
        char readBuffer[65536];
        rapidjson::FileReadStream is(fp, readBuffer, sizeof(readBuffer));
        doc.ParseStream(is);
        fclose(fp);
    } catch (...) {
        throw customException ("Unable to parse "+filename);
    }
    if (doc.IsObject()) {
        sendMsg("Parsed JSON file "+filename);
    } else {
        throw customException ("Error in "+filename+", not begin detected as proper JSON document");
    }
}
void pauseCode (long intdur)
Pause the code for a certain time.
Parameters:
dur Number of seconds to pause for
Definition at line 67 of file utilities.cpp.
                              {
    long int temp = time(NULL) + dur;
    while(temp > time(NULL));
}
void pbc (std::vector< double > &pos, const std::vector< double > &box)
Replace a position inside a box assuming periodic boundary conditions.
Parameters:
pos Position to be placed in box
box Box dimensions
Definition at line 227 of file utilities.cpp.
Referenced by hardWallZ::energy(), squareWellWallZ::energy(), rightTriangleXZ::energy(), hardWallZ::inside(), and squareWellWallZ::inside().
                                                                      {
    // generally while loops are faster than round statements
    for (unsigned int i = 0; i < pos.size(); ++i) {
        while (pos[i] < 0.0) {
            pos[i] += box[i];
        }
        while (pos[i] >= box[i]) {
            pos[i] -= box[i];
        }
    }
}
double pbcDist2 (const std::vector< double > &p1, const std::vector< double > &p2, const std::vector< double > &box)
Calculate the minimum image distance squared between two coordinates assuming periodic boundary conditions. Coordinates do not have to be in the box to begin with.
Parameters:
\p1 Position 1
\p1 Position 2
\box Box size
Returns:
d2 (distance squared)
Definition at line 248 of file utilities.cpp.
Referenced by lennardJones::energy(), fsLennardJones::energy(), cylinderZ::energy(), tabulated::energy(), squareWell::energy(), hardCore::energy(), cylinderZ::inside(), and aggVolBias3::make().
                                                                                                                  {
    double d2 = 0.0;
    for (unsigned int i = 0; i < p2.size(); ++i) {
        double dr = p2[i] - p1[i];
        while (dr < -box[i]/2.0) {
            dr += box[i];
        }
        while (dr > box[i]/2.0) {
            dr -= box[i];
        }
        d2 += dr*dr;
    }
    return d2;
}
std::vector< double > random3DSurfaceVector (const doublemagnitude)
Chose a random vector sampled from a random distribution on the surface of a sphere.
Parameters:
magnitude Mangitude of the vector (radius of sphere)
Returns:
ans double3 containing coordinates of vector
Definition at line 165 of file utilities.cpp.
References rng(), and RNG_SEED.
Referenced by aggVolBias3::make().
                                                                    {
    int success = 0;
    std::vector < double > ans (3, 0);
    while (success == 0) {
        double r1 = rng(&RNG_SEED), r2 = rng(&RNG_SEED), x1 = 1.0-2.0*r1, x2 = 1.0-2.0*r2;
        double sum2 = x1*x1+x2*x2;
        if (sum2 < 1.0) {
            ans[0] = 2*x1*sqrt(1-sum2)*magnitude;
            ans[1] = 2*x2*sqrt(1-sum2)*magnitude;
            ans[2] = (1-2.0*sum2)*magnitude;
            success = 1;
        }
    }
    return ans;
}
double rng (int *idum)
Random number generator (from Numerical Recipes)
Parameters:
idum seed
Returns:
temp Pseudo-random number between [0, 1)
Definition at line 188 of file utilities.cpp.
References AM, IA1, IA2, IM1, IM2, IMM1, IQ1, IQ2, IR1, IR2, NDIV, NTAB, and RNMX.
Referenced by aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), swapParticles::make(), insertParticle::make(), moves::makeMove(), random3DSurfaceVector(), and quaternion::setRandomRot().
                       {
    int j;
    long k;
    static long idum2=123456789;
    static long iy=0;
    static long iv[NTAB];
    double temp;
    if (*idum <= 0) {
        if (-(*idum) < 1) *idum=1;
        else *idum = -(*idum);
        idum2=(*idum);
        for (j=NTAB+7;j>=0;j--) {
            k=(*idum)/IQ1;
            *idum=IA1*(*idum-k*IQ1)-k*IR1;
            if (*idum < 0) *idum += IM1;
            if (j < NTAB) iv[j] = *idum;
        } iy=iv[0];
    }
    k=(*idum)/IQ1;
    *idum=IA1*(*idum-k*IQ1)-k*IR1;
    if (*idum < 0) *idum += IM1;
    k=idum2/IQ2;
    idum2=IA2*(idum2-k*IQ2)-k*IR2;
    if (idum2 < 0) idum2 += IM2;
    j=iy/NDIV;
    iy=iv[j]-idum2;
    iv[j] = *idum;
    if (iy < 1) iy += IMM1;
    if ((temp=AM*iy) > RNMX) return RNMX;
    else return temp;
}
std::vector< std::vector < double > > rotationMatrix (const doublealpha, const doublebeta, const doublegamma)
Create 3D rotation matrix from angles (x, then y, then z)
Parameters:
alpha Radians to rotate centers by around x-axis
beta Radians to rotate centers by around y-axis
gamma Radians to rotate centers by around z-axis
Definition at line 128 of file utilities.cpp.
References matrixProduct().
                                                                                                              {
    std::vector < double > dummy (3, 0);
    std::vector < std::vector < double > > Rx (3, dummy), Ry(3, dummy), Rz(3, dummy), Ryx, Rzyx;
    // https://en.wikipedia.org/wiki/Rotation_matrix#General_rotations
    Rx[0][0] = 1.0;
    Rx[1][1] = cos(alpha);
    Rx[1][2] = -sin(alpha);
    Rx[2][1] = sin(alpha);
    Rx[2][2] = cos(alpha);
    Ry[0][0] = cos(beta);
    Ry[0][2] = sin(beta);
    Ry[1][1] = 1.0;
    Ry[2][0] = -sin(beta);
    Ry[2][2] = cos(beta);
    Rz[0][0] = cos(gamma);
    Rz[0][1] = -sin(gamma);
    Rz[1][0] = sin(gamma);
    Rz[1][1] = cos(gamma);
    Rz[2][2] = 1.0;
    Ryx = matrixProduct(Ry, Rx);
    Rzyx = matrixProduct(Rz, Ryx);
    return Rzyx;
}
void sendErr (const std::stringmsg)
Send a message to std::cerr.
Parameters:
msg Message as string
Definition at line 35 of file utilities.cpp.
References getTimeStamp().
Referenced by simSystem::addPotential(), checkBounds(), tabulated::energy(), initialize(), checkpoint::load(), tabulated::loadPotential(), moves::moves(), performCrossover(), performTMMC(), performWALA(), simSystem::readConfig(), sanityChecks(), setConfig(), setMoves(), setPairPotentials(), and setSystemBarriers().
                                   {
    std::cerr << " *** ERROR: " << getTimeStamp() << " : " << msg << " *** " << std::endl;
}
void sendMsg (const std::stringmsg)
Send a message to std::cout.
Parameters:
msg Message as string
Definition at line 26 of file utilities.cpp.
References getTimeStamp().
Referenced by simSystem::addPotential(), initialize(), checkpoint::load(), tabulated::loadPotential(), parseJson(), performCrossover(), performTMMC(), performWALA(), simSystem::readConfig(), sanityChecks(), and setConfig().
                                   {
    std::cout << getTimeStamp() << " : " << msg << std::endl;
}
std::vector< std::string > splitstr (const std::string &s, chardelim)
C++ explode a string.
Definition at line 75 of file utilities.cpp.
                                                                  {
    std::stringstream ss(s);
    std::string item;
    std::vector <std::string> tokens;
    while (std::getline(ss, item, delim)) {
        tokens.push_back(item);
    }
    return tokens;
}
Variable Documentation
int RNG_SEED = -1024
Default RNG seed.
Definition at line 3 of file utilities.cpp.
Referenced by initialize(), aggVolBias3::make(), deleteParticle::make(), translateParticle::make(), insertParticle::make(), swapParticles::make(), moves::makeMove(), random3DSurfaceVector(), and quaternion::setRandomRot().
Author
Generated automatically by Doxygen for Flat-Histogram Monte Carlo Simulation from the source code.